//! Intel GPU (Arc, Iris Xe) code generation for ECS-native IR operations.
//!
//! Lowers high-level IR operations (e.g., `linalg.matmul`) into SPIR-V assembly
//! style kernel source strings targeting the Intel Graphics Compiler (IGC) for
//! Intel Arc and Iris Xe GPUs.
//!
//! The generated kernels use `get_global_id` for 2D grid dispatch (one thread
//! per output element) with `global` pointers for the matmul operands. The
//! output format follows OpenCL C / SPIR-V transparent-bridge conventions and
//! resembles what IGC would consume from a lowered SPIR-V module.

use prism_ecs_core::{Entity, World};

use crate::ir_types::{FloatKind, TensorType, Type};
use crate::op::{op_name, operands};
use crate::value::ValueType;

/// Error type for Intel GPU lowering failures.
#[derive(Debug)]
pub enum IntelGpuLowerError {
    /// The operation is not one that can be lowered to Intel GPU code.
    UnsupportedOp(String),
    /// A required operand or result is missing.
    MissingOperand(String),
    /// An operand or result is missing a type annotation.
    MissingType(String),
}

impl std::fmt::Display for IntelGpuLowerError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::UnsupportedOp(msg) => write!(f, "unsupported op: {msg}"),
            Self::MissingOperand(msg) => write!(f, "missing operand: {msg}"),
            Self::MissingType(msg) => write!(f, "missing type: {msg}"),
        }
    }
}

impl std::error::Error for IntelGpuLowerError {}

// ── Element type mapping ─────────────────────────────────────────────────────

/// Map an IR element type to its OpenCL C / Intel GPU scalar type name.
fn element_type_to_intel(ty: &Type) -> &'static str {
    match ty {
        Type::Float(ft) => match ft.kind {
            FloatKind::F16 => "half",
            FloatKind::F32 => "float",
            FloatKind::F64 => "double",
            FloatKind::BF16 => "ushort", // storage-only on Intel
            FloatKind::F8E4M3 | FloatKind::F8E5M2 => "half", // fallback
        },
        Type::Integer(int_ty) if int_ty.width <= 8 => "char",
        Type::Integer(int_ty) if int_ty.width <= 16 => "short",
        Type::Integer(int_ty) if int_ty.width <= 32 => "int",
        Type::Integer(_) => "long",
        _ => "float",
    }
}

/// Extract a `TensorType` from a value entity's `ValueType` component.
fn require_tensor(
    world: &World,
    entity: Entity,
    label: &str,
) -> Result<TensorType, IntelGpuLowerError> {
    let vt = world
        .get_component::<ValueType>(entity)
        .map(|v| v.0.clone())
        .ok_or_else(|| IntelGpuLowerError::MissingType(format!("{} has no ValueType", label)))?;

    match vt {
        Type::Tensor(t) => Ok(t),
        _ => Err(IntelGpuLowerError::MissingType(format!(
            "{} is not a tensor type",
            label
        ))),
    }
}

/// Emit Intel GPU kernel pseudo-code for a matmul with the given dimensions.
#[rustfmt::skip]
fn emit_matmul_kernel(
    m: u64,
    n: u64,
    k: u64,
    intel_type: &str,
) -> String {
    format!(
        r#";; Intel GPU Kernel: matmul_{m}x{k}x{n}
;; Target: Intel Arc / Iris Xe
;; Auto-generated by prism-ecs-ir codegen_intel_gpu
;;
kernel void matmul_{m}x{k}x{n}(global const {t}* A, global const {t}* B, global {t}* C)
{{
    int i = get_global_id(1);
    int j = get_global_id(0);
    if (i >= {m} || j >= {n}) {{ return; }}

    {t} acc = 0.0f;
    for (int k = 0; k < {k}; k++)
    {{
        acc += A[i * {k} + k] * B[k * {n} + j];
    }}
    C[i * {n} + j] = acc;
}}
"#,
        m = m,
        n = n,
        k = k,
        t = intel_type,
    )
}

// ── Public API ───────────────────────────────────────────────────────────────

/// Lower a `linalg.matmul` to an Intel GPU kernel function.
///
/// Given a `linalg.matmul` op consuming operands `A`, `B`, `C` where the
/// semantics are `C += A @ B`, this function emits Intel GPU kernel pseudo-code
/// implementing the matrix multiplication as a 2D grid kernel — one thread
/// per output element `C[i][j]`.
///
/// Each operand **must** carry a `tensor<...>` type with a 2-D shape so that
/// the dimensions `M`, `K`, `N` can be extracted.
pub fn lower_matmul_to_intel_gpu(
    world: &World,
    matmul_op: Entity,
) -> Result<String, IntelGpuLowerError> {
    // 1. Verify the op is a matmul
    let name = op_name(world, matmul_op).unwrap_or_default();
    if name != "linalg.matmul" {
        return Err(IntelGpuLowerError::UnsupportedOp(format!(
            "expected 'linalg.matmul', got '{}'",
            name
        )));
    }

    // 2. Read operands
    let op_operands = operands(world, matmul_op);
    if op_operands.len() < 3 {
        return Err(IntelGpuLowerError::MissingOperand(format!(
            "matmul requires 3 operands (A, B, C), got {}",
            op_operands.len()
        )));
    }

    let a = op_operands[0];
    let b = op_operands[1];
    let c = op_operands[2];

    // 3. Extract tensor shapes
    let a_tensor = require_tensor(world, a, "operand A")?;
    let b_tensor = require_tensor(world, b, "operand B")?;
    let c_tensor = require_tensor(world, c, "operand C")?;

    // 4. Validate shapes: A[M,K] x B[K,N] = C[M,N]
    let shape_ok =
        a_tensor.shape.len() == 2 && b_tensor.shape.len() == 2 && c_tensor.shape.len() == 2;

    if !shape_ok {
        return Err(IntelGpuLowerError::MissingType(
            "all matmul operands must be 2-D tensors".into(),
        ));
    }

    let m = a_tensor.shape[0];
    let k_a = a_tensor.shape[1];
    let k_b = b_tensor.shape[0];
    let n = b_tensor.shape[1];
    let c_m = c_tensor.shape[0];
    let c_n = c_tensor.shape[1];

    if k_a != k_b {
        return Err(IntelGpuLowerError::MissingType(format!(
            "matmul dimension mismatch: A[1] = {k_a} ≠ B[0] = {k_b}"
        )));
    }
    if m != c_m || n != c_n {
        return Err(IntelGpuLowerError::MissingType(format!(
            "matmul result shape mismatch: expected [{m}, {n}], got [{c_m}, {c_n}]"
        )));
    }

    // 5. Emit kernel source
    let intel_type = element_type_to_intel(&a_tensor.element_type);
    Ok(emit_matmul_kernel(m, n, k_a, intel_type))
}

/// Lower any supported root IR operation to Intel GPU kernel source.
///
/// Dispatches to the appropriate lowering function based on the operation name.
pub fn lower_to_intel_gpu(world: &World, root_op: Entity) -> Result<String, IntelGpuLowerError> {
    match op_name(world, root_op).as_deref() {
        Some("linalg.matmul") => lower_matmul_to_intel_gpu(world, root_op),
        Some(name) => Err(IntelGpuLowerError::UnsupportedOp(format!(
            "no Intel GPU lowering available for '{name}'"
        ))),
        None => Err(IntelGpuLowerError::UnsupportedOp(
            "operation has no name".into(),
        )),
    }
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use prism_ecs_core::{EntityKind, World};

    use super::*;
    use crate::ir_types::{FloatKind, TensorType, Type};
    use crate::op::{OpAttributes, OpMarker, OpName, Operands, Results};
    use crate::value::{Uses, ValueDef, ValueType};

    // ── Helpers ──────────────────────────────────────────────────────────

    fn create_value(world: &mut World, label: &str, ty: Type) -> Entity {
        let entity: Entity = world
            .spawn(EntityKind::Node, Some(label.into()))
            .unwrap()
            .into();
        world
            .add_component(entity, ValueDef::op_result(Entity::new(0, 1), 0))
            .unwrap();
        world.add_component(entity, ValueType(ty)).unwrap();
        world.add_component(entity, Uses(vec![])).unwrap();
        entity
    }

    fn create_matmul_op(world: &mut World, a_ty: Type, b_ty: Type, c_ty: Type) -> Entity {
        let a = create_value(world, "A", a_ty.clone());
        let b = create_value(world, "B", b_ty.clone());
        let c = create_value(world, "C", c_ty.clone());
        let _result = create_value(world, "result", c_ty);

        let op: Entity = world
            .spawn(EntityKind::Node, Some("matmul".into()))
            .unwrap()
            .into();
        world.add_component(op, OpMarker).unwrap();
        world
            .add_component(op, OpName("linalg.matmul".into()))
            .unwrap();
        world.add_component(op, Operands(vec![a, b, c])).unwrap();
        world.add_component(op, Results(vec![])).unwrap();
        world.add_component(op, OpAttributes(vec![])).unwrap();
        op
    }

    // ── Tests ────────────────────────────────────────────────────────────

    #[test]
    fn lower_matmul_f32_2x3x4() {
        let mut world = World::new();

        let f32 = Type::float(FloatKind::F32);
        let a_ty = Type::Tensor(TensorType::new(vec![2, 3], f32.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![3, 4], f32.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 4], f32));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source = lower_matmul_to_intel_gpu(&world, op).expect("lowering failed");

        // Verify key structural elements from the acceptance criteria
        assert!(
            source.contains("Intel Arc"),
            "missing 'Intel Arc' in:\n{}",
            source
        );
        assert!(
            source.contains("get_global_id"),
            "missing 'get_global_id' in:\n{}",
            source
        );
        assert!(
            source.contains("matmul"),
            "missing 'matmul' in:\n{}",
            source
        );

        // Verify Intel GPU kernel structure
        assert!(
            source.contains("kernel void"),
            "missing 'kernel void' in:\n{}",
            source
        );
        assert!(
            source.contains("global float*"),
            "missing 'global float*' in:\n{}",
            source
        );
        assert!(source.contains("for ("), "missing 'for (' in:\n{}", source);
        assert!(
            source.contains("+="),
            "missing '+=' (accumulator) in:\n{}",
            source
        );
        assert!(
            source.contains("get_global_id(1)"),
            "missing row dispatch in:\n{}",
            source
        );
        assert!(
            source.contains("get_global_id(0)"),
            "missing col dispatch in:\n{}",
            source
        );

        // Verify dimension-specific content
        assert!(
            source.contains("matmul_2x3x4"),
            "kernel name should include MxKxN dimensions"
        );
        assert!(
            source.contains("if (i >= 2 || j >= 4)"),
            "missing bounds check"
        );

        assert!(
            source.contains("Intel Arc / Iris Xe"),
            "missing 'Intel Arc / Iris Xe' target in:\n{}",
            source
        );

        eprintln!("Generated Intel GPU source:\n{}", source);
    }

    #[test]
    fn lower_matmul_f16() {
        let mut world = World::new();

        let f16 = Type::float(FloatKind::F16);
        let a_ty = Type::Tensor(TensorType::new(vec![4, 8], f16.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![8, 16], f16.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![4, 16], f16));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source = lower_matmul_to_intel_gpu(&world, op).expect("lowering failed");

        assert!(source.contains("global half*"), "expected half pointers");
        assert!(
            source.contains("half acc = 0.0f"),
            "expected half accumulator"
        );
        assert!(source.contains("matmul_4x8x16"));
    }

    #[test]
    fn lower_matmul_f64() {
        let mut world = World::new();

        let f64 = Type::float(FloatKind::F64);
        let a_ty = Type::Tensor(TensorType::new(vec![1, 1], f64.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![1, 1], f64.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![1, 1], f64));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source = lower_matmul_to_intel_gpu(&world, op).expect("lowering failed");

        assert!(source.contains("global double*"));
        assert!(source.contains("double acc = 0.0f"));
    }

    #[test]
    fn error_wrong_op_name() {
        let mut world = World::new();
        let entity: Entity = world
            .spawn(EntityKind::Node, Some("bad".into()))
            .unwrap()
            .into();
        world.add_component(entity, OpMarker).unwrap();
        world
            .add_component(entity, OpName("arith.addf".into()))
            .unwrap();

        let err = lower_matmul_to_intel_gpu(&world, entity).unwrap_err();
        match err {
            IntelGpuLowerError::UnsupportedOp(msg) => {
                assert!(msg.contains("linalg.matmul"));
            }
            _ => panic!("expected UnsupportedOp, got {:?}", err),
        }
    }

    #[test]
    fn error_missing_operands() {
        let mut world = World::new();
        let entity: Entity = world
            .spawn(EntityKind::Node, Some("bad".into()))
            .unwrap()
            .into();
        world.add_component(entity, OpMarker).unwrap();
        world
            .add_component(entity, OpName("linalg.matmul".into()))
            .unwrap();
        world.add_component(entity, Operands(vec![])).unwrap();
        world.add_component(entity, Results(vec![])).unwrap();

        let err = lower_matmul_to_intel_gpu(&world, entity).unwrap_err();
        match err {
            IntelGpuLowerError::MissingOperand(_) => {}
            _ => panic!("expected MissingOperand, got {:?}", err),
        }
    }

    #[test]
    fn error_non_tensor_operand() {
        let mut world = World::new();

        let scalar = Type::float(FloatKind::F32);
        let a = create_value(&mut world, "A", scalar.clone());
        let b = create_value(&mut world, "B", scalar.clone());
        let c = create_value(&mut world, "C", scalar);

        let op: Entity = world
            .spawn(EntityKind::Node, Some("bad".into()))
            .unwrap()
            .into();
        world.add_component(op, OpMarker).unwrap();
        world
            .add_component(op, OpName("linalg.matmul".into()))
            .unwrap();
        world.add_component(op, Operands(vec![a, b, c])).unwrap();
        world.add_component(op, Results(vec![])).unwrap();

        let err = lower_matmul_to_intel_gpu(&world, op).unwrap_err();
        match err {
            IntelGpuLowerError::MissingType(_) => {}
            _ => panic!("expected MissingType, got {:?}", err),
        }
    }

    #[test]
    fn error_dimension_mismatch() {
        let mut world = World::new();

        let f32 = Type::float(FloatKind::F32);
        let a_ty = Type::Tensor(TensorType::new(vec![2, 3], f32.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![4, 5], f32.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 4], f32));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let err = lower_matmul_to_intel_gpu(&world, op).unwrap_err();
        match err {
            IntelGpuLowerError::MissingType(_) => {}
            _ => panic!("expected MissingType, got {:?}", err),
        }
    }

    #[test]
    fn lower_to_intel_gpu_dispatches_matmul() {
        let mut world = World::new();

        let f32 = Type::float(FloatKind::F32);
        let a_ty = Type::Tensor(TensorType::new(vec![2, 3], f32.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![3, 4], f32.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 4], f32));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source = lower_to_intel_gpu(&world, op).expect("dispatch failed");
        assert!(source.contains("kernel void"));
        assert!(source.contains("global float*"));
        assert!(source.contains("Intel Arc"));
        assert!(source.contains("get_global_id"));
    }

    #[test]
    fn lower_to_intel_gpu_unknown_op() {
        let mut world = World::new();
        let entity: Entity = world
            .spawn(EntityKind::Node, Some("unknown".into()))
            .unwrap()
            .into();
        world.add_component(entity, OpMarker).unwrap();
        world
            .add_component(entity, OpName("unknown.op".into()))
            .unwrap();

        let err = lower_to_intel_gpu(&world, entity).unwrap_err();
        match err {
            IntelGpuLowerError::UnsupportedOp(_) => {}
            _ => panic!("expected UnsupportedOp, got {:?}", err),
        }
    }
}
