//! Metal Shading Language code generation for ECS-native IR operations.
//!
//! Lowers high-level IR operations (e.g., `linalg.matmul`) into Metal kernel
//! function source strings suitable for compilation by the Metal runtime.
//!
//! The generated kernels use a 2D grid dispatch (one thread per output element)
//! with device pointers for the matmul operands.

use prism_ecs_core::{Entity, World};

use crate::backend_dispatch::HalFormat;
use crate::evolution::{
    get_assigned_format, resolve_matmul_tile, CompilePlanRef, FormatAssignment, TensorFormat,
};
use crate::ir_types::{FloatKind, Signedness, TensorType, Type};
use crate::op::{op_name, operands};
use crate::value::ValueType;

/// Error type for Metal lowering failures.
#[derive(Debug)]
pub enum MetalLowerError {
    /// The operation is not one that can be lowered to Metal.
    NotAMatmulOp(String),
    /// The operation is not a batch_matmul.
    NotABatchMatmulOp(String),
    /// A required operand or result is missing.
    MissingOperand(String),
    /// An operand or result is missing a type annotation.
    MissingType(String),
    /// An unsupported tensor encoding (format) was requested.
    UnsupportedEncoding(String),
}

// ── Element type mapping ─────────────────────────────────────────────────────

/// Map an IR element type to its Metal Shading Language scalar type name.
fn element_type_to_metal(ty: &Type) -> &'static str {
    match ty {
        Type::Float(ft) => match ft.kind {
            FloatKind::F16 => "half",
            FloatKind::F32 => "float",
            FloatKind::F64 => "double",
            FloatKind::BF16 => "bfloat",
            FloatKind::F8E4M3 | FloatKind::F8E5M2 => "half", // fallback
        },
        Type::Integer(int_ty) if int_ty.width <= 8 => "char",
        Type::Integer(int_ty) if int_ty.width <= 16 => "short",
        Type::Integer(int_ty) if int_ty.width <= 32 => "int",
        Type::Integer(_) => "long",
        _ => "float",
    }
}

// ── Tensor encoding detection ────────────────────────────────────────────────

/// Discriminant for special packed tensor encodings that affect code emission.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum TensorEncoding {
    /// Standard floating-point tensor.
    Float,
    /// Ternary 1.58-bit format — 8-bit signed ints representing {-1, 0, 1}.
    Ternary158,
    /// Binary 1-bit format — packed bits, one weight per bit.
    Binary1,
}

/// Detect the tensor encoding from its element type.
fn detect_tensor_encoding(ty: &Type) -> TensorEncoding {
    match ty {
        Type::Integer(int_ty) if int_ty.width <= 1 => TensorEncoding::Binary1,
        Type::Integer(int_ty) if int_ty.width == 8 && int_ty.signedness == Signedness::Signed => {
            TensorEncoding::Ternary158
        }
        _ => TensorEncoding::Float,
    }
}

/// Extract a `TensorType` from a value entity's `ValueType` component.
fn require_tensor(
    world: &World,
    entity: Entity,
    label: &str,
) -> Result<TensorType, MetalLowerError> {
    let vt = world
        .get_component::<ValueType>(entity)
        .map(|v| v.0.clone())
        .ok_or_else(|| MetalLowerError::MissingType(format!("{} has no ValueType", label)))?;

    match vt {
        Type::Tensor(t) => Ok(t),
        _ => Err(MetalLowerError::MissingType(format!(
            "{} is not a tensor type",
            label
        ))),
    }
}

#[rustfmt::skip]
fn emit_matmul_kernel(
    m: u64, n: u64, k: u64,
    tile_m: u64,
    tile_n: u64,
    tile_k: u64,
    metal_type: &str,
) -> String {
    let has_tiles = (tile_m, tile_n, tile_k) != (64, 64, 32);
    let kernel_name = if has_tiles {
        format!("matmul_{}x{}_tile_{}x{}x{}", m, n, tile_m, tile_k, tile_n)
    } else {
        format!("matmul_{}x{}_device", m, n)
    };
    format!(
        r#"// Auto-generated by prism-ecs-ir codegen_metal

kernel void {kernel_name}(
    device const {t}* A [[buffer(0)]],
    device const {t}* B [[buffer(1)]],
    device {t}* C [[buffer(2)]],
    uint2 gid [[thread_position_in_grid]]
) {{
    // Tile: {tile_m}x{tile_k}x{tile_n} (MxKxN threadblock)
    const uint i = gid.y;
    const uint j = gid.x;
    if (i >= {m} || j >= {n}) {{ return; }}

    {t} acc = 0.0;
    for (uint k = 0; k < {k}; ++k) {{
        acc += A[i * {k} + k] * B[k * {n} + j];
    }}
    C[i * {n} + j] = acc;
}}
"#,
        m = m, n = n, k = k, t = metal_type,
        tile_m = tile_m, tile_n = tile_n, tile_k = tile_k, kernel_name = kernel_name,
    )
}

// ── Batch matmul kernel (3-D grid dispatch) ────────────────────────────────
#[allow(clippy::too_many_arguments)]
#[rustfmt::skip]
fn emit_batch_matmul_kernel(
    m: u64, n: u64, k: u64, batch: u64,
    tile_m: u64,
    tile_n: u64,
    tile_k: u64,
    metal_type: &str,
) -> String {
    let has_tiles = (tile_m, tile_n, tile_k) != (64, 64, 32);
    let kernel_name = if has_tiles {
        format!("batch_matmul_{}x{}x{}_tile_{}x{}x{}", m, n, batch, tile_m, tile_k, tile_n)
    } else {
        format!("batch_matmul_{}x{}x{}_device", m, n, batch)
    };
    format!(
        r#"// Auto-generated by prism-ecs-ir codegen_metal

kernel void {kernel_name}(
    device const {t}* A [[buffer(0)]],
    device const {t}* B [[buffer(1)]],
    device {t}* C [[buffer(2)]],
    uint3 gid [[thread_position_in_grid]]
) {{
    // Tile: {tile_m}x{tile_k}x{tile_n} (MxKxN threadblock)
    // gid.z = batch index (depth)
    const uint depth = gid.z;
    const uint i = gid.y;
    const uint j = gid.x;
    if (i >= {m} || j >= {n} || depth >= {batch}) {{ return; }}

    const uint a_base = depth * {m} * {k};
    const uint b_base = depth * {k} * {n};
    const uint c_base = depth * {m} * {n};

    {t} acc = 0.0;
    for (uint kk = 0; kk < {k}; ++kk) {{
        acc += A[a_base + i * {k} + kk] * B[b_base + kk * {n} + j];
    }}
    C[c_base + i * {n} + j] = acc;
}}
"#,
        m = m, n = n, k = k, batch = batch, t = metal_type,
        tile_m = tile_m, tile_n = tile_n, tile_k = tile_k, kernel_name = kernel_name,
    )
}

// ── Ternary matmul kernel (half-precision accumulator, no multiply) ─────────

#[rustfmt::skip]
fn emit_ternary_matmul_kernel(
    m: u64, n: u64, k: u64,
    tile_m: u64,
    tile_n: u64,
    tile_k: u64,
) -> String {
    let has_tiles = (tile_m, tile_n, tile_k) != (64, 64, 32);
    let kernel_name = if has_tiles {
        format!("ternary_matmul_{}x{}_tile_{}x{}x{}", m, n, tile_m, tile_k, tile_n)
    } else {
        format!("ternary_matmul_{}x{}_device", m, n)
    };
    format!(
        r#"// Auto-generated by prism-ecs-ir codegen_metal

kernel void {kernel_name}(
    device const char* A [[buffer(0)]],
    device const half* B [[buffer(1)]],
    device half* C [[buffer(2)]],
    uint2 gid [[thread_position_in_grid]]
) {{
    // Tile: {tile_m}x{tile_k}x{tile_n} (MxKxN threadblock)
    const uint i = gid.y;
    const uint j = gid.x;
    if (i >= {m} || j >= {n}) {{ return; }}

    half acc = 0.0h;
    for (uint kk = 0; kk < {k}; ++kk) {{
        char a_val = A[i * {k} + kk];
        half b_val = B[kk * {n} + j];
        // Ternary {{-1, 0, 1}} — no multiply
        if (a_val > 0) {{
            acc += b_val;
        }} else if (a_val < 0) {{
            acc -= b_val;
        }}
    }}
    C[i * {n} + j] = acc;
}}
"#,
        m = m, n = n, k = k,
        tile_m = tile_m, tile_n = tile_n, tile_k = tile_k, kernel_name = kernel_name,
    )
}

// ── Binary matmul kernel (popcount-based dot product) ───────────────────────

#[rustfmt::skip]
fn emit_binary_matmul_kernel(
    m: u64, n: u64, k: u64,
    tile_m: u64,
    tile_n: u64,
    tile_k: u64,
) -> String {
    let has_tiles = (tile_m, tile_n, tile_k) != (64, 64, 32);
    let kernel_name = if has_tiles {
        format!("binary_matmul_{}x{}_tile_{}x{}x{}", m, n, tile_m, tile_k, tile_n)
    } else {
        format!("binary_matmul_{}x{}_device", m, n)
    };
    // For binary matmul, K is the number of packed bytes (8 weights per byte)
    let k_packed = k / 8;
    format!(
        r#"// Auto-generated by prism-ecs-ir codegen_metal

kernel void {kernel_name}(
    device const uchar* A [[buffer(0)]],
    device const uchar* B [[buffer(1)]],
    device int* C [[buffer(2)]],
    uint2 gid [[thread_position_in_grid]]
) {{
    // Tile: {tile_m}x{tile_k}x{tile_n} (MxKxN threadblock)
    const uint i = gid.y;
    const uint j = gid.x;
    if (i >= {m} || j >= {n}) {{ return; }}

    int acc = 0;
    for (uint kk = 0; kk < {k_packed}; ++kk) {{
        // Popcount-based binary dot product
        acc += popcount(A[i * {k_packed} + kk] & B[kk * {n} + j]);
    }}
    C[i * {n} + j] = acc;
}}
"#,
        m = m, n = n, k_packed = k_packed,
        tile_m = tile_m, tile_n = tile_n, tile_k = tile_k, kernel_name = kernel_name,
    )
}

// ── Public API ───────────────────────────────────────────────────────────────

/// Lower a `linalg.matmul` to a Metal kernel function.
///
/// Given a `linalg.matmul` op consuming operands `A`, `B`, `C` where the
/// semantics are `C += A @ B`, this function emits Metal Shading Language
/// source code implementing the matrix multiplication as a 2D grid kernel —
/// one thread per output element `C[i][j]`.
///
/// Each operand **must** carry a `tensor<...>` type with a 2-D shape so that
/// the dimensions `M`, `K`, `N` can be extracted.
pub fn lower_matmul_to_metal(world: &World, matmul_op: Entity) -> Result<String, MetalLowerError> {
    // 1. Verify the op is a matmul
    let name = op_name(world, matmul_op).unwrap_or_default();
    if name != "linalg.matmul" {
        return Err(MetalLowerError::NotAMatmulOp(format!(
            "expected 'linalg.matmul', got '{}'",
            name
        )));
    }

    // 2. Read operands
    let op_operands = operands(world, matmul_op);
    if op_operands.len() < 3 {
        return Err(MetalLowerError::MissingOperand(format!(
            "matmul requires 3 operands (A, B, C), got {}",
            op_operands.len()
        )));
    }

    let a = op_operands[0];
    let b = op_operands[1];
    let c = op_operands[2];

    // 3. Extract tensor shapes
    let a_tensor = require_tensor(world, a, "operand A")?;
    let b_tensor = require_tensor(world, b, "operand B")?;
    let c_tensor = require_tensor(world, c, "operand C")?;

    // 4. Validate shapes: A[M,K] x B[K,N] = C[M,N]
    let shape_ok =
        a_tensor.shape.len() == 2 && b_tensor.shape.len() == 2 && c_tensor.shape.len() == 2;

    if !shape_ok {
        return Err(MetalLowerError::MissingType(
            "all matmul operands must be 2-D tensors".into(),
        ));
    }

    let m = a_tensor.shape[0];
    let k_a = a_tensor.shape[1];
    let k_b = b_tensor.shape[0];
    let n = b_tensor.shape[1];
    let c_m = c_tensor.shape[0];
    let c_n = c_tensor.shape[1];

    if k_a != k_b {
        return Err(MetalLowerError::MissingType(format!(
            "matmul dimension mismatch: A[1] = {k_a} ≠ B[0] = {k_b}"
        )));
    }
    if m != c_m || n != c_n {
        return Err(MetalLowerError::MissingType(format!(
            "matmul result shape mismatch: expected [{m}, {n}], got [{c_m}, {c_n}]"
        )));
    }

    // 5. Emit kernel source
    // Check for FormatAssignment — if any operand has Ternary158 or Binary1
    // assigned, emit the corresponding kernel variant instead of standard FP16.
    let assigned_a = get_assigned_format(world, a);
    let assigned_b = get_assigned_format(world, b);

    // Prefer the weight operand (B) for format selection; fall back to A.
    let fmt = assigned_b.or(assigned_a).map(|(fmt, _op)| fmt).or_else(|| {
        world
            .get_component::<CompilePlanRef>(matmul_op)
            .and_then(|r| world.get_component::<FormatAssignment>(r.0).map(|f| f.0))
    });

    let (tile_m, tile_n, tile_k) =
        resolve_matmul_tile(world, matmul_op, m as u32, n as u32, k_a as u32);
    match fmt {
        Some(TensorFormat::Ternary158) => Ok(emit_ternary_matmul_kernel(
            m,
            n,
            k_a,
            tile_m.into(),
            tile_n.into(),
            tile_k.into(),
        )),
        Some(TensorFormat::Binary1) => Ok(emit_binary_matmul_kernel(
            m,
            n,
            k_a,
            tile_m.into(),
            tile_n.into(),
            tile_k.into(),
        )),
        _ => {
            let metal_type = element_type_to_metal(&a_tensor.element_type);
            Ok(emit_matmul_kernel(
                m,
                n,
                k_a,
                tile_m.into(),
                tile_n.into(),
                tile_k.into(),
                metal_type,
            ))
        }
    }
}

/// Lower a `linalg.batch_matmul` to a Metal kernel function.
///
/// Given a `linalg.batch_matmul` op consuming operands `A`, `B`, `C` where the
/// semantics are `C[b, :, :] += A[b, :, :] @ B[b, :, :]`, this function emits
/// Metal Shading Language source code implementing the batched matrix
/// multiplication as a 3D grid kernel — one thread per output element
/// `C[batch][i][j]`. The grid depth dimension is the batch size.
///
/// Each operand **must** carry a `tensor<...>` type with a 3-D shape so that
/// the dimensions `B`, `M`, `K`, `N` can be extracted.
pub fn lower_batch_matmul_to_metal(
    world: &World,
    batch_op: Entity,
) -> Result<String, MetalLowerError> {
    // 1. Verify the op is a batch_matmul
    let name = op_name(world, batch_op).unwrap_or_default();
    if name != "linalg.batch_matmul" {
        return Err(MetalLowerError::NotABatchMatmulOp(format!(
            "expected 'linalg.batch_matmul', got '{}'",
            name
        )));
    }

    // 2. Read operands
    let op_operands = operands(world, batch_op);
    if op_operands.len() < 3 {
        return Err(MetalLowerError::MissingOperand(format!(
            "batch_matmul requires 3 operands (A, B, C), got {}",
            op_operands.len()
        )));
    }

    let a = op_operands[0];
    let b = op_operands[1];
    let c = op_operands[2];

    // 3. Extract tensor shapes — all must be 3-D
    let a_tensor = require_tensor(world, a, "operand A")?;
    let b_tensor = require_tensor(world, b, "operand B")?;
    let c_tensor = require_tensor(world, c, "operand C")?;

    let shape_ok =
        a_tensor.shape.len() == 3 && b_tensor.shape.len() == 3 && c_tensor.shape.len() == 3;

    if !shape_ok {
        return Err(MetalLowerError::MissingType(
            "all batch_matmul operands must be 3-D tensors".into(),
        ));
    }

    let batch = a_tensor.shape[0];
    let batch_b = b_tensor.shape[0];
    let batch_c = c_tensor.shape[0];
    if batch != batch_b || batch != batch_c {
        return Err(MetalLowerError::MissingType(format!(
            "batch_matmul batch dimension mismatch: A[0] = {batch}, B[0] = {batch_b}, C[0] = {batch_c}"
        )));
    }

    let m = a_tensor.shape[1];
    let k_a = a_tensor.shape[2];
    let k_b = b_tensor.shape[1];
    let n = b_tensor.shape[2];
    let c_m = c_tensor.shape[1];
    let c_n = c_tensor.shape[2];

    if k_a != k_b {
        return Err(MetalLowerError::MissingType(format!(
            "batch_matmul dimension mismatch: A[2] = {k_a} ≠ B[1] = {k_b}"
        )));
    }
    if m != c_m || n != c_n {
        return Err(MetalLowerError::MissingType(format!(
            "batch_matmul result shape mismatch: expected [{batch}, {m}, {n}], got [{batch_c}, {c_m}, {c_n}]"
        )));
    }

    // 5. Emit kernel source
    let (tile_m, tile_n, tile_k) =
        resolve_matmul_tile(world, batch_op, m as u32, n as u32, k_a as u32);
    let metal_type = element_type_to_metal(&a_tensor.element_type);
    Ok(emit_batch_matmul_kernel(
        m,
        n,
        k_a,
        batch,
        tile_m.into(),
        tile_n.into(),
        tile_k.into(),
        metal_type,
    ))
}

/// Lower a ternary (or binary) matmul to a Metal kernel function.
///
/// Given a `linalg.ternary_matmul` op consuming operands `A`, `B`, `C` where
/// the semantics are `C += A @ B`, this function detects the tensor encoding
/// (Ternary158 or Binary1) from the element type annotation and emits
/// appropriate Metal Shading Language source:
///
/// - **Ternary158**: operands are 8-bit signed integers {-1, 0, 1}; uses a
///   `half`-precision accumulator and conditional addition/subtraction
///   (no multiplication instructions).
/// - **Binary1**: operands are packed 1-bit values; uses `popcount` for the
///   dot product.
///
/// Each operand **must** carry a `tensor<...>` type with a 2-D shape so that
/// the dimensions `M`, `K`, `N` can be extracted.
pub fn lower_ternary_matmul_to_metal(
    world: &World,
    matmul_op: Entity,
) -> Result<String, MetalLowerError> {
    // 1. Verify the op is a ternary_matmul
    let name = op_name(world, matmul_op).unwrap_or_default();
    if name != "linalg.ternary_matmul" {
        return Err(MetalLowerError::NotAMatmulOp(format!(
            "expected 'linalg.ternary_matmul', got '{}'",
            name
        )));
    }

    // 2. Read operands
    let op_operands = operands(world, matmul_op);
    if op_operands.len() < 3 {
        return Err(MetalLowerError::MissingOperand(format!(
            "ternary_matmul requires 3 operands (A, B, C), got {}",
            op_operands.len()
        )));
    }

    let a = op_operands[0];
    let b = op_operands[1];
    let c = op_operands[2];

    // 3. Extract tensor shapes
    let a_tensor = require_tensor(world, a, "operand A")?;
    let b_tensor = require_tensor(world, b, "operand B")?;
    let c_tensor = require_tensor(world, c, "operand C")?;

    let shape_ok =
        a_tensor.shape.len() == 2 && b_tensor.shape.len() == 2 && c_tensor.shape.len() == 2;

    if !shape_ok {
        return Err(MetalLowerError::MissingType(
            "all ternary_matmul operands must be 2-D tensors".into(),
        ));
    }

    let m = a_tensor.shape[0];
    let k_a = a_tensor.shape[1];
    let k_b = b_tensor.shape[0];
    let n = b_tensor.shape[1];
    let c_m = c_tensor.shape[0];
    let c_n = c_tensor.shape[1];

    if k_a != k_b {
        return Err(MetalLowerError::MissingType(format!(
            "ternary_matmul dimension mismatch: A[1] = {k_a} ≠ B[0] = {k_b}"
        )));
    }
    if m != c_m || n != c_n {
        return Err(MetalLowerError::MissingType(format!(
            "ternary_matmul result shape mismatch: expected [{m}, {n}], got [{c_m}, {c_n}]"
        )));
    }

    // 4. Detect tensor encoding from element type and emit appropriate kernel
    let (tile_m, tile_n, tile_k) =
        resolve_matmul_tile(world, matmul_op, m as u32, n as u32, k_a as u32);
    let encoding = detect_tensor_encoding(&a_tensor.element_type);
    match encoding {
        TensorEncoding::Ternary158 => Ok(emit_ternary_matmul_kernel(
            m,
            n,
            k_a,
            tile_m.into(),
            tile_n.into(),
            tile_k.into(),
        )),
        TensorEncoding::Binary1 => Ok(emit_binary_matmul_kernel(
            m,
            n,
            k_a,
            tile_m.into(),
            tile_n.into(),
            tile_k.into(),
        )),
        TensorEncoding::Float => Err(MetalLowerError::UnsupportedEncoding(
            "ternary_matmul requires Ternary158 or Binary1 element type, got float".into(),
        )),
    }
}

/// Lower any supported root IR operation to Metal source.
///
/// Dispatches to the appropriate lowering function based on the operation name.
pub fn lower_to_metal(world: &World, root_op: Entity) -> Result<String, MetalLowerError> {
    match op_name(world, root_op).as_deref() {
        Some("linalg.matmul") => lower_matmul_to_metal(world, root_op),
        Some("linalg.batch_matmul") => lower_batch_matmul_to_metal(world, root_op),
        Some("linalg.ternary_matmul") => lower_ternary_matmul_to_metal(world, root_op),
        Some(name) => Err(MetalLowerError::NotAMatmulOp(format!(
            "no Metal lowering available for '{name}'"
        ))),
        None => Err(MetalLowerError::NotAMatmulOp(
            "operation has no name".into(),
        )),
    }
}
/// Public constant exposing the Metal HAL format for dispatch from `hal.rs`.
pub const METAL_FORMAT: HalFormat = HalFormat::Metal;

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use prism_ecs_core::{EntityKind, World};

    use super::*;
    use crate::evolution::{CompilePlan, CompilePlanRef, FormatAssignment, TensorFormat};
    use crate::ir_types::{FloatKind, TensorType, Type};
    use crate::op::{OpAttributes, OpMarker, OpName, Operands, Results};
    use crate::value::{Uses, ValueDef, ValueType};

    // ── Helpers ──────────────────────────────────────────────────────────

    fn create_value(world: &mut World, label: &str, ty: Type) -> Entity {
        let entity: Entity = world
            .spawn(EntityKind::Node, Some(label.into()))
            .unwrap()
            .into();
        world
            .add_component(entity, ValueDef::op_result(Entity::new(0, 1), 0))
            .unwrap();
        world.add_component(entity, ValueType(ty)).unwrap();
        world.add_component(entity, Uses(vec![])).unwrap();
        entity
    }

    fn create_matmul_op(world: &mut World, a_ty: Type, b_ty: Type, c_ty: Type) -> Entity {
        let a = create_value(world, "A", a_ty.clone());
        let b = create_value(world, "B", b_ty.clone());
        let c = create_value(world, "C", c_ty.clone());
        let _result = create_value(world, "result", c_ty);

        let op: Entity = world
            .spawn(EntityKind::Node, Some("matmul".into()))
            .unwrap()
            .into();
        world.add_component(op, OpMarker).unwrap();
        world
            .add_component(op, OpName("linalg.matmul".into()))
            .unwrap();
        world.add_component(op, Operands(vec![a, b, c])).unwrap();
        world.add_component(op, Results(vec![])).unwrap();
        world.add_component(op, OpAttributes(vec![])).unwrap();
        op
    }

    // ── Tests ────────────────────────────────────────────────────────────

    #[test]
    fn lower_matmul_f32_2x3x4() {
        let mut world = World::new();

        let f32 = Type::float(FloatKind::F32);
        let a_ty = Type::Tensor(TensorType::new(vec![2, 3], f32.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![3, 4], f32.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 4], f32));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source = lower_matmul_to_metal(&world, op).expect("lowering failed");

        // Verify key structural elements
        assert!(
            source.contains("kernel void"),
            "missing 'kernel void' in:\n{}",
            source
        );
        assert!(
            source.contains("device float*"),
            "missing 'device float*' in:\n{}",
            source
        );
        assert!(source.contains("for ("), "missing 'for (' in:\n{}", source);
        assert!(
            source.contains("+="),
            "missing '+=' (accumulator) in:\n{}",
            source
        );

        // Verify dimension-specific content
        assert!(
            source.contains("matmul_2x4_device"),
            "kernel name should include MxN dimensions"
        );
        assert!(
            source.contains("if (i >= 2 || j >= 4)"),
            "missing bounds check"
        );
        assert!(source.contains("[[buffer(0)]]"), "missing buffer attribute");
        assert!(
            source.contains("[[thread_position_in_grid]]"),
            "missing thread_position_in_grid"
        );

        eprintln!("Generated Metal source:\n{}", source);
    }

    #[test]
    fn lower_matmul_f16() {
        let mut world = World::new();

        let f16 = Type::float(FloatKind::F16);
        let a_ty = Type::Tensor(TensorType::new(vec![4, 8], f16.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![8, 16], f16.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![4, 16], f16));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source = lower_matmul_to_metal(&world, op).expect("lowering failed");

        assert!(source.contains("device half*"), "expected half pointers");
        assert!(
            source.contains("half acc = 0.0"),
            "expected half accumulator"
        );
        assert!(source.contains("kernel void matmul_4x16_device"));
    }

    #[test]
    fn lower_matmul_f64() {
        let mut world = World::new();

        let f64 = Type::float(FloatKind::F64);
        let a_ty = Type::Tensor(TensorType::new(vec![1, 1], f64.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![1, 1], f64.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![1, 1], f64));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source = lower_matmul_to_metal(&world, op).expect("lowering failed");

        assert!(source.contains("device double*"));
        assert!(source.contains("double acc = 0.0"));
    }

    #[test]
    fn error_wrong_op_name() {
        let mut world = World::new();
        let entity: Entity = world
            .spawn(EntityKind::Node, Some("bad".into()))
            .unwrap()
            .into();
        world.add_component(entity, OpMarker).unwrap();
        world
            .add_component(entity, OpName("arith.addf".into()))
            .unwrap();

        let err = lower_matmul_to_metal(&world, entity).unwrap_err();
        match err {
            MetalLowerError::NotAMatmulOp(msg) => {
                assert!(msg.contains("linalg.matmul"));
            }
            _ => panic!("expected NotAMatmulOp, got {:?}", err),
        }
    }

    #[test]
    fn error_missing_operands() {
        let mut world = World::new();
        let entity: Entity = world
            .spawn(EntityKind::Node, Some("bad".into()))
            .unwrap()
            .into();
        world.add_component(entity, OpMarker).unwrap();
        world
            .add_component(entity, OpName("linalg.matmul".into()))
            .unwrap();
        world.add_component(entity, Operands(vec![])).unwrap();
        world.add_component(entity, Results(vec![])).unwrap();

        let err = lower_matmul_to_metal(&world, entity).unwrap_err();
        match err {
            MetalLowerError::MissingOperand(_) => {}
            _ => panic!("expected MissingOperand, got {:?}", err),
        }
    }

    #[test]
    fn error_non_tensor_operand() {
        let mut world = World::new();

        let scalar = Type::float(FloatKind::F32);
        let a = create_value(&mut world, "A", scalar.clone());
        let b = create_value(&mut world, "B", scalar.clone());
        let c = create_value(&mut world, "C", scalar);

        let op: Entity = world
            .spawn(EntityKind::Node, Some("bad".into()))
            .unwrap()
            .into();
        world.add_component(op, OpMarker).unwrap();
        world
            .add_component(op, OpName("linalg.matmul".into()))
            .unwrap();
        world.add_component(op, Operands(vec![a, b, c])).unwrap();
        world.add_component(op, Results(vec![])).unwrap();

        let err = lower_matmul_to_metal(&world, op).unwrap_err();
        match err {
            MetalLowerError::MissingType(_) => {}
            _ => panic!("expected MissingType, got {:?}", err),
        }
    }

    #[test]
    fn error_dimension_mismatch() {
        let mut world = World::new();

        let f32 = Type::float(FloatKind::F32);
        let a_ty = Type::Tensor(TensorType::new(vec![2, 3], f32.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![4, 5], f32.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 4], f32));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let err = lower_matmul_to_metal(&world, op).unwrap_err();
        match err {
            MetalLowerError::MissingType(_) => {}
            _ => panic!("expected MissingType, got {:?}", err),
        }
    }

    #[test]
    fn lower_to_metal_dispatches_matmul() {
        let mut world = World::new();

        let f32 = Type::float(FloatKind::F32);
        let a_ty = Type::Tensor(TensorType::new(vec![2, 3], f32.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![3, 4], f32.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 4], f32));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source = lower_to_metal(&world, op).expect("dispatch failed");
        assert!(source.contains("kernel void"));
        assert!(source.contains("device float*"));
    }

    #[test]
    fn lower_to_metal_unknown_op() {
        let mut world = World::new();
        let entity: Entity = world
            .spawn(EntityKind::Node, Some("unknown".into()))
            .unwrap()
            .into();
        world.add_component(entity, OpMarker).unwrap();
        world
            .add_component(entity, OpName("unknown.op".into()))
            .unwrap();

        let err = lower_to_metal(&world, entity).unwrap_err();
        match err {
            MetalLowerError::NotAMatmulOp(_) => {}
            _ => panic!("expected NotAMatmulOp, got {:?}", err),
        }
    }
    // ── FormatAssignment tests ──────────────────────────────────────────

    #[test]
    fn lower_matmul_with_ternary_assignment() {
        let mut world = World::new();

        let f16 = Type::float(FloatKind::F16);
        let a_ty = Type::Tensor(TensorType::new(vec![4, 8], f16.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![8, 16], f16.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![4, 16], f16));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let op_operands = world.get_component::<Operands>(op).unwrap();
        let _a = op_operands.0[0];
        let _b = op_operands.0[1];

        // Assign Ternary158 + TernaryGemm to operand B (weights)
        let plan = world
            .spawn(EntityKind::Pipeline, Some("ternary-plan".into()))
            .unwrap();
        let plan_e: Entity = plan.into();
        world.add_component(plan_e, CompilePlan).unwrap();
        world
            .add_component(plan_e, FormatAssignment(TensorFormat::Ternary158))
            .unwrap();
        world.add_component(op, CompilePlanRef(plan_e)).unwrap();

        let source = lower_matmul_to_metal(&world, op).expect("lowering failed");

        // Must contain half-precision accumulator
        assert!(
            source.contains("half"),
            "ternary kernel should use half-precision, got:\n{}",
            source
        );
        assert!(
            source.contains("half acc = 0.0h"),
            "missing half accumulator in:\n{}",
            source
        );
        // Must NOT contain multiplication
        assert!(
            !source.contains("acc *"),
            "ternary kernel should have no multiply instruction, got:\n{}",
            source
        );
        // Must contain ternary-specific logic
        assert!(
            source.contains("a_val > 0"),
            "missing positive value check in ternary kernel"
        );
        assert!(
            source.contains("a_val < 0"),
            "missing negative value check in ternary kernel"
        );
    }

    #[test]
    fn lower_matmul_with_binary_assignment() {
        let mut world = World::new();

        let f16 = Type::float(FloatKind::F16);
        let a_ty = Type::Tensor(TensorType::new(vec![2, 16], f16.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![16, 4], f16.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 4], f16));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let op_operands = world.get_component::<Operands>(op).unwrap();
        let _b = op_operands.0[1];

        // Assign Binary1 + BinaryPopcountGemm to operand B (weights)
        let plan = world
            .spawn(EntityKind::Pipeline, Some("binary-plan".into()))
            .unwrap();
        let plan_e: Entity = plan.into();
        world.add_component(plan_e, CompilePlan).unwrap();
        world
            .add_component(plan_e, FormatAssignment(TensorFormat::Binary1))
            .unwrap();
        world.add_component(op, CompilePlanRef(plan_e)).unwrap();

        let source = lower_matmul_to_metal(&world, op).expect("lowering failed");

        // Must contain popcount in binary kernel
        assert!(
            source.contains("popcount"),
            "binary kernel should use popcount, got:\n{}",
            source
        );
    }

    #[test]
    fn lower_matmul_no_assignment_default_fp16() {
        // Without FormatAssignment, should emit standard FP16 matmul
        let mut world = World::new();

        let f16 = Type::float(FloatKind::F16);
        let a_ty = Type::Tensor(TensorType::new(vec![4, 8], f16.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![8, 16], f16.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![4, 16], f16));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source = lower_matmul_to_metal(&world, op).expect("lowering failed");

        // Must be standard FP16 matmul (fma/multiply, not ternary)
        assert!(source.contains("device half*"), "expected half pointers");
        assert!(
            source.contains("half acc = 0.0"),
            "expected half accumulator"
        );
        assert!(source.contains("* B["), "expected multiply");
        assert!(
            !source.contains("popcount"),
            "standard matmul should not have popcount"
        );
    }

    // ── Batch matmul helpers and tests ────────────────────────────────────

    fn create_batch_value(world: &mut World, label: &str, ty: Type) -> Entity {
        let entity: Entity = world
            .spawn(EntityKind::Node, Some(label.into()))
            .unwrap()
            .into();
        world
            .add_component(entity, ValueDef::op_result(Entity::new(0, 1), 0))
            .unwrap();
        world.add_component(entity, ValueType(ty)).unwrap();
        world.add_component(entity, Uses(vec![])).unwrap();
        entity
    }

    fn create_batch_matmul_op(world: &mut World, a_ty: Type, b_ty: Type, c_ty: Type) -> Entity {
        let a = create_batch_value(world, "A", a_ty.clone());
        let b = create_batch_value(world, "B", b_ty.clone());
        let c = create_batch_value(world, "C", c_ty.clone());
        let _result = create_batch_value(world, "result", c_ty);

        let op: Entity = world
            .spawn(EntityKind::Node, Some("batch_matmul".into()))
            .unwrap()
            .into();
        world.add_component(op, OpMarker).unwrap();
        world
            .add_component(op, OpName("linalg.batch_matmul".into()))
            .unwrap();
        world.add_component(op, Operands(vec![a, b, c])).unwrap();
        world.add_component(op, Results(vec![])).unwrap();
        world.add_component(op, OpAttributes(vec![])).unwrap();
        op
    }

    fn create_ternary_matmul_op(world: &mut World, a_ty: Type, b_ty: Type, c_ty: Type) -> Entity {
        let a = create_batch_value(world, "A", a_ty.clone());
        let b = create_batch_value(world, "B", b_ty.clone());
        let c = create_batch_value(world, "C", c_ty.clone());
        let _result = create_batch_value(world, "result", c_ty);

        let op: Entity = world
            .spawn(EntityKind::Node, Some("ternary_matmul".into()))
            .unwrap()
            .into();
        world.add_component(op, OpMarker).unwrap();
        world
            .add_component(op, OpName("linalg.ternary_matmul".into()))
            .unwrap();
        world.add_component(op, Operands(vec![a, b, c])).unwrap();
        world.add_component(op, Results(vec![])).unwrap();
        world.add_component(op, OpAttributes(vec![])).unwrap();
        op
    }

    #[test]
    fn lower_batch_matmul_f32_2x2x3x4() {
        let mut world = World::new();

        let f32 = Type::float(FloatKind::F32);
        let a_ty = Type::Tensor(TensorType::new(vec![2, 2, 3], f32.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![2, 3, 4], f32.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 2, 4], f32));

        let op = create_batch_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source = lower_batch_matmul_to_metal(&world, op).expect("batch_matmul lowering failed");

        // Verify kernel structure
        assert!(
            source.contains("kernel void"),
            "missing 'kernel void' in:\n{}",
            source
        );
        assert!(
            source.contains("device float*"),
            "missing 'device float*' in:\n{}",
            source
        );

        // Verify "depth" appears in kernel signature (3-D grid)
        assert!(
            source.contains("depth"),
            "missing 'depth' (batch index) in:\n{}",
            source
        );
        assert!(
            source.contains("uint3 gid"),
            "missing uint3 grid id for 3-D dispatch in:\n{}",
            source
        );

        // Verify batch dimension in kernel name
        assert!(
            source.contains("batch_matmul_2x4x2_device"),
            "kernel name should include MxNxBatch dimensions"
        );

        eprintln!("Generated batch Metal source:\n{}", source);
    }

    #[test]
    fn lower_batch_matmul_error_wrong_op_name() {
        let mut world = World::new();
        let entity: Entity = world
            .spawn(EntityKind::Node, Some("bad".into()))
            .unwrap()
            .into();
        world.add_component(entity, OpMarker).unwrap();
        world
            .add_component(entity, OpName("arith.addf".into()))
            .unwrap();

        let err = lower_batch_matmul_to_metal(&world, entity).unwrap_err();
        match err {
            MetalLowerError::NotABatchMatmulOp(msg) => {
                assert!(msg.contains("linalg.batch_matmul"));
            }
            _ => panic!("expected NotABatchMatmulOp, got {:?}", err),
        }
    }

    #[test]
    fn lower_batch_matmul_error_non_3d_tensor() {
        let mut world = World::new();

        let f32 = Type::float(FloatKind::F32);
        let a_ty = Type::Tensor(TensorType::new(vec![2, 3], f32.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![3, 4], f32.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 4], f32));

        let op = create_batch_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let err = lower_batch_matmul_to_metal(&world, op).unwrap_err();
        match err {
            MetalLowerError::MissingType(_) => {}
            _ => panic!("expected MissingType, got {:?}", err),
        }
    }

    #[test]
    fn lower_ternary_matmul_kernel() {
        let mut world = World::new();

        // Ternary158 uses signed 8-bit integer element type
        let i8_elem = Type::Integer(crate::ir_types::IntegerType::new(
            8,
            crate::ir_types::Signedness::Signed,
        ));
        let a_ty = Type::Tensor(TensorType::new(vec![2, 3], i8_elem.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![3, 4], i8_elem.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 4], i8_elem));

        let op = create_ternary_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source =
            lower_ternary_matmul_to_metal(&world, op).expect("ternary_matmul lowering failed");

        // Must contain "half" (half-precision accumulator)
        assert!(
            source.contains("half"),
            "ternary kernel should use half-precision, got:\n{}",
            source
        );
        assert!(
            source.contains("half acc = 0.0h"),
            "missing half accumulator in:\n{}",
            source
        );

        // Must NOT contain multiplication in the inner loop
        assert!(
            !source.contains("acc *"),
            "ternary kernel should have no multiply instruction, got:\n{}",
            source
        );

        // Must contain ternary-specific logic
        assert!(
            source.contains("a_val > 0"),
            "missing positive value check in ternary kernel"
        );
        assert!(
            source.contains("a_val < 0"),
            "missing negative value check in ternary kernel"
        );

        eprintln!("Generated ternary Metal source:\n{}", source);
    }

    #[test]
    fn lower_ternary_matmul_binary_format() {
        let mut world = World::new();

        // Binary1 uses 1-bit unsigned element type
        let u1_elem = Type::Integer(crate::ir_types::IntegerType::new(
            1,
            crate::ir_types::Signedness::Unsigned,
        ));
        let a_ty = Type::Tensor(TensorType::new(vec![2, 16], u1_elem.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![16, 4], u1_elem.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 4], u1_elem));

        let op = create_ternary_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source =
            lower_ternary_matmul_to_metal(&world, op).expect("binary matmul lowering failed");

        // Must contain popcount
        assert!(
            source.contains("popcount"),
            "binary kernel should use popcount, got:\n{}",
            source
        );
        assert!(
            source.contains("kernel void binary_matmul_2x4_device"),
            "kernel name should include MxN dimensions"
        );

        eprintln!("Generated binary Metal source:\n{}", source);
    }

    #[test]
    fn lower_ternary_matmul_error_float_encoding() {
        let mut world = World::new();

        let f32 = Type::float(FloatKind::F32);
        let a_ty = Type::Tensor(TensorType::new(vec![2, 3], f32.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![3, 4], f32.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 4], f32));

        let op = create_ternary_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let err = lower_ternary_matmul_to_metal(&world, op).unwrap_err();
        match err {
            MetalLowerError::UnsupportedEncoding(_) => {}
            _ => panic!("expected UnsupportedEncoding, got {:?}", err),
        }
    }

    #[test]
    fn lower_to_metal_dispatches_batch_matmul() {
        let mut world = World::new();

        let f32 = Type::float(FloatKind::F32);
        let a_ty = Type::Tensor(TensorType::new(vec![2, 2, 3], f32.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![2, 3, 4], f32.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 2, 4], f32));

        let op = create_batch_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source = lower_to_metal(&world, op).expect("dispatch failed");
        assert!(source.contains("kernel void"));
        assert!(source.contains("depth"));
    }

    #[test]
    fn lower_to_metal_dispatches_ternary_matmul() {
        let mut world = World::new();

        let i8_elem = Type::Integer(crate::ir_types::IntegerType::new(
            8,
            crate::ir_types::Signedness::Signed,
        ));
        let a_ty = Type::Tensor(TensorType::new(vec![2, 3], i8_elem.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![3, 4], i8_elem.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 4], i8_elem));

        let op = create_ternary_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source = lower_to_metal(&world, op).expect("dispatch failed");
        assert!(source.contains("kernel void"));
        assert!(source.contains("half"));
    }

    #[test]
    fn metal_format_constant() {
        assert_eq!(METAL_FORMAT, HalFormat::Metal);
    }
}
