//! C code generation for ECS-native IR operations.
//!
//! Lowers high-level IR operations (e.g., `linalg.matmul`) into C source
//! strings with simple loop nests suitable for compilation with any C compiler.
//!
//! The generated code uses triple-nested for-loops for the matrix multiply.

use prism_ecs_core::{Entity, World};

use crate::ir_types::{FloatKind, TensorType, Type};
use crate::op::{op_name, operands};
use crate::value::ValueType;

/// Error type for CPU lowering failures.
#[derive(Debug)]
pub enum CpuLowerError {
    /// The operation is not one that can be lowered to CPU C code.
    UnsupportedOp(String),
    /// A required operand or result is missing.
    MissingOperand(String),
    /// An operand or result is missing a type annotation.
    MissingType(String),
}

// ── Element type mapping ─────────────────────────────────────────────────────

/// Map an IR element type to its C scalar type name.
fn element_type_to_c(ty: &Type) -> &'static str {
    match ty {
        Type::Float(ft) => match ft.kind {
            FloatKind::F16 => "float", // C promotes half to float
            FloatKind::F32 => "float",
            FloatKind::F64 => "double",
            FloatKind::BF16 => "float", // C promotes bfloat to float
            FloatKind::F8E4M3 | FloatKind::F8E5M2 => "float", // fallback
        },
        Type::Integer(int_ty) if int_ty.width <= 8 => "char",
        Type::Integer(int_ty) if int_ty.width <= 16 => "short",
        Type::Integer(int_ty) if int_ty.width <= 32 => "int",
        Type::Integer(_) => "long",
        _ => "float",
    }
}

/// Extract a `TensorType` from a value entity's `ValueType` component.
fn require_tensor(world: &World, entity: Entity, label: &str) -> Result<TensorType, CpuLowerError> {
    let vt = world
        .get_component::<ValueType>(entity)
        .map(|v| v.0.clone())
        .ok_or_else(|| CpuLowerError::MissingType(format!("{} has no ValueType", label)))?;

    match vt {
        Type::Tensor(t) => Ok(t),
        _ => Err(CpuLowerError::MissingType(format!(
            "{} is not a tensor type",
            label
        ))),
    }
}

#[rustfmt::skip]
fn emit_matmul_c_function(
    m: u64, n: u64, k: u64,
    c_type: &str,
) -> String {
    format!(
        r#"// Auto-generated by prism-ecs-ir codegen_cpu

void matmul_{m}x{k}x{n}(
    {t}* A, {t}* B, {t}* C,
    int M, int N, int K)
{{
    for (int i = 0; i < M; i++) {{
        for (int j = 0; j < N; j++) {{
            {t} acc = 0;
            for (int k = 0; k < K; k++) {{
                acc += A[i * K + k] * B[k * N + j];
            }}
            C[i * N + j] = acc;
        }}
    }}
}}
"#,
        m = m, n = n, k = k, t = c_type,
    )
}

// ── Public API ───────────────────────────────────────────────────────────────

/// Lower a `linalg.matmul` to a C function.
///
/// Given a `linalg.matmul` op consuming operands `A`, `B`, `C` where the
/// semantics are `C += A @ B`, this function emits C source code implementing
/// the matrix multiplication as a triple-nested for-loop — one loop per output
/// element `C[i][j]`.
///
/// Each operand **must** carry a `tensor<...>` type with a 2-D shape so that
/// the dimensions `M`, `K`, `N` can be extracted for the signature.
pub fn lower_matmul_to_cpu(world: &World, matmul_op: Entity) -> Result<String, CpuLowerError> {
    // 1. Verify the op is a matmul
    let name = op_name(world, matmul_op).unwrap_or_default();
    if name != "linalg.matmul" {
        return Err(CpuLowerError::UnsupportedOp(format!(
            "expected 'linalg.matmul', got '{}'",
            name
        )));
    }

    // 2. Read operands
    let op_operands = operands(world, matmul_op);
    if op_operands.len() < 3 {
        return Err(CpuLowerError::MissingOperand(format!(
            "matmul requires 3 operands (A, B, C), got {}",
            op_operands.len()
        )));
    }

    let a = op_operands[0];
    let b = op_operands[1];
    let c = op_operands[2];

    // 3. Extract tensor shapes
    let a_tensor = require_tensor(world, a, "operand A")?;
    let b_tensor = require_tensor(world, b, "operand B")?;
    let c_tensor = require_tensor(world, c, "operand C")?;

    // 4. Validate shapes: A[M,K] x B[K,N] = C[M,N]
    let shape_ok =
        a_tensor.shape.len() == 2 && b_tensor.shape.len() == 2 && c_tensor.shape.len() == 2;

    if !shape_ok {
        return Err(CpuLowerError::MissingType(
            "all matmul operands must be 2-D tensors".into(),
        ));
    }

    let m = a_tensor.shape[0];
    let k_a = a_tensor.shape[1];
    let k_b = b_tensor.shape[0];
    let n = b_tensor.shape[1];
    let c_m = c_tensor.shape[0];
    let c_n = c_tensor.shape[1];

    if k_a != k_b {
        return Err(CpuLowerError::MissingType(format!(
            "matmul dimension mismatch: A[1] = {k_a} ≠ B[0] = {k_b}"
        )));
    }
    if m != c_m || n != c_n {
        return Err(CpuLowerError::MissingType(format!(
            "matmul result shape mismatch: expected [{m}, {n}], got [{c_m}, {c_n}]"
        )));
    }

    // 5. Emit C source
    let c_type = element_type_to_c(&a_tensor.element_type);
    Ok(emit_matmul_c_function(m, n, k_a, c_type))
}

/// Lower any supported root IR operation to C source.
///
/// Dispatches to the appropriate lowering function based on the operation name.
pub fn lower_to_cpu(world: &World, root_op: Entity) -> Result<String, CpuLowerError> {
    match op_name(world, root_op).as_deref() {
        Some("linalg.matmul") => lower_matmul_to_cpu(world, root_op),
        Some(name) => Err(CpuLowerError::UnsupportedOp(format!(
            "no CPU lowering available for '{name}'"
        ))),
        None => Err(CpuLowerError::UnsupportedOp("operation has no name".into())),
    }
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use prism_ecs_core::{EntityKind, World};

    use super::*;
    use crate::ir_types::{FloatKind, TensorType, Type};
    use crate::op::{OpAttributes, OpMarker, OpName, Operands, Results};
    use crate::value::{Uses, ValueDef, ValueType};

    // ── Helpers ──────────────────────────────────────────────────────────

    fn create_value(world: &mut World, label: &str, ty: Type) -> Entity {
        let entity: Entity = world
            .spawn(EntityKind::Node, Some(label.into()))
            .unwrap()
            .into();
        world
            .add_component(entity, ValueDef::op_result(Entity::new(0, 1), 0))
            .unwrap();
        world.add_component(entity, ValueType(ty)).unwrap();
        world.add_component(entity, Uses(vec![])).unwrap();
        entity
    }

    fn create_matmul_op(world: &mut World, a_ty: Type, b_ty: Type, c_ty: Type) -> Entity {
        let a = create_value(world, "A", a_ty.clone());
        let b = create_value(world, "B", b_ty.clone());
        let c = create_value(world, "C", c_ty.clone());
        let _result = create_value(world, "result", c_ty);

        let op: Entity = world
            .spawn(EntityKind::Node, Some("matmul".into()))
            .unwrap()
            .into();
        world.add_component(op, OpMarker).unwrap();
        world
            .add_component(op, OpName("linalg.matmul".into()))
            .unwrap();
        world.add_component(op, Operands(vec![a, b, c])).unwrap();
        world.add_component(op, Results(vec![])).unwrap();
        world.add_component(op, OpAttributes(vec![])).unwrap();
        op
    }

    // ── Tests ────────────────────────────────────────────────────────────

    #[test]
    fn lower_matmul_f32_2x3x4() {
        let mut world = World::new();

        let f32 = Type::float(FloatKind::F32);
        let a_ty = Type::Tensor(TensorType::new(vec![2, 3], f32.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![3, 4], f32.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 4], f32));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source = lower_matmul_to_cpu(&world, op).expect("lowering failed");

        // Verify key structural elements
        assert!(source.contains("void"), "missing 'void' in:\n{}", source);
        assert!(source.contains("for ("), "missing 'for (' in:\n{}", source);
        assert!(source.contains("*"), "missing '*' in:\n{}", source);

        // Verify dimension-specific content
        assert!(
            source.contains("matmul_2x3x4"),
            "function name should include MxKxN dimensions in:\n{}",
            source
        );
        assert!(
            source.contains("float* A"),
            "missing float* A argument in:\n{}",
            source
        );
        assert!(
            source.contains("float* B"),
            "missing float* B argument in:\n{}",
            source
        );
        assert!(
            source.contains("float* C"),
            "missing float* C argument in:\n{}",
            source
        );

        eprintln!("Generated C source:\n{}", source);
    }

    #[test]
    fn lower_matmul_f64() {
        let mut world = World::new();

        let f64 = Type::float(FloatKind::F64);
        let a_ty = Type::Tensor(TensorType::new(vec![1, 1], f64.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![1, 1], f64.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![1, 1], f64));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source = lower_matmul_to_cpu(&world, op).expect("lowering failed");

        assert!(source.contains("double*"), "expected double pointers");
        assert!(
            source.contains("double acc = 0"),
            "expected double accumulator"
        );
        assert!(source.contains("matmul_1x1x1"));
    }

    #[test]
    fn error_wrong_op_name() {
        let mut world = World::new();
        let entity: Entity = world
            .spawn(EntityKind::Node, Some("bad".into()))
            .unwrap()
            .into();
        world.add_component(entity, OpMarker).unwrap();
        world
            .add_component(entity, OpName("arith.addf".into()))
            .unwrap();

        let err = lower_matmul_to_cpu(&world, entity).unwrap_err();
        match err {
            CpuLowerError::UnsupportedOp(msg) => {
                assert!(msg.contains("linalg.matmul"));
            }
            _ => panic!("expected UnsupportedOp, got {:?}", err),
        }
    }

    #[test]
    fn error_missing_operands() {
        let mut world = World::new();
        let entity: Entity = world
            .spawn(EntityKind::Node, Some("bad".into()))
            .unwrap()
            .into();
        world.add_component(entity, OpMarker).unwrap();
        world
            .add_component(entity, OpName("linalg.matmul".into()))
            .unwrap();
        world.add_component(entity, Operands(vec![])).unwrap();
        world.add_component(entity, Results(vec![])).unwrap();

        let err = lower_matmul_to_cpu(&world, entity).unwrap_err();
        match err {
            CpuLowerError::MissingOperand(_) => {}
            _ => panic!("expected MissingOperand, got {:?}", err),
        }
    }

    #[test]
    fn error_non_tensor_operand() {
        let mut world = World::new();

        let scalar = Type::float(FloatKind::F32);
        let a = create_value(&mut world, "A", scalar.clone());
        let b = create_value(&mut world, "B", scalar.clone());
        let c = create_value(&mut world, "C", scalar);

        let op: Entity = world
            .spawn(EntityKind::Node, Some("bad".into()))
            .unwrap()
            .into();
        world.add_component(op, OpMarker).unwrap();
        world
            .add_component(op, OpName("linalg.matmul".into()))
            .unwrap();
        world.add_component(op, Operands(vec![a, b, c])).unwrap();
        world.add_component(op, Results(vec![])).unwrap();

        let err = lower_matmul_to_cpu(&world, op).unwrap_err();
        match err {
            CpuLowerError::MissingType(_) => {}
            _ => panic!("expected MissingType, got {:?}", err),
        }
    }

    #[test]
    fn error_dimension_mismatch() {
        let mut world = World::new();

        let f32 = Type::float(FloatKind::F32);
        let a_ty = Type::Tensor(TensorType::new(vec![2, 3], f32.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![4, 5], f32.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 4], f32));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let err = lower_matmul_to_cpu(&world, op).unwrap_err();
        match err {
            CpuLowerError::MissingType(_) => {}
            _ => panic!("expected MissingType, got {:?}", err),
        }
    }

    #[test]
    fn lower_to_cpu_dispatches_matmul() {
        let mut world = World::new();

        let f32 = Type::float(FloatKind::F32);
        let a_ty = Type::Tensor(TensorType::new(vec![2, 3], f32.clone()));
        let b_ty = Type::Tensor(TensorType::new(vec![3, 4], f32.clone()));
        let c_ty = Type::Tensor(TensorType::new(vec![2, 4], f32));

        let op = create_matmul_op(&mut world, a_ty, b_ty, c_ty);
        let source = lower_to_cpu(&world, op).expect("dispatch failed");
        assert!(source.contains("void"));
        assert!(source.contains("float*"));
        assert!(source.contains("for ("));
    }

    #[test]
    fn lower_to_cpu_unknown_op() {
        let mut world = World::new();
        let entity: Entity = world
            .spawn(EntityKind::Node, Some("unknown".into()))
            .unwrap()
            .into();
        world.add_component(entity, OpMarker).unwrap();
        world
            .add_component(entity, OpName("unknown.op".into()))
            .unwrap();

        let err = lower_to_cpu(&world, entity).unwrap_err();
        match err {
            CpuLowerError::UnsupportedOp(_) => {}
            _ => panic!("expected UnsupportedOp, got {:?}", err),
        }
    }
}
