pub mod conv3d;
pub mod frame_scheduler;
pub mod temporal_attention;
pub mod vae_3d;

pub mod types {
    #[derive(Debug, Clone, Copy)]
    pub enum VideoCodec {
        H264,
    }
}

pub use frame_scheduler::FrameIndex;

/// New operation kinds for video generation
#[derive(Debug, Clone)]
pub enum VideoOp {
    // 3D convolution (spatial + temporal)
    Conv3d {
        in_ch: u32,
        out_ch: u32,
        kernel: (u32, u32, u32), // (temporal, height, width)
        stride: (u32, u32, u32),
        padding: (u32, u32, u32),
    },

    // Temporal attention (across frames at same spatial position)
    TemporalAttention {
        dim: u32,
        heads: u32,
        causal: bool,
    },

    // Joint spatial-temporal attention (full 3D self-attention)
    SpatialTemporalAttention {
        dim: u32,
        heads: u32,
    },

    // Frame interpolation
    FrameInterpolation {
        scale: u32,
    },

    // 3D VAE decode (video latent → video frames)
    VideoVaeDecode {
        latent_channels: u32,
        num_frames: u32,
    },

    // Frame-wise schedule for long video generation
    FrameSchedule {
        keyframe_interval: u32,   // generate keyframe every N frames
        interpolation_steps: u32, // interpolate between keyframes
    },
}

#[derive(Debug, Clone)]
pub struct VideoPipeline {
    /// Total frames to generate
    pub num_frames: u32,
    /// Frames processed per denoising step (sliding window)
    pub window_size: u32, // typically 4-8 frames
    /// Overlap between windows (for temporal consistency)
    pub overlap: u32, // typically 1-2 frames
    /// Generated keyframes (every keyframe_interval frames)
    pub keyframes: Vec<FrameIndex>,
    /// Interpolation between keyframes
    pub interpolate: bool,
}

/// A gap between two keyframes that must be filled via interpolation.
#[derive(Debug, Clone)]
pub struct InterpolationGap {
    /// Index of the keyframe that starts this gap.
    pub start_frame: u32,
    /// Index of the keyframe that ends this gap.
    pub end_frame: u32,
    /// How many interpolated frames to insert between start and end.
    pub num_interpolations: u32,
}

/// Describes a complete frame schedule for video generation:
/// which frames are keyframes (generated by the image provider)
/// and which gaps are filled by interpolation.
#[derive(Debug, Clone)]
pub struct FrameSchedule {
    /// The list of keyframe indices in temporal order.
    pub keyframes: Vec<FrameIndex>,
    /// Gaps between consecutive keyframes that need interpolation.
    pub interpolation_gaps: Vec<InterpolationGap>,
    /// Keyframe interval used to derive the schedule.
    pub keyframe_interval: u32,
    /// Interpolation steps between keyframes.
    pub interpolation_steps: u32,
}

impl FrameSchedule {
    /// Build a frame schedule for `num_frames` frames, placing a keyframe
    /// every `keyframe_interval` frames and setting `interpolation_steps`
    /// as the number of interpolated frames between consecutive keyframes.
    pub fn new(num_frames: u32, _fps: u32, keyframe_interval: u32) -> Self {
        let scheduler = frame_scheduler::FrameScheduler::new(
            num_frames,
            keyframe_interval,
            1, // interpolation_steps handled separately
        );
        let raw_keyframes = scheduler.schedule_keyframes();

        let mut keyframes: Vec<FrameIndex> = raw_keyframes;
        keyframes.sort();
        keyframes.dedup();

        let mut interpolation_gaps = Vec::new();
        // Cap interpolation so we never exceed num_frames
        let safe_interpolation_steps = keyframe_interval.saturating_sub(1).min(4);

        for window in keyframes.windows(2) {
            let start = window[0];
            let end = window[1];
            let range = end - start;
            if range > 1 {
                let steps = safe_interpolation_steps.min(range - 1);
                if steps > 0 {
                    interpolation_gaps.push(InterpolationGap {
                        start_frame: start,
                        end_frame: end,
                        num_interpolations: steps,
                    });
                }
            }
        }

        Self {
            keyframes,
            interpolation_gaps,
            keyframe_interval,
            interpolation_steps: safe_interpolation_steps,
        }
    }
}

#[derive(Debug, Clone)]
pub struct VideoGenPipeline {
    pub pipeline: VideoPipeline,
}

// ── Prism Video facade ───────────────────────────────────────────────────

/// Parameters for text-to-video generation.
#[derive(Clone, Debug)]
pub struct VideoParams {
    /// Number of frames to generate.
    pub num_frames: u32,
    /// Target frame rate (for metadata / downstream encoding).
    pub fps: u32,
    /// Base seed for deterministic frame sequences.
    pub seed: u64,
}

/// Receipt for a completed video-generation request.
#[derive(Debug)]
pub struct VideoGenerationReceipt {
    /// Generated frames in temporal order.
    /// Each entry is `(width, height, flat RGBA8888 pixel data)`.
    pub frames: Vec<(u32, u32, Vec<u8>)>,
    /// Wall-clock compute time in milliseconds.
    pub compute_ms: f64,
}

/// Errors that can occur during video generation.
#[derive(Debug, thiserror::Error)]
pub enum PrismVideoError {
    #[error("video generation feature not enabled (add generation-video feature)")]
    MissingFeature,
    #[error("model not found at {0}")]
    ModelNotFound(String),
    #[error("generation failed: {0}")]
    GenerationFailed(String),
    #[error("frame sizes do not match for blending")]
    FrameSizeMismatch,
}

/// Blend two RGBA8888 frames linearly by factor `t`.
///
/// `t = 0.0` returns `a` unchanged; `t = 1.0` returns `b` unchanged.
fn blend_frames(a: &[u8], b: &[u8], t: f32) -> Result<Vec<u8>, PrismVideoError> {
    if a.len() != b.len() {
        return Err(PrismVideoError::FrameSizeMismatch);
    }
    Ok(a.iter()
        .zip(b.iter())
        .map(|(x, y)| (*x as f32 * (1.0 - t) + *y as f32 * t) as u8)
        .collect())
}

/// Generate a video from a text prompt.
///
/// This is the main entry point for text-to-video generation.
///
/// When the `generation-video` feature is enabled, delegates to the
/// compute-core [`VideoGenerationProvider`]. Otherwise a fast CPU-based
/// pipeline is used that calls `image_provider` for each keyframe and
/// fills the remaining frames via linear interpolation.
pub fn generate_video(
    model_path: &str,
    prompt: &str,
    params: VideoParams,
    image_provider: &dyn Fn(&str, u32, u32) -> Result<Vec<u8>, String>,
) -> Result<VideoGenerationReceipt, PrismVideoError> {
    #[cfg(feature = "generation-video")]
    {
        return generate_via_compute_core(model_path, prompt, params);
    }

    #[cfg(not(feature = "generation-video"))]
    {
        let _ = model_path;
        generate_video_impl(prompt, params, image_provider)
    }
}

/// Fallback implementation: generate keyframes via the image provider,
/// then fill gaps with linear interpolation.
#[cfg(not(feature = "generation-video"))]
fn generate_video_impl(
    prompt: &str,
    params: VideoParams,
    image_provider: &dyn Fn(&str, u32, u32) -> Result<Vec<u8>, String>,
) -> Result<VideoGenerationReceipt, PrismVideoError> {
    let num_frames = params.num_frames.max(1);
    let schedule = FrameSchedule::new(num_frames, params.fps, 8);

    // Fixed frame size for image generation
    let width = 512u32;
    let height = 512u32;

    // Accumulate all frames in a temporary Vec<(frame_index, data)>
    // then convert to the receipt format at the end.
    let mut indexed_frames: Vec<(u32, Vec<u8>)> = Vec::with_capacity(num_frames as usize);

    // Generate keyframes via image provider
    for &keyframe_idx in &schedule.keyframes {
        let img = image_provider(prompt, width, height)
            .map_err(|e| PrismVideoError::GenerationFailed(e))?;
        indexed_frames.push((keyframe_idx, img));
    }

    // Sort by frame index so subsequent interpolation lookups are correct
    indexed_frames.sort_by_key(|(idx, _)| *idx);

    // Interpolate between keyframes — clone keyframe data out to avoid
    // borrowing `indexed_frames` mutably while holding references into it
    for gap in &schedule.interpolation_gaps {
        let start_buf = indexed_frames
            .iter()
            .find(|(i, _)| *i == gap.start_frame)
            .map(|(_, d)| d.clone());
        let end_buf = indexed_frames
            .iter()
            .find(|(i, _)| *i == gap.end_frame)
            .map(|(_, d)| d.clone());

        if let (Some(start_data), Some(end_data)) = (start_buf, end_buf) {
            for step in 1..=gap.num_interpolations {
                let t = step as f32 / (gap.num_interpolations + 1) as f32;
                let blended = blend_frames(&start_data, &end_data, t)?;
                indexed_frames.push((gap.start_frame + step, blended));
            }
        }
    }

    // Final sort by frame index
    indexed_frames.sort_by_key(|(idx, _)| *idx);

    // Convert to receipt format (width, height, data)
    let frames: Vec<(u32, u32, Vec<u8>)> = indexed_frames
        .into_iter()
        .map(|(_, data)| (width, height, data))
        .collect();

    Ok(VideoGenerationReceipt {
        frames,
        compute_ms: 0.0,
    })
}

/// Delegate to the compute-core [`VideoGenerationProvider`].
///
/// Only compiled when the `generation-video` feature is enabled.
#[cfg(feature = "generation-video")]
fn generate_via_compute_core(
    model_path: &str,
    prompt: &str,
    params: VideoParams,
) -> Result<VideoGenerationReceipt, PrismVideoError> {
    use tribunus_compute_core::video_provider::{
        VideoGenerationProvider as _, VideoGenerationRequest, VideoProvider,
    };

    let provider = VideoProvider::new(model_path)
        .map_err(|e| PrismVideoError::ModelNotFound(e.to_string()))?;

    let request = VideoGenerationRequest {
        model_path: model_path.to_string(),
        prompt: prompt.to_string(),
        num_frames: params.num_frames,
        fps: params.fps,
        seed: params.seed,
    };

    let result = provider
        .generate_text_to_video(request)
        .map_err(|e| PrismVideoError::GenerationFailed(e.to_string()))?;

    Ok(VideoGenerationReceipt {
        frames: result.frames,
        compute_ms: result.compute_ms,
    })
}
