//! Post-emission diagnostics for the CImage pipeline.
//!
//! This module owns the canonical authority for the post-emission
//! diagnostic report and the layer / global diagnostic records. The
//! diagnostic report is the *primary operator-facing view* of a
//! finalized CImage: it lists the per-layer outcomes, the per-global
//! outcomes, the [`DiagnosticIssue`]s that the post-emission reader
//! identified, and the overall pass / fail verdict.
//!
//! Diagnostics are *projection data*: they are derived from the manifest
//! and the receipt, and can be regenerated by re-running
//! [`run_diagnostics`] over the same CImage directory. They are not
//! authoritative; the manifest and receipt are. A change to a
//! diagnostic field is a non-constitutional change as long as the
//! underlying manifest / receipt schema is unchanged.

use std::fs;
use std::path::Path;

use serde::{Deserialize, Serialize};

use super::CImagePipelineError;
use super::CImagePipelineResult;

/// Top-level diagnostic report for a finalized CImage.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DiagnosticReport {
    /// Image directory path that was diagnosed.
    pub image_dir: String,
    /// Per-layer diagnostic records (BTreeMap for stable iteration).
    pub layers: std::collections::BTreeMap<u32, LayerDiagnostic>,
    /// Per-global (persistent) diagnostic records.
    pub globals: Vec<GlobalDiagnostic>,
    /// Identified issues (ordered by severity).
    pub issues: Vec<DiagnosticIssue>,
    /// Overall pass / fail verdict.
    pub overall_pass: bool,
}

/// Per-layer diagnostic record.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LayerDiagnostic {
    /// Layer index.
    pub index: u32,
    /// Layer segment name (e.g. `target_layer_3`).
    pub segment_name: String,
    /// Number of tensors in the layer segment.
    pub tensor_count: u32,
    /// Total bytes in the layer segment.
    pub byte_size: u64,
    /// Issues identified for the layer, if any.
    pub issues: Vec<DiagnosticIssue>,
}

/// Per-global (persistent) diagnostic record.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GlobalDiagnostic {
    /// Global segment name.
    pub segment_name: String,
    /// Number of tensors in the global segment.
    pub tensor_count: u32,
    /// Total bytes in the global segment.
    pub byte_size: u64,
    /// Issues identified for the global segment, if any.
    pub issues: Vec<DiagnosticIssue>,
}

/// Diagnostic issue severity.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DiagnosticSeverity {
    /// Informational finding.
    Info,
    /// Warning that does not fail the overall verdict.
    Warning,
    /// Error that fails the overall verdict.
    Error,
}

/// Diagnostic issue.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DiagnosticIssue {
    /// Issue severity.
    pub severity: DiagnosticSeverity,
    /// Stable issue code (e.g. `MANIFEST_MISSING`).
    pub code: String,
    /// Human-readable description.
    pub message: String,
}

impl DiagnosticIssue {
    /// Construct an error issue.
    pub fn error(code: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            severity: DiagnosticSeverity::Error,
            code: code.into(),
            message: message.into(),
        }
    }

    /// Construct a warning issue.
    pub fn warning(code: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            severity: DiagnosticSeverity::Warning,
            code: code.into(),
            message: message.into(),
        }
    }
}

/// Verify a finalized CImage directory and return a
/// [`DiagnosticReport`].
pub fn verify(image_dir: &str) -> CImagePipelineResult<DiagnosticReport> {
    run_diagnostics(Path::new(image_dir))
}

/// Run post-emission diagnostics on a finalized CImage directory.
pub fn run_diagnostics(image_dir: &Path) -> CImagePipelineResult<DiagnosticReport> {
    let mut report = DiagnosticReport {
        image_dir: image_dir.display().to_string(),
        layers: std::collections::BTreeMap::new(),
        globals: Vec::new(),
        issues: Vec::new(),
        overall_pass: true,
    };

    let manifest_path = image_dir.join("manifest.json");
    if !manifest_path.exists() {
        report.issues.push(DiagnosticIssue::error(
            "MANIFEST_MISSING",
            "manifest.json is missing from the CImage directory",
        ));
        report.overall_pass = false;
        return Ok(report);
    }

    let manifest_text = fs::read_to_string(&manifest_path).map_err(|e| {
        CImagePipelineError::failed(format!("read manifest: {e}"))
    })?;
    let manifest: serde_json::Value = serde_json::from_str(&manifest_text).map_err(|e| {
        CImagePipelineError::failed(format!("parse manifest: {e}"))
    })?;

    if let Some(segments) = manifest.get("segments").and_then(|v| v.as_array()) {
        for segment in segments {
            let kind = segment
                .get("kind")
                .and_then(|v| v.as_str())
                .unwrap_or("");
            let name = segment
                .get("name")
                .and_then(|v| v.as_str())
                .unwrap_or("");
            let byte_size = segment
                .get("byte_size")
                .and_then(|v| v.as_u64())
                .unwrap_or(0);
            let tensor_count = segment
                .get("tensor_count")
                .and_then(|v| v.as_u64())
                .unwrap_or(0) as u32;

            if let Some(layer_idx) = name
                .strip_prefix("target_layer_")
                .and_then(|s| s.parse::<u32>().ok())
            {
                let diag = LayerDiagnostic {
                    index: layer_idx,
                    segment_name: name.to_string(),
                    tensor_count,
                    byte_size,
                    issues: Vec::new(),
                };
                report.layers.insert(layer_idx, diag);
            } else {
                report.globals.push(GlobalDiagnostic {
                    segment_name: name.to_string(),
                    tensor_count,
                    byte_size,
                    issues: Vec::new(),
                });
            }
            if byte_size == 0 && !kind.is_empty() {
                let issue = DiagnosticIssue::warning(
                    "EMPTY_SEGMENT",
                    format!("segment {name} ({kind}) has zero bytes"),
                );
                report.issues.push(issue.clone());
            }
        }
    }

    if let Some(receipt_path) = Some(image_dir.join("receipt.json")) {
        if !receipt_path.exists() {
            report.issues.push(DiagnosticIssue::warning(
                "RECEIPT_MISSING",
                "receipt.json is missing from the CImage directory",
            ));
        }
    }

    Ok(report)
}
