//! MIL program generation for ANE KV cache decompression and sliding window attention.
//! Also provides AneCompressor — a manager that loads and runs ANE compression/decompression programs.
//!
//! The ANE decompresses TurboQuant-compressed KV cache pages from the IOSurface
//! island while the GPU computes attention, hiding the decompression latency.
//!
//! Decompression pipeline per page:
//!   1. Read packed bits from IOSurface input
//!   2. Dequantize: packed bits -> FP16 values (polar dequant with scale)
//!   3. Apply QJL correction: add/subtract residual magnitude
//!   4. Apply inverse Hadamard transform (Hadamard is self-inverse)
//!   5. Write FP16 output to IOSurface

use crate::coreml_bridge::{CoreMlComputeUnits, CoreMlModel};
use crate::arena::Arena;

/// Generate MIL program text for KV cache decompression.
///
/// The program reads a compressed KV page from `compressed_input` IOSurface,
/// decompresses it through an element-wise MIL graph, and writes FP16 values
/// to `decompressed_output` IOSurface.
///
/// `head_dim`: dimension per KV head (e.g. 120 for Gemma4, 64 for Qwen)
/// `n_kv_heads`: number of KV heads
/// `bits`: quantization bits per value (3-4)
pub fn generate_kv_decompress_mil(head_dim: u32, n_kv_heads: u32, bits: u32) -> String {
    let mut mil = String::new();

    // Prologue: auto-generated header with parameters
    mil.push_str("# Generated by Tribunus ANE KV Decompression\n");
    mil.push_str("# head_dim: ");
    mil.push_str(&head_dim.to_string());
    mil.push_str(" n_kv_heads: ");
    mil.push_str(&n_kv_heads.to_string());
    mil.push_str(" bits: ");
    mil.push_str(&bits.to_string());
    mil.push_str("\n\n");

    // Input: packed bytes from IOSurface
    mil.push_str(&format!(
        "input @ {name} (float16, {size}) read write\n",
        name = "compressed_input",
        size = (head_dim * n_kv_heads * bits as u32 / 16).max(64),
    ));

    // Output: decompressed FP16 to IOSurface
    mil.push_str(&format!(
        "output @ {name} (float16, {size}) read write\n\n",
        name = "decompressed_output",
        size = head_dim * n_kv_heads,
    ));

    // Dequantize: unpack bits and apply scale (mode: "polar" for TurboQuant polar dequant)
    mil.push_str(&format!(
        "layer dequant {{\n  type: dequantize\n  input: \"compressed_input\"\n  output: \"unpacked\"\n  mode: \"polar\"\n  bits: {}\n}}\n",
        bits,
    ));

    // Apply QJL correction (element-wise additive residual)
    mil.push_str(
        "layer qjl_correct {\n  type: add\n  input: \"unpacked\"\n  output: \"corrected\"\n}\n",
    );

    // Inverse Hadamard transform (Hadamard is self-inverse, same operation)
    mil.push_str(
        "layer inv_hadamard {\n  type: hadamard_transform\n  input: \"corrected\"\n  output: \"decompressed_output\"\n}\n",
    );

    mil
}

/// Generate MIL program text for sliding window attention.
///
/// Runs the attention computation for a sliding window layer on ANE:
///   1. Read Q, K, V from IOSurface
///   2. Compute Q @ K^T (sliding window mask)
///   3. Softmax
///   4. Output @ V
///   5. Write attention output to IOSurface
pub fn generate_attention_mil(
    n_heads: u32,
    n_kv_heads: u32,
    head_dim: u32,
    window: u32,
) -> String {
    let mut mil = String::new();
    mil.push_str("// Tribunus ANE Sliding Window Attention\n");
    mil.push_str(&format!(
        "// n_heads: {} n_kv_heads: {} head_dim: {} window: {}\n\n",
        n_heads, n_kv_heads, head_dim, window,
    ));

    // Inputs
    let q_size = n_heads * head_dim;
    let kv_size = n_kv_heads * head_dim;
    let seq_len = window;

    mil.push_str(&format!(
        "input @ \"query\" (float16, {}) read write\n",
        q_size,
    ));
    mil.push_str(&format!(
        "input @ \"key\" (float16, {}) read write\n",
        kv_size,
    ));
    mil.push_str(&format!(
        "input @ \"value\" (float16, {}) read write\n",
        kv_size,
    ));

    // Output
    mil.push_str(&format!(
        "output @ \"attention_output\" (float16, {}) read write\n\n",
        q_size,
    ));

    // Q @ K^T
    mil.push_str(&format!(
        "layer qk_matmul {{\n  type: batched_matmul\n  input: \"query\", \"key\"\n  output: \"scores\"\n  transpose_b: true\n}}\n",
    ));

    // Sliding window mask (element-wise)
    mil.push_str(&format!(
        "layer window_mask {{\n  type: add\n  input: \"scores\"\n  output: \"masked_scores\"\n}}\n",
    ));

    // Softmax
    mil.push_str(
        "layer softmax {\n  type: softmax\n  input: \"masked_scores\"\n  output: \"probs\"\n  axis: -1\n}\n",
    );

    // Attention output = probs @ V
    mil.push_str(
        "layer attn_matmul {\n  type: batched_matmul\n  input: \"probs\", \"value\"\n  output: \"attention_output\"\n}\n",
    );

    mil
}

/// Generate MIL program for L3 tier 2-bit compression (FP16 → 2-bit packed).
///
/// The program reads FP16 values from `value_input`, quantizes them to 2-bit
/// using polar quantization with learned scale, and writes packed bytes to
/// `packed_output`. This is the cold-storage path: L3 DRAM heap holds 2-bit
/// compressed pages that are rare to access.
///
/// `head_dim`: dimension per KV head (e.g. 120 for Gemma4, 64 for Qwen)
/// `n_kv_heads`: number of KV heads
pub fn generate_l3_compress_mil(head_dim: u32, n_kv_heads: u32) -> String {
    let mut mil = String::new();
    let bits: u32 = 2;

    mil.push_str("# Generated by Tribunus ANE L3 2-bit Compression\n");
    mil.push_str(&format!(
        "# head_dim: {} n_kv_heads: {} bits: {}\n\n",
        head_dim, n_kv_heads, bits,
    ));

    // Input: FP16 values from the decompressed page.
    let input_size = head_dim * n_kv_heads;
    mil.push_str(&format!(
        "input @ \"input\" (float16, {}) read write\n",
        input_size,
    ));

    // Output: packed 2-bit bytes (minimum 64 for ANE pipeline alignment).
    let packed_size = (head_dim * n_kv_heads * bits / 16).max(64);
    mil.push_str(&format!(
        "output @ \"output\" (float16, {}) read write\n\n",
        packed_size,
    ));

    // Quantize: FP16 → 2-bit packed bits using polar quantization.
    mil.push_str(&format!(
        "layer quantize {{\n  type: quantize\n  input: \"input\"\n  output: \"output\"\n  mode: \"polar\"\n  bits: {}\n}}\n",
        bits,
    ));

    mil
}

/// Generate MIL program for L3 tier 2-bit decompression (2-bit packed → FP16).
///
/// The program reads 2-bit packed bytes from `packed_input`, dequantizes them
/// to FP16 values via polar dequantization, applies QJL residual correction,
/// applies the inverse Hadamard transform, and writes FP16 output to
/// `decompressed_output`. Matches the L2 decompression pipeline but with 2-bit
/// precision for cold pages stored in DRAM.
///
/// `head_dim`: dimension per KV head (e.g. 120 for Gemma4, 64 for Qwen)
/// `n_kv_heads`: number of KV heads
pub fn generate_l3_decompress_mil(head_dim: u32, n_kv_heads: u32) -> String {
    let mut mil = String::new();
    let bits: u32 = 2;

    mil.push_str("# Generated by Tribunus ANE L3 2-bit Decompression\n");
    mil.push_str(&format!(
        "# head_dim: {} n_kv_heads: {} bits: {}\n\n",
        head_dim, n_kv_heads, bits,
    ));

    // Input: packed 2-bit bytes.
    let packed_size = (head_dim * n_kv_heads * bits / 16).max(64);
    mil.push_str(&format!(
        "input @ \"input\" (float16, {}) read write\n",
        packed_size,
    ));

    // Output: decompressed FP16.
    let output_size = head_dim * n_kv_heads;
    mil.push_str(&format!(
        "output @ \"output\" (float16, {}) read write\n\n",
        output_size,
    ));

    // Dequantize: unpack 2-bit values and apply scale (polar mode).
    mil.push_str(&format!(
        "layer dequant {{\n  type: dequantize\n  input: \"input\"\n  output: \"unpacked\"\n  mode: \"polar\"\n  bits: {}\n}}\n",
        bits,
    ));

    // Apply QJL correction (element-wise additive residual).
    mil.push_str(
        "layer qjl_correct {\n  type: add\n  input: \"unpacked\"\n  output: \"corrected\"\n}\n",
    );

    // Inverse Hadamard transform (Hadamard is self-inverse).
    mil.push_str(
        "layer inv_hadamard {\n  type: hadamard_transform\n  input: \"corrected\"\n  output: \"output\"\n}\n",
    );

    mil
}

/// Manager that loads and runs ANE compression/decompression programs.
///
/// Owns four pre-compiled Core ML models targeting the ANE:
/// - L2 compress/decompress (3.5-bit TurboQuant, IOSurface tier)
/// - L3 compress/decompress (2-bit TurboQuant, DRAM heap tier)
///
/// Each model takes an IOSurface-backed Arena as input and writes to another
/// Arena as output. The caller (PageMigrationService) owns the page data and
/// copies bytes into/from the arenas before/after prediction.
pub struct AneCompressor {
    /// Compiles FP16 → 3.5-bit (L2 warm tier).
    pub l2_compress: CoreMlModel,
    /// Compiles 3.5-bit → FP16 (L2→L1 promotion).
    pub l2_decompress: CoreMlModel,
    /// Compiles FP16 → 2-bit (L3 cold tier).
    pub l3_compress: CoreMlModel,
    /// Compiles 2-bit → FP16 (L3→L2/L1 promotion).
    pub l3_decompress: CoreMlModel,
    /// Reusable input IOSurface arena for feeding data to the ANE.
    pub input_arena: Arena,
    /// Reusable output IOSurface arena for reading results from the ANE.
    pub output_arena: Arena,
}

impl AneCompressor {
    /// Port names for the L2 decompress MIL (from generate_kv_decompress_mil).
    const L2_DECOMPRESS_INPUT: &'static str = "compressed_input";
    const L2_DECOMPRESS_OUTPUT: &'static str = "decompressed_output";
    /// Port names for the L3 compress/decompress MIL (from generate_l3_*_mil).
    const L3_INPUT: &'static str = "input";
    const L3_OUTPUT: &'static str = "output";
    /// Port names for the L2 compress MIL (from generate_kv_compress_mil).
    const L2_COMPRESS_INPUT: &'static str = "input";
    const L2_COMPRESS_OUTPUT: &'static str = "output";

    /// Create a new AneCompressor by compiling all four MIL programs.
    ///
    /// `head_dim`: KV head dimension
    /// `n_kv_heads`: number of KV heads
    ///
    /// Pre-allocates input and output arenas sized for the largest operation
    /// (decompressed output = head_dim × n_kv_heads FP16 elements).
    pub fn new(head_dim: u32, n_kv_heads: u32) -> Result<Self, String> {
        let l2_compress_mil = generate_kv_compress_mil(head_dim, n_kv_heads, 3);
        let l2_decompress_mil =
            generate_kv_decompress_mil(head_dim, n_kv_heads, 3);
        let l3_compress_mil = generate_l3_compress_mil(head_dim, n_kv_heads);
        let l3_decompress_mil = generate_l3_decompress_mil(head_dim, n_kv_heads);

        let l2_compress = compile_mil_text(&l2_compress_mil)?;
        let l2_decompress = compile_mil_text(&l2_decompress_mil)?;
        let l3_compress = compile_mil_text(&l3_compress_mil)?;
        let l3_decompress = compile_mil_text(&l3_decompress_mil)?;

        // Allocate arenas sized for the largest FP16 page.
        let arena_size = head_dim * n_kv_heads;
        let input_arena = Arena::new(arena_size, 1, mlx_rs::Dtype::Float16)
            .map_err(|e| format!("AneCompressor input arena: {}", e))?;
        let output_arena = Arena::new(arena_size, 1, mlx_rs::Dtype::Float16)
            .map_err(|e| format!("AneCompressor output arena: {}", e))?;

        Ok(Self {
            l2_compress,
            l2_decompress,
            l3_compress,
            l3_decompress,
            input_arena,
            output_arena,
        })
    }

    /// Compress FP16 page data to 2-bit L3 format via the ANE.
    ///
    /// Copies `fp16_data` (length = head_dim × n_kv_heads) into the input
    /// arena, runs the L3 compress model, and returns the packed 2-bit bytes.
    pub fn compress_to_l3(&self, fp16_data: &[f32], head_dim: u32, n_kv_heads: u32) -> Result<Vec<u8>, String> {
        let elem_count = (head_dim * n_kv_heads) as usize;
        if fp16_data.len() < elem_count {
            return Err(format!(
                "AneCompressor: need {} elements for L3 compress, got {}",
                elem_count,
                fp16_data.len()
            ));
        }
        self.run_compress_l3(fp16_data, elem_count)
    }

    /// Decompress 2-bit L3 packed bytes back to FP16 via the ANE.
    ///
    /// Copies `packed_data` into the input arena, runs the L3 decompress
    /// model, and returns the decompressed FP16 values.
    pub fn decompress_from_l3(&self, packed_data: &[u8], head_dim: u32, n_kv_heads: u32) -> Result<Vec<f32>, String> {
        let packed_size = ((head_dim * n_kv_heads * 2) / 16).max(64) as usize;
        if packed_data.len() < packed_size {
            return Err(format!(
                "AneCompressor: need {} bytes for L3 decompress, got {}",
                packed_size,
                packed_data.len()
            ));
        }
        self.run_decompress_l3(packed_data, (head_dim * n_kv_heads) as usize)
    }

    /// Compress FP16 page data to 3.5-bit L2 format via the ANE.
    pub fn compress_to_l2(&self, fp16_data: &[f32], head_dim: u32, n_kv_heads: u32, _bits: u32) -> Result<Vec<u8>, String> {
        let elem_count = (head_dim * n_kv_heads) as usize;
        if fp16_data.len() < elem_count {
            return Err(format!(
                "AneCompressor: need {} elements for L2 compress, got {}",
                elem_count, fp16_data.len()
            ));
        }
        self.run_compress_l2(fp16_data, elem_count)
    }

    /// Decompress 3.5-bit L2 packed bytes back to FP16 via the ANE.
    pub fn decompress_from_l2(&self, packed_data: &[u8], head_dim: u32, n_kv_heads: u32, _bits: u32) -> Result<Vec<f32>, String> {
        let elem_count = (head_dim * n_kv_heads) as usize;
        self.run_decompress_l2(packed_data, elem_count)
    }

    // ── Internal helpers ──────────────────────────────────────────────

    fn run_compress_l3(&self, fp16_data: &[f32], elem_count: usize) -> Result<Vec<u8>, String> {
        self.run_compress(&self.l3_compress, fp16_data, elem_count, Self::L3_INPUT, Self::L3_OUTPUT)
    }

    fn run_decompress_l3(&self, packed_data: &[u8], elem_count: usize) -> Result<Vec<f32>, String> {
        self.run_decompress(&self.l3_decompress, packed_data, elem_count, Self::L3_INPUT, Self::L3_OUTPUT)
    }

    fn run_compress_l2(&self, fp16_data: &[f32], elem_count: usize) -> Result<Vec<u8>, String> {
        self.run_compress(&self.l2_compress, fp16_data, elem_count, Self::L2_COMPRESS_INPUT, Self::L2_COMPRESS_OUTPUT)
    }

    fn run_decompress_l2(&self, packed_data: &[u8], elem_count: usize) -> Result<Vec<f32>, String> {
        self.run_decompress(&self.l2_decompress, packed_data, elem_count, Self::L2_DECOMPRESS_INPUT, Self::L2_DECOMPRESS_OUTPUT)
    }

    /// Run a compress model: copy FP16 bytes into input arena, predict, read output bytes.
    fn run_compress(&self, model: &CoreMlModel, fp16_data: &[f32], elem_count: usize, input_name: &str, output_name: &str) -> Result<Vec<u8>, String> {
        // SAFETY: we own the arenas and hold the only references.
        unsafe {
            std::ptr::copy_nonoverlapping(
                fp16_data.as_ptr() as *const u8,
                self.input_arena.base_ptr() as *mut u8,
                elem_count * 4, // f32 → 4 bytes each
            );
        }
        self.predict_raw(model, input_name, output_name)?;
        let packed_len = self.output_arena.byte_len();
        let mut output = vec![0u8; packed_len];
        unsafe {
            std::ptr::copy_nonoverlapping(
                self.output_arena.base_ptr() as *const u8,
                output.as_mut_ptr(),
                packed_len,
            );
        }
        Ok(output)
    }

    /// Run a decompress model: copy packed bytes into input arena, predict, read FP16 output.
    fn run_decompress(&self, model: &CoreMlModel, packed_data: &[u8], elem_count: usize, input_name: &str, output_name: &str) -> Result<Vec<f32>, String> {
        let packed_len = packed_data.len();
        unsafe {
            std::ptr::copy_nonoverlapping(
                packed_data.as_ptr(),
                self.input_arena.base_ptr() as *mut u8,
                packed_len,
            );
        }
        self.predict_raw(model, input_name, output_name)?;
        let mut output = vec![0f32; elem_count];
        unsafe {
            std::ptr::copy_nonoverlapping(
                self.output_arena.base_ptr() as *const u8,
                output.as_mut_ptr() as *mut u8,
                elem_count * 4,
            );
        }
        Ok(output)
    }

    /// Predict using the given model. Copies from input_arena → model → output_arena.
    fn predict_raw(
        &self,
        model: &CoreMlModel,
        input_name: &str,
        output_name: &str,
    ) -> Result<(), String> {
        // Direct FFI call: we hold the only reference to our arenas, so the
        // const → mut cast on output_arena is safe.
        let input_info = &self.input_arena.info;
        let output_info = &self.output_arena.info;
        let c_in = std::ffi::CString::new(input_name)
            .map_err(|e| format!("CString input_name: {}", e))?;
        let c_out = std::ffi::CString::new(output_name)
            .map_err(|e| format!("CString output_name: {}", e))?;
        let rc = unsafe {
            crate::coreml_bridge::tribunus_coreml_predict_pixelbuffer(
                model.ptr,
                c_in.as_ptr(),
                input_info,
                c_out.as_ptr(),
                output_info as *const _ as *mut _,
            )
        };
        if rc != 0 {
            return Err(format!("AneCompressor: ANE predict failed with code {}", rc));
        }
        Ok(())
    }
}

/// Generate MIL program text for KV cache compression (FP16 → packed bits).
///
/// The program reads FP16 values from `value_input` and quantizes them to
/// packed bits using polar quantization with learned scale.
///
/// `head_dim`: dimension per KV head
/// `n_kv_heads`: number of KV heads
/// `bits`: quantization bits per value (3-4 for L2, 2 for L3)
pub fn generate_kv_compress_mil(head_dim: u32, n_kv_heads: u32, bits: u32) -> String {
    let mut mil = String::new();

    mil.push_str("# Generated by Tribunus ANE KV Compression\n");
    mil.push_str(&format!(
        "# head_dim: {} n_kv_heads: {} bits: {}\n\n",
        head_dim, n_kv_heads, bits,
    ));

    // Input: FP16 values.
    let input_size = head_dim * n_kv_heads;
    mil.push_str(&format!(
        "input @ \"input\" (float16, {}) read write\n",
        input_size,
    ));

    // Output: packed bits.
    let packed_size = (head_dim * n_kv_heads * bits / 16).max(64);
    mil.push_str(&format!(
        "output @ \"output\" (float16, {}) read write\n\n",
        packed_size,
    ));

    // Quantize: FP16 → packed bits.
    mil.push_str(&format!(
        "layer quantize {{\n  type: quantize\n  input: \"input\"\n  output: \"output\"\n  mode: \"polar\"\n  bits: {}\n}}\n",
        bits,
    ));

    mil
}

/// Compile MIL text to a Core ML model targeting ANE.
///
/// Writes the MIL text to a temporary `.mlmodel` file, loads it via
/// Core ML's model loading API with `CpuAndNeuralEngine` compute units,
/// and removes the temp file on success.
pub fn compile_mil_text(mil_text: &str) -> Result<CoreMlModel, String> {
    // Generate a unique temp path under the system temp directory
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let tmp = std::env::temp_dir().join(format!("ane_prog_{:x}.mlmodel", nanos));

    // Write MIL text to the temp file
    std::fs::write(&tmp, mil_text).map_err(|e| format!("write MIL: {}", e))?;

    // Load via Core ML with ANE compute units (CpuAndNeuralEngine)
    let model = CoreMlModel::load_with_compute_units(
        tmp.to_str().ok_or_else(|| "bad temp path".to_string())?,
        CoreMlComputeUnits::CpuAndNeuralEngine,
    )?;

    // Clean up the temp file; ignore cleanup failure
    let _ = std::fs::remove_file(&tmp);

    Ok(model)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_kv_decompress_mil_contains_expected_sections() {
        let mil = generate_kv_decompress_mil(120, 8, 3);
        assert!(mil.contains("head_dim: 120"), "header should contain head_dim");
        assert!(mil.contains("n_kv_heads: 8"), "header should contain n_kv_heads");
        assert!(mil.contains("bits: 3"), "header should contain bits");
        assert!(mil.contains("compressed_input"), "should declare input");
        assert!(mil.contains("decompressed_output"), "should declare output");
        assert!(mil.contains("type: dequantize"), "should have dequantize layer");
        assert!(mil.contains("mode: \"polar\""), "should use polar mode");
        assert!(mil.contains("type: add"), "should have add layer for QJL");
        assert!(mil.contains("type: hadamard_transform"), "should have Hadamard");
    }

    #[test]
    fn test_generate_kv_decompress_mil_size_calculation() {
        // head_dim=120, n_kv_heads=8, bits=3
        // packed = max(120*8*3/16, 64) = max(180, 64) = 180
        let mil = generate_kv_decompress_mil(120, 8, 3);
        assert!(mil.contains("(float16, 180)"), "packed input size should be 180");

        // output = 120 * 8 = 960
        assert!(mil.contains("(float16, 960)"), "output size should be 960");
    }

    #[test]
    fn test_generate_kv_decompress_mil_minimum_packed_size() {
        // Small config: packed size would be below minimum
        let mil = generate_kv_decompress_mil(64, 1, 3);
        // packed = max(64*1*3/16, 64) = max(12, 64) = 64
        assert!(mil.contains("(float16, 64)"), "minimum packed size should be 64");
    }

    #[test]
    fn test_generate_attention_mil_contains_expected_sections() {
        let mil = generate_attention_mil(32, 8, 128, 4096);
        assert!(mil.contains("query"), "should have query input");
        assert!(mil.contains("key"), "should have key input");
        assert!(mil.contains("value"), "should have value input");
        assert!(mil.contains("attention_output"), "should have attention output");
        assert!(mil.contains("type: batched_matmul"), "should have batched_matmul");
        assert!(mil.contains("type: softmax"), "should have softmax");
    }

    #[test]
    fn test_compile_mil_text_returns_err_for_invalid_mil() {
        // Invalid MIL text should fail to compile
        let result = compile_mil_text("not valid mil at all {{{");
        assert!(result.is_err(), "compilation of garbage MIL should fail");
    }

    #[test]
    fn test_kv_decompress_mil_smoke() {
        // Just verify that the MIL is non-empty and structurally valid
        let mil = generate_kv_decompress_mil(64, 4, 4);
        assert!(!mil.is_empty(), "MIL text should not be empty");
        assert!(mil.starts_with('#'), "MIL should start with header comment");
        assert!(mil.contains("layer dequant {"), "should open dequant layer");
        assert!(mil.contains("layer qjl_correct {"), "should open qjl_correct layer");
        assert!(mil.contains("layer inv_hadamard {"), "should open inv_hadamard layer");
    }
}
