use serde::{Deserialize, Serialize}; use std::collections::HashMap;
#[derive(Debug,Clone,Serialize,Deserialize,Default,PartialEq,Eq)] pub struct HardwareCapabilities{pub ane:bool,pub metal:bool,pub accelerate:bool,pub video_toolbox:bool,pub av_foundation:bool}
#[derive(Debug,Clone,Serialize,Deserialize,PartialEq,Eq)] pub struct ModelIoBinding{pub name:String,pub kind:ModelIoKind,pub dtype:String,pub shape:Vec<usize>,pub optional:bool}
#[derive(Debug,Clone,Serialize,Deserialize,PartialEq,Eq)] pub enum ModelIoKind{Input,Output,Tokens,Embedding,ImageRgba,AudioPcm,VideoFrame}
#[derive(Debug,Clone,Serialize,Deserialize,Default,PartialEq,Eq)] pub struct ModelManifest{pub id:String,pub modality:ModelModality,pub inputs:Vec<ModelIoBinding>,pub outputs:Vec<ModelIoBinding>,pub requirements:ModelRequirements,pub program_names:Vec<String>,pub projectors:Vec<ModelProjectorBinding>,pub fusion_inputs:Vec<String>}
#[derive(Debug,Clone,Serialize,Deserialize,PartialEq,Eq)] pub enum ModelModality{Text,Audio,Image,Vision,Video,Multimodal}
impl Default for ModelModality { fn default()->Self { Self::Text } }
#[derive(Debug,Clone,Serialize,Deserialize,Default,PartialEq,Eq)] pub struct ModelProjectorBinding{pub tensor_name:String,pub input_dim:usize,pub output_dim:usize}
#[derive(Debug,Clone,Serialize,Deserialize,Default,PartialEq,Eq)] pub struct ModelRequirements{pub ane:bool,pub metal:bool,pub accelerate:bool,pub video_toolbox:bool,pub av_foundation:bool}
impl ModelRequirements{pub fn validate_against(&self,h:HardwareCapabilities)->Result<(),String>{for (n,a,s) in [(self.ane,h.ane,"ANE"),(self.metal,h.metal,"Metal"),(self.accelerate,h.accelerate,"Accelerate"),(self.video_toolbox,h.video_toolbox,"VideoToolbox"),(self.av_foundation,h.av_foundation,"AVFoundation")]{if n&&!a{return Err(format!("requires unavailable {s}"))}}Ok(())}}
#[derive(Debug,Clone,Serialize,Deserialize,Default,PartialEq,Eq)] pub struct MultiModelManifest{pub models:HashMap<String,ModelManifest>}
impl MultiModelManifest{pub fn insert(&mut self,m:ModelManifest)->Result<(),String>{if self.models.insert(m.id.clone(),m).is_some(){return Err("duplicate model id".into())}Ok(())}pub fn get(&self,id:&str)->Option<&ModelManifest>{self.models.get(id)}pub fn validate(&self)->Result<(),String>{if self.models.is_empty(){Err("manifest contains no models".into())}else{Ok(())}}pub fn select_modality(&self,x:ModelModality)->Result<&ModelManifest,String>{self.models.values().find(|m|m.modality==x).ok_or_else(||format!("no model for modality {x:?}"))}pub fn validate_io(&self,id:&str,i:&[&str],o:&[&str])->Result<(),String>{let m=self.get(id).ok_or_else(||format!("unknown model {id}"))?;if i.iter().any(|n|!m.inputs.iter().any(|b|b.name==*n))||o.iter().any(|n|!m.outputs.iter().any(|b|b.name==*n)){Err("invalid model I/O binding".into())}else{Ok(())}}pub fn validate_hardware(&self,id:&str,h:HardwareCapabilities)->Result<(),String>{self.get(id).ok_or_else(||format!("unknown model {id}"))?.requirements.validate_against(h)}}
