#[cfg(test)]
mod tests {
    use crate::runtime::ledger::{
        DeterministicReceiptPayload, JcsReceiptEncoder, ReceiptHasher,
        SemanticStampedCommand, SemanticCommandPayload, CanonicalReceiptEncoder,
        TransitionReceipt,
    };
    use crate::runtime::scheduling::metadata::{Stage, SystemId};
    use crate::runtime::world::Entity;

    /// Canonical JSON (RFC 8785) output for a minimal one-command payload.
    /// Generated by `serde_jcs::to_vec` with the test_payload() fixture.
    const EXPECTED_CANONICAL_BYTES: &[u8] = br#"{"command_count":1,"commands":[{"command":{"data":{"entity_kind":"test_entity"},"kind":"entity_spawned"},"entity":0,"entity_generation":null,"sequence":0,"stage":"Intake","system_id":0}],"microcycle":0,"receipt_sequence":0,"scheduler_epoch":0,"schema_version":1,"stage":"Intake"}"#;

    /// Blake3-256 digest of the canonical bytes above (hex).
    const EXPECTED_BLAKE3_HEX: &str = "f72b09b19256ef121e2db3076a460442a0aae1c681035f1f18a708bf7d4336ea";

    fn test_payload() -> DeterministicReceiptPayload {
        DeterministicReceiptPayload {
            schema_version: 1,
            receipt_sequence: 0,
            scheduler_epoch: 0,
            microcycle: 0,
            stage: Stage::Intake,
            command_count: 1,
            commands: vec![SemanticStampedCommand {
                stage: Stage::Intake,
                system_id: SystemId(0),
                entity: Entity(0),
                entity_generation: None,
                sequence: 0,
                command: SemanticCommandPayload::EntitySpawned {
                    entity_kind: "test_entity".to_string(),
                },
            }],
        }
    }

    // ------------------------------------------------------------------
    // Canonical encoder tests
    // ------------------------------------------------------------------

    #[test]
    fn jcs_encoder_matches_expected_canonical_bytes() {
        let encoder = JcsReceiptEncoder;
        let result = encoder.encode(&test_payload());
        assert!(result.is_ok(), "JCS encoding should succeed: {:?}", result);

        let canonical = result.unwrap();
        assert_eq!(
            canonical, EXPECTED_CANONICAL_BYTES,
            "canonical JCS output must match the fixed test vector"
        );
    }

    #[test]
    fn canonical_encoder_rejects_invalid_payload() {
        // For valid payloads, the encoder must succeed.
        // (InvalidPayload is reserved for future payloads that violate
        //  canonical JSON constraints; currently no payload type does.)
        let encoder = JcsReceiptEncoder;
        let result = encoder.encode(&test_payload());
        assert!(
            result.is_ok(),
            "a well-formed DeterministicReceiptPayload must encode without error"
        );
    }

    // ------------------------------------------------------------------
    // Receipt hasher tests
    // ------------------------------------------------------------------

    #[test]
    fn receipt_hasher_production_constructs() {
        let hasher = ReceiptHasher::production();
        let digest = hasher.compute(&test_payload());
        assert!(digest.is_ok(), "production hasher must compute a digest");
        assert_eq!(digest.as_ref().unwrap().algorithm, "blake3-256-jcs-rfc8785");
    }

    #[test]
    fn receipt_hasher_matches_fixed_blake3_test_vector() {
        let hasher = ReceiptHasher::production();
        let digest = hasher.compute(&test_payload()).unwrap();
        assert_eq!(
            digest.hex, EXPECTED_BLAKE3_HEX,
            "blake3 digest must match the fixed test vector"
        );
    }

    #[test]
    fn receipt_digest_ignores_observed_at_ns() {
        let hasher = ReceiptHasher::production();

        // Two TransitionReceipts with identical payloads but different timestamps.
        let receipt_a = TransitionReceipt {
            payload: test_payload(),
            deterministic_digest: hasher.compute(&test_payload()).unwrap(),
            observed_at_ns: Some(1000),
        };
        let receipt_b = TransitionReceipt {
            payload: test_payload(),
            deterministic_digest: hasher.compute(&test_payload()).unwrap(),
            observed_at_ns: Some(999_999_999),
        };

        // The digest is computed over the payload only — observed_at_ns is metadata.
        assert_eq!(
            hasher.compute(&receipt_a.payload).unwrap(),
            hasher.compute(&receipt_b.payload).unwrap(),
            "observed_at_ns must not affect the deterministic digest"
        );
    }

    #[test]
    fn receipt_digest_detects_changed_schema_version() {
        let hasher = ReceiptHasher::production();

        let mut payload_b = test_payload();
        payload_b.schema_version = 2;

        let digest_a = hasher.compute(&test_payload()).unwrap();
        let digest_b = hasher.compute(&payload_b).unwrap();

        assert_ne!(
            digest_a, digest_b,
            "changing schema_version must produce a different digest"
        );
    }

    // ------------------------------------------------------------------
    // Serialization roundtrip
    // ------------------------------------------------------------------

    #[test]
    fn transition_receipt_serde_roundtrip() {
        let hasher = ReceiptHasher::production();
        let receipt = TransitionReceipt {
            payload: test_payload(),
            deterministic_digest: hasher.compute(&test_payload()).unwrap(),
            observed_at_ns: Some(42),
        };

        let json = serde_json::to_string(&receipt).unwrap();
        let deserialized: TransitionReceipt = serde_json::from_str(&json).unwrap();

        assert_eq!(receipt, deserialized, "JSON roundtrip must preserve all fields");
        assert_eq!(
            deserialized.observed_at_ns,
            Some(42),
            "observed_at_ns must survive roundtrip"
        );
    }

    #[test]
    fn transition_receipt_serde_roundtrip_observed_none() {
        let hasher = ReceiptHasher::production();
        let receipt = TransitionReceipt {
            payload: test_payload(),
            deterministic_digest: hasher.compute(&test_payload()).unwrap(),
            observed_at_ns: None,
        };

        let json = serde_json::to_string(&receipt).unwrap();
        let deserialized: TransitionReceipt = serde_json::from_str(&json).unwrap();

        assert_eq!(receipt, deserialized, "JSON roundtrip with None observed_at_ns");
        assert!(
            deserialized.observed_at_ns.is_none(),
            "None observed_at_ns must roundtrip correctly"
        );
    }
}
