//! Metal kernel source code generation from fusion region definitions.
//!
//! For each selected fusion region, [`generate_metal_source`] produces a
//! complete `.metal` source file with the appropriate kernel function,
//! buffer bindings, and Metal Shading Language 3.2 attributes.

use crate::compute_image::fusion_plan::SelectedFusionRegion;

/// The generated Metal source and its metadata.
#[derive(Debug, Clone)]
pub struct MetalCodegenOutput {
    /// Kernel function name (entry point for dispatch).
    pub entry_point: String,
    /// The complete `.metal` source string.
    pub source: String,
    /// Number of threads per threadgroup (threads_per_threadgroup in each dim).
    pub threads_per_threadgroup: [u32; 3],
    /// Tiling parameters used by the kernel.
    pub tile_m: u32,
    pub tile_k: u32,
    pub tile_n: u32,
}

/// Generate a `.metal` source file for a selected fusion region.
pub fn generate_metal_source(region: &SelectedFusionRegion) -> MetalCodegenOutput {
    let entry_point = format!("{}_kernel", region.region_id);
    let tile_m = 32u32;
    let tile_k = 64u32;
    let tile_n = 32u32;

    let hs = region.hidden_size;
    let is = region.intermediate_size;
    let nh = region.num_heads;
    let hd = region.head_dim;

    let source = match region.region_id.as_str() {
        "qkv_proj" => qkv_proj_kernel(&entry_point, tile_m, tile_k, tile_n, hs),
        "attn_out" => attn_out_kernel(&entry_point, tile_m, tile_k, tile_n, hs),
        "gate_up_proj" => gate_up_proj_kernel(&entry_point, tile_m, tile_k, tile_n, hs, is),
        "silu_mul" => silu_mul_kernel(&entry_point),
        "down_proj" => down_proj_kernel(&entry_point, tile_m, tile_k, tile_n, hs, is),
        "rms_norm_residual" => rms_norm_residual_kernel(&entry_point, hs),
        "self_attn" => self_attn_kernel(&entry_point, hs, nh, hd),
        other => panic!("unrecognised fusion region: {}", other),
    };

    MetalCodegenOutput {
        entry_point,
        source,
        threads_per_threadgroup: [tile_m, tile_n, 1],
        tile_m,
        tile_k,
        tile_n,
    }
}

// ── Kernel templates ──────────────────────────────────────────────────────

fn qkv_proj_kernel(name: &str, tm: u32, tk: u32, tn: u32, hidden_size: u64) -> String {
    let hs = hidden_size;
    format!(
        r#"// Auto-generated by Tribunus compute compiler
#include <metal_stdlib>
using namespace metal;

kernel void {name}(
    device const half* hidden  [[buffer(0)]],
    device const half* weight_q [[buffer(1)]],
    device const half* weight_k [[buffer(2)]],
    device const half* weight_v [[buffer(3)]],
    device half* q_out          [[buffer(4)]],
    device half* k_out          [[buffer(5)]],
    device half* v_out          [[buffer(6)]],
    uint2 gid                   [[thread_position_in_grid]]
) {{
    uint row = gid.x * {tm};
    uint col = gid.y * {tn};
    // Fused QKV projection: three matmuls in one kernel.
    // Each head group reads hidden once, writes Q/K/V concatenated.
    // Full implementation would tile over K dimension with simdgroup matrix ops.
    // For now: naive reference that the compiler can verify produces correct
    // output before the optimized tile version replaces it.
    for (uint i = 0; i < {tm} && row + i < {hs}; ++i) {{
        for (uint j = 0; j < {tn} && col + j < {hs}; ++j) {{
            half sum_q = 0, sum_k = 0, sum_v = 0;
            for (uint k = 0; k < {tk} && col * {tm} + k < {hs}; ++k) {{
                half x = hidden[(row + i) * {hs} + col * {tm} + k];
                sum_q += x * weight_q[(col + j) * {hs} + col * {tm} + k];
                sum_k += x * weight_k[(col + j) * {hs} + col * {tm} + k];
                sum_v += x * weight_v[(col + j) * {hs} + col * {tm} + k];
            }}
            q_out[(row + i) * {hs} + col + j] = sum_q;
            k_out[(row + i) * {hs} + col + j] = sum_k;
            v_out[(row + i) * {hs} + col + j] = sum_v;
        }}
    }}
}}
"#,
        name = name,
        tm = tm,
        tk = tk,
        tn = tn,
        hs = hs
    )
}

fn attn_out_kernel(name: &str, tm: u32, tk: u32, tn: u32, hidden_size: u64) -> String {
    let hs = hidden_size;
    format!(
        r#"// Auto-generated by Tribunus compute compiler
#include <metal_stdlib>
using namespace metal;

kernel void {name}(
    device const half* attn_input [[buffer(0)]],
    device const half* weight     [[buffer(1)]],
    device half* output           [[buffer(2)]],
    uint2 gid                     [[thread_position_in_grid]]
) {{
    uint row = gid.x * {tm};
    uint col = gid.y * {tn};
    for (uint i = 0; i < {tm} && row + i < {hs}; ++i) {{
        half sum = 0;
        for (uint k = 0; k < {tk}; ++k) {{
            sum += attn_input[(row + i) * {hs} + k] * weight[k * {hs} + col];
        }}
        output[(row + i) * {hs} + col] = sum;
    }}
}}
"#,
        name = name,
        tm = tm,
        tk = tk,
        tn = tn,
        hs = hs
    )
}

fn gate_up_proj_kernel(
    name: &str,
    tm: u32,
    tk: u32,
    tn: u32,
    hidden_size: u64,
    intermediate_size: u64,
) -> String {
    let hs = hidden_size;
    let is = intermediate_size;
    format!(
        r#"// Auto-generated by Tribunus compute compiler
#include <metal_stdlib>
using namespace metal;

kernel void {name}(
    device const half* hidden    [[buffer(0)]],
    device const half* weight_gate [[buffer(1)]],
    device const half* weight_up   [[buffer(2)]],
    device half* gate_out         [[buffer(3)]],
    device half* up_out           [[buffer(4)]],
    uint2 gid                     [[thread_position_in_grid]]
) {{
    uint row = gid.x * {tm};
    uint col = gid.y * {tn};
    for (uint i = 0; i < {tm} && row + i < {hs}; ++i) {{
        for (uint j = 0; j < {tn} && col + j < {is}; ++j) {{
            half sum_g = 0, sum_u = 0;
            for (uint k = 0; k < {tk} && col * {tm} + k < {hs}; ++k) {{
                half x = hidden[(row + i) * {hs} + col * {tm} + k];
                sum_g += x * weight_gate[(col + j) * {hs} + col * {tm} + k];
                sum_u += x * weight_up[(col + j) * {hs} + col * {tm} + k];
            }}
            gate_out[(row + i) * {is} + col + j] = sum_g;
            up_out[(row + i) * {is} + col + j] = sum_u;
        }}
    }}
}}
"#,
        name = name,
        tm = tm,
        tk = tk,
        tn = tn,
        hs = hs,
        is = is
    )
}

fn silu_mul_kernel(name: &str) -> String {
    format!(
        r#"// Auto-generated by Tribunus compute compiler
#include <metal_stdlib>
using namespace metal;

kernel void {name}(
    device const half* gate [[buffer(0)]],
    device const half* up   [[buffer(1)]],
    device half* output     [[buffer(2)]],
    uint tid                 [[thread_position_in_grid]]
) {{
    half g = gate[tid];
    half u = up[tid];
    // SiLU: x * sigmoid(x)
    half sig = 1.0 / (1.0 + exp(-g));
    output[tid] = g * sig * u;
}}
"#,
        name = name
    )
}

fn down_proj_kernel(
    name: &str,
    tm: u32,
    tk: u32,
    tn: u32,
    hidden_size: u64,
    intermediate_size: u64,
) -> String {
    let hs = hidden_size;
    let is = intermediate_size;
    format!(
        r#"// Auto-generated by Tribunus compute compiler
#include <metal_stdlib>
using namespace metal;

kernel void {name}(
    device const half* activation [[buffer(0)]],
    device const half* weight     [[buffer(1)]],
    device half* output           [[buffer(2)]],
    uint2 gid                     [[thread_position_in_grid]]
) {{
    uint row = gid.x * {tm};
    uint col = gid.y * {tn};
    for (uint i = 0; i < {tm} && row + i < {is}; ++i) {{
        half sum = 0;
        for (uint k = 0; k < {tk}; ++k) {{
            sum += activation[(row + i) * {is} + k] * weight[k * {hs} + col];
        }}
        output[(row + i) * {hs} + col] = sum;
    }}
}}
"#,
        name = name,
        tm = tm,
        tk = tk,
        tn = tn,
        hs = hs,
        is = is
    )
}

fn rms_norm_residual_kernel(name: &str, hidden_size: u64) -> String {
    let hs = hidden_size;
    format!(
        r#"// Auto-generated by Tribunus compute compiler
#include <metal_stdlib>
using namespace metal;

kernel void {name}(
    device const half* hidden   [[buffer(0)]],
    device const half* residual [[buffer(1)]],
    device const half* weight   [[buffer(2)]],
    device half* output         [[buffer(3)]],
    constant float& eps         [[buffer(4)]],
    uint tid                    [[thread_position_in_grid]]
) {{
    // Compute RMS norm of hidden, scale by weight, add residual.
    // Single-element reduction — in production this would use
    // simdgroup_sum for data-parallel reduction.
    float sum_sq = 0;
    for (uint i = 0; i < {hs}; ++i) {{
        float x = hidden[tid * {hs} + i];
        sum_sq += x * x;
    }}
    float rms = sqrt(sum_sq / {hs}.0 + eps);
    for (uint i = 0; i < {hs}; ++i) {{
        output[tid * {hs} + i] = hidden[tid * {hs} + i] / rms * weight[i] + residual[tid * {hs} + i];
    }}
}}
"#,
        name = name,
        hs = hs
    )
}

fn self_attn_kernel(name: &str, hidden_size: u64, num_heads: u64, head_dim: u64) -> String {
    let hs = hidden_size;
    format!(
        r#"// Auto-generated by Tribunus compute compiler
#include <metal_stdlib>
using namespace metal;

kernel void {name}(
    device const half* hidden      [[buffer(0)]],
    device const half* weight_qkv  [[buffer(1)]],
    device const half* weight_out  [[buffer(2)]],
    device half* output            [[buffer(3)]],
    uint tid                       [[thread_position_in_grid]]
) {{
    // Self-attention fused megakernel: QKV projection + score + softmax + output.
    // This version demonstrates the fused dispatch boundary.
    // Production version would tile QK^T over the sequence dimension
    // and use simdgroup matrix multiply+accumulate.
    // Naive reference implementation for correctness verification.
    half q[{hs}], k[{hs}], v[{hs}];

    // QKV projections (simplified — one head)
    for (uint i = 0; i < {hs}; ++i) {{
        half sum_q = 0, sum_k = 0, sum_v = 0;
        for (uint j = 0; j < {hs}; ++j) {{
            half x = hidden[tid * {hs} + j];
            sum_q += x * weight_qkv[j * 3 * {hs} + i];
            sum_k += x * weight_qkv[j * 3 * {hs} + {hs} + i];
            sum_v += x * weight_qkv[j * 3 * {hs} + 2 * {hs} + i];
        }}
        q[i] = sum_q;
        k[i] = sum_k;
        v[i] = sum_v;
    }}

    // Score = softmax(Q * K^T)
    // (naive single-token decode — only scores with itself)
    float score = 0;
    for (uint i = 0; i < {hs}; ++i) {{
        score += (float)q[tid] * (float)k[i];
    }}
    score = exp(score);
    // Apply to V
    half attn_out = 0;
    for (uint i = 0; i < {hs}; ++i) {{
        attn_out += (half)score * v[i];
    }}

    // Output projection
    for (uint i = 0; i < {hs}; ++i) {{
        output[tid * {hs} + i] = attn_out * weight_out[i];
    }}
}}
"#,
        name = name,
        hs = hs
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compute_image::fusion_plan::SelectedFusionRegion;
    use crate::fusion_region::FusionImplBackend;

    fn sample_region(id: &str) -> SelectedFusionRegion {
        SelectedFusionRegion {
            region_id: id.into(),
            ops: vec![],
            backend: FusionImplBackend::MlxGpu,
            eliminated_intermediates: 0,
            input_elements: 4096,
            output_elements: 4096,
            hidden_size: 4096,
            num_heads: 32,
            num_kv_heads: 8,
            head_dim: 128,
            intermediate_size: 14336,
        }
    }

    #[test]
    fn test_generate_qkv_proj_contains_kernel_attr() {
        let out = generate_metal_source(&sample_region("qkv_proj"));
        assert!(out.source.contains("kernel void"));
        assert!(out.source.contains("qkv_proj_kernel"));
        assert!(out.source.contains("[[buffer("));
    }

    #[test]
    fn test_generate_gate_up_proj_contains_both_outputs() {
        let out = generate_metal_source(&sample_region("gate_up_proj"));
        assert!(out.source.contains("gate_out"));
        assert!(out.source.contains("up_out"));
    }

    #[test]
    fn test_generate_silu_mul_contains_silu() {
        let out = generate_metal_source(&sample_region("silu_mul"));
        assert!(out.source.contains("silu_mul_kernel"));
        assert!(out.source.contains("sigmoid"));
        assert!(out.source.contains("exp("));
    }

    #[test]
    fn test_generate_rms_norm_residual_contains_rms() {
        let out = generate_metal_source(&sample_region("rms_norm_residual"));
        assert!(out.source.contains("sqrt"));
        assert!(out.source.contains("residual"));
    }

    #[test]
    fn test_generate_self_attn_contains_attention() {
        let out = generate_metal_source(&sample_region("self_attn"));
        assert!(out.source.contains("softmax"));
        assert!(out.source.contains("score"));
    }

    #[test]
    fn test_all_regions_compile_style() {
        for id in &[
            "qkv_proj",
            "attn_out",
            "gate_up_proj",
            "silu_mul",
            "down_proj",
            "rms_norm_residual",
            "self_attn",
        ] {
            let out = generate_metal_source(&sample_region(id));
            assert!(
                out.source.contains("#include <metal_stdlib>"),
                "{} missing metal_stdlib include",
                id
            );
            assert!(
                out.source.contains("kernel void"),
                "{} missing kernel declaration",
                id
            );
            assert!(out.entry_point.contains(id), "{} entry point mismatch", id);
        }
    }

    #[test]
    fn test_output_has_correct_entry_point() {
        let out = generate_metal_source(&sample_region("qkv_proj"));
        assert_eq!(out.entry_point, "qkv_proj_kernel");
    }
}
