[package]
name = "prism-plugin"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
libc = { workspace = true }
parking_lot = { workspace = true }
prism-video = { path = "../prism-video" }
prism-audio = { path = "../prism-audio" }

[dev-dependencies]
