//! Video generation via per-frame text-to-image with optional temporal
//! refinement.
//!
//! The [`VideoGenerator`] synthesizes a sequence of RGBA frames from a text
//! prompt (text-to-video) or from an initial frame (image-to-video).
//! Each frame is generated by the [`TextToImageGenerator`] with seed-controlled
//! variation.  Frame-to-frame conditioning provides temporal consistency.

use std::sync::Arc;

use crate::profiled_executor::LoadedProfiledModel;

// ── TextToImageGenerator ───────────────────────────────────────────────────

/// A text-to-image generator that produces a single RGBA frame from a text
/// prompt and a seed.
///
/// Each call with a different seed produces a different frame.  An optional
/// latent (from the previous frame) can be passed for temporal conditioning.
pub struct TextToImageGenerator {
    /// Underlying generative model (typically a diffusion or flow-matching
    /// model loaded via MLX).  `None` during development/stub mode.
    model: Option<Arc<LoadedProfiledModel>>,
}

impl TextToImageGenerator {
    /// Create a new text-to-image generator backed by the given model.
    pub fn new(model: Option<Arc<LoadedProfiledModel>>) -> Self {
        Self { model }
    }

    /// Generate a single RGBA frame from a text prompt.
    ///
    /// The `seed` controls the random noise used during generation, allowing
    /// deterministic frame sequences.  `latent` is an optional previous-frame
    /// latent for temporal conditioning.
    ///
    /// Returns `(width, height, RGBA pixel data)` at a fixed 512×512
    /// resolution.  In production this would run a diffusion model via MLX;
    /// here we synthesise deterministic noise-based frames for stub testing.
    pub fn generate(
        &self,
        _prompt: &str,
        seed: u64,
        _latent: Option<&[u8]>,
    ) -> Result<(u32, u32, Vec<u8>), String> {
        let width = 512u32;
        let height = 512u32;
        let total_pixels = (width * height) as usize;
        let mut pixels = Vec::with_capacity(total_pixels * 4);

        // Simple deterministic noise — each seed produces a unique but stable
        // frame.  In production this runs the actual diffusion forward pass.
        let mut state = seed;
        for _ in 0..total_pixels {
            state = state
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            let r = (state >> 24) as u8;
            state = state
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            let g = (state >> 24) as u8;
            state = state
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            let b = (state >> 24) as u8;
            pixels.extend_from_slice(&[r, g, b, 255]);
        }

        // Temporal conditioning stub: in production this would modulate the
        // diffusion latent with cross-frame attention / temporal layers.
        if _latent.is_some() {
            // Blend with previous frame for temporal consistency — skipped
            // in the stub; real implementation uses latent-space interpolation.
        }

        Ok((width, height, pixels))
    }
}

// ── VideoGenerator ─────────────────────────────────────────────────────────

/// Generates a video (sequence of RGBA frames) from a text prompt or an
/// initial image using a per-frame text-to-image model.
///
/// Temporal consistency is maintained by:
/// 1. Seeding each frame from the previous frame's latent.
/// 2. Passing the raw previous-frame pixels as conditioning.
/// 3. (Optional) a separate temporal refinement model that smooths the
///    output sequence.
pub struct VideoGenerator {
    /// Per-frame text-to-image generator — produces each frame individually.
    pub frame_gen: Arc<TextToImageGenerator>,
    /// Optional temporal-refinement model (e.g. a lightweight inter-frame
    /// attention or frame interpolation model).
    pub temporal_model: Option<Arc<LoadedProfiledModel>>,
}

impl VideoGenerator {
    /// Create a new video generator backed by the given frame generator.
    pub fn new(frame_gen: Arc<TextToImageGenerator>) -> Self {
        Self {
            frame_gen,
            temporal_model: None,
        }
    }

    /// Generate a video from a text prompt.
    ///
    /// Each frame is produced by [`TextToImageGenerator::generate`] with
    /// a seed derived from the initial `seed` plus the frame index, and
    /// with the previous frame's pixel data passed as the latent.
    ///
    /// * `prompt` — the text description of the video content.
    /// * `num_frames` — how many frames to generate.
    /// * `fps` — target frame rate (stored for metadata; does not affect
    ///   the generation loop).
    /// * `seed` — base seed; each frame uses `seed + frame_index`.
    ///
    /// Returns a `Vec` of `(width, height, RGBA data)` tuples, one per
    /// frame, in temporal order.
    pub fn text_to_video(
        &self,
        prompt: &str,
        num_frames: u32,
        fps: u32,
        seed: u64,
    ) -> Result<Vec<(u32, u32, Vec<u8>)>, String> {
        let _ = fps; // unused in stub — real impl adjusts denoising steps
        let mut frames = Vec::with_capacity(num_frames as usize);
        let mut prev_latent: Option<Vec<u8>> = None;

        for i in 0..num_frames {
            let frame_seed = seed.wrapping_add(i as u64);
            let latent_slice = prev_latent.as_deref();
            let (w, h, pixels) = self.frame_gen.generate(prompt, frame_seed, latent_slice)?;
            prev_latent = Some(pixels.clone());
            frames.push((w, h, pixels));
        }

        // Optional temporal smoothing pass
        if let Some(_model) = &self.temporal_model {
            // Run temporal-refinement model over the frame sequence
            // (e.g. frame interpolation, smoothing, or latent-space blending).
            // Stub: no-op.
        }

        Ok(frames)
    }

    /// Generate a video continuing from an initial image.
    ///
    /// The first frame of the output is derived from `initial_frame` (raw
    /// RGBA pixel data).  Subsequent frames are generated with seed-based
    /// variation conditioned on the preceding frame's pixels.
    ///
    /// * `initial_frame` — raw RGBA byte slice `[H × W × 4]`.
    /// * `prompt` — text prompt describing the action/change.
    /// * `num_frames` — total frames to produce (including the initial one).
    /// * `fps` — target frame rate.
    ///
    /// Returns a `Vec` of `(width, height, RGBA data)` tuples, one per
    /// frame, in temporal order.  The first tuple corresponds to the
    /// (potentially re-encoded) initial frame, and the rest are generated.
    pub fn image_to_video(
        &self,
        initial_frame: &[u8],
        prompt: &str,
        num_frames: u32,
        fps: u32,
    ) -> Result<Vec<(u32, u32, Vec<u8>)>, String> {
        let _ = fps;
        // Infer dimensions from the initial frame — it must be RGBA.
        if initial_frame.len() % 4 != 0 {
            return Err("initial_frame length must be a multiple of 4 (RGBA)".into());
        }
        let pixel_count = initial_frame.len() / 4;
        // Assume square-ish layout: derive nearest plausible width.
        // In production the caller provides explicit dimensions.
        let side = (pixel_count as f64).sqrt() as u32;
        if side * side * 4 != initial_frame.len() as u32 {
            return Err(format!(
                "initial_frame must be square ({} pixels = {} × {} is not a perfect square)",
                pixel_count, side, side
            ));
        }
        let width = side;
        let height = side;

        let mut frames = Vec::with_capacity(num_frames as usize);

        // Frame 0: use the provided initial image as-is (normalized).
        frames.push((width, height, initial_frame.to_vec()));
        let mut prev_latent = Some(initial_frame.to_vec());

        // Frames 1..num_frames-1: generate from prompt + previous latent.
        for i in 1..num_frames {
            let frame_seed = (i as u64).wrapping_mul(6364136223846793005);
            let latent_slice = prev_latent.as_deref();
            let (w, h, pixels) = self.frame_gen.generate(prompt, frame_seed, latent_slice)?;
            prev_latent = Some(pixels.clone());
            frames.push((w, h, pixels));
        }

        // Optional temporal smoothing
        if let Some(_model) = &self.temporal_model {
            // Stub: no-op.
        }

        Ok(frames)
    }
}
