//! MIL program text generators for ANE CImage compilation.
//!
//! Authority: pure string composition of MIL (Model Intermediate Language)
//! programs targeting Apple Neural Engine.
//!
//! These generators produce MIL text that the engine's Core ML backend
//! compiles into ANE executables. They are pure functions — no
//! filesystem, no FFI, no engine state. The same generators can be
//! used by any test harness or by the engine's `legacy_ane::AneCompressor`
//! when it loads a `kv_decompress_program` into Core ML.
//!
//! # Pipeline
//!
//! The decompression pipeline per page is:
//! 1. Read packed bits from IOSurface input.
//! 2. Dequantize: packed bits → FP16 values (polar dequant with scale).
//! 3. Apply QJL correction: add/subtract residual magnitude.
//! 4. Apply inverse Hadamard transform (Hadamard is self-inverse).
//! 5. Write FP16 output to IOSurface.

/// Generate MIL program text for KV cache decompression.
///
/// The program reads a compressed KV page from `compressed_input`
/// IOSurface, decompresses it through an element-wise MIL graph, and
/// writes FP16 values to `decompressed_output` IOSurface.
///
/// `head_dim`: dimension per KV head (e.g. 120 for Gemma4, 64 for Qwen).
/// `n_kv_heads`: number of KV heads.
/// `bits`: quantization bits per value (3-4).
pub fn generate_kv_decompress_mil(head_dim: u32, n_kv_heads: u32, bits: u32) -> String {
    let mut mil = String::new();

    // Prologue: auto-generated header with parameters
    mil.push_str("# Generated by Tribunus ANE KV Decompression\n");
    mil.push_str("# head_dim: ");
    mil.push_str(&head_dim.to_string());
    mil.push_str(" n_kv_heads: ");
    mil.push_str(&n_kv_heads.to_string());
    mil.push_str(" bits: ");
    mil.push_str(&bits.to_string());
    mil.push_str("\n\n");

    // Input: packed bytes from IOSurface
    mil.push_str(&format!(
        "input @ {name} (float16, {size}) read write\n",
        name = "compressed_input",
        size = (head_dim * n_kv_heads * bits / 16).max(64),
    ));

    // Output: decompressed FP16 to IOSurface
    mil.push_str(&format!(
        "output @ {name} (float16, {size}) read write\n\n",
        name = "decompressed_output",
        size = head_dim * n_kv_heads,
    ));

    // Dequantize: unpack bits and apply scale (mode: "polar" for TurboQuant polar dequant)
    mil.push_str(&format!(
        "layer dequant {{\n  type: dequantize\n  input: \"compressed_input\"\n  output: \"unpacked\"\n  mode: \"polar\"\n  bits: {}\n}}\n",
        bits,
    ));

    // Apply QJL correction (element-wise additive residual)
    mil.push_str(
        "layer qjl_correct {\n  type: add\n  input: \"unpacked\"\n  output: \"corrected\"\n}\n",
    );

    // Inverse Hadamard transform (Hadamard is self-inverse, same operation)
    mil.push_str(
        "layer inv_hadamard {\n  type: hadamard_transform\n  input: \"corrected\"\n  output: \"decompressed_output\"\n}\n",
    );

    mil
}

/// Generate MIL program text for KV cache compression (FP16 → packed bits).
///
/// The program reads FP16 values from `input` IOSurface, quantises them
/// to `bits`-wide packed representation using polar quantisation, and
/// writes the packed bytes to `output`.
///
/// `head_dim`: dimension per KV head.
/// `n_kv_heads`: number of KV heads.
/// `bits`: quantization bits per value.
pub fn generate_kv_compress_mil(head_dim: u32, n_kv_heads: u32, bits: u32) -> String {
    let mut mil = String::new();

    mil.push_str("# Generated by Tribunus ANE KV Compression\n");
    mil.push_str(&format!(
        "# head_dim: {} n_kv_heads: {} bits: {}\n\n",
        head_dim, n_kv_heads, bits,
    ));

    let input_size = head_dim * n_kv_heads;
    mil.push_str(&format!(
        "input @ \"input\" (float16, {}) read write\n",
        input_size,
    ));

    let packed_size = (head_dim * n_kv_heads * bits / 16).max(64);
    mil.push_str(&format!(
        "output @ \"output\" (float16, {}) read write\n\n",
        packed_size,
    ));

    // Quantize: FP16 → packed bits using polar quantization.
    mil.push_str(&format!(
        "layer quantize {{\n  type: quantize\n  input: \"input\"\n  output: \"output\"\n  mode: \"polar\"\n  bits: {}\n}}\n",
        bits,
    ));

    mil
}

/// Generate MIL program text for sliding window attention.
///
/// Runs the attention computation for a sliding window layer on ANE:
/// 1. Read Q, K, V from IOSurface.
/// 2. Compute Q @ K^T (sliding window mask).
/// 3. Softmax.
/// 4. Output @ V.
/// 5. Write attention output to IOSurface.
///
/// `n_heads`: number of query heads.
/// `n_kv_heads`: number of key/value heads (GQA factor).
/// `head_dim`: dimension per head.
/// `window`: sliding window size in tokens.
pub fn generate_attention_mil(n_heads: u32, n_kv_heads: u32, head_dim: u32, window: u32) -> String {
    let mut mil = String::new();
    mil.push_str("// Tribunus ANE Sliding Window Attention\n");
    mil.push_str(&format!(
        "// n_heads: {} n_kv_heads: {} head_dim: {} window: {}\n\n",
        n_heads, n_kv_heads, head_dim, window,
    ));

    // Inputs
    let q_size = n_heads * head_dim;
    let kv_size = n_kv_heads * head_dim;
    let _seq_len = window;

    mil.push_str(&format!(
        "input @ \"query\" (float16, {}) read write\n",
        q_size,
    ));
    mil.push_str(&format!(
        "input @ \"key\" (float16, {}) read write\n",
        kv_size,
    ));
    mil.push_str(&format!(
        "input @ \"value\" (float16, {}) read write\n",
        kv_size,
    ));

    // Output
    mil.push_str(&format!(
        "output @ \"attention_output\" (float16, {}) read write\n\n",
        q_size,
    ));

    // Q @ K^T
    mil.push_str("layer qk_matmul {\n  type: batched_matmul\n  input: \"query\", \"key\"\n  output: \"scores\"\n  transpose_b: true\n}\n");

    // Sliding window mask (element-wise)
    mil.push_str("layer window_mask {\n  type: add\n  input: \"scores\"\n  output: \"masked_scores\"\n}\n");

    // Softmax
    mil.push_str(
        "layer softmax {\n  type: softmax\n  input: \"masked_scores\"\n  output: \"probs\"\n  axis: -1\n}\n",
    );

    // Attention output = probs @ V
    mil.push_str(
        "layer attn_matmul {\n  type: batched_matmul\n  input: \"probs\", \"value\"\n  output: \"attention_output\"\n}\n",
    );

    mil
}

/// Generate MIL program for L3 tier 2-bit compression (FP16 → 2-bit packed).
///
/// The program reads FP16 values from `value_input`, quantises them to
/// 2-bit using polar quantization with learned scale, and writes packed
/// bytes to `packed_output`. This is the cold-storage path: L3 DRAM heap
/// holds 2-bit compressed pages that are rare to access.
///
/// `head_dim`: dimension per KV head (e.g. 120 for Gemma4, 64 for Qwen).
/// `n_kv_heads`: number of KV heads.
pub fn generate_l3_compress_mil(head_dim: u32, n_kv_heads: u32) -> String {
    let mut mil = String::new();
    let bits: u32 = 2;

    mil.push_str("# Generated by Tribunus ANE L3 2-bit Compression\n");
    mil.push_str(&format!(
        "# head_dim: {} n_kv_heads: {} bits: {}\n\n",
        head_dim, n_kv_heads, bits,
    ));

    // Input: FP16 values from the decompressed page.
    let input_size = head_dim * n_kv_heads;
    mil.push_str(&format!(
        "input @ \"input\" (float16, {}) read write\n",
        input_size,
    ));

    // Output: packed 2-bit bytes (minimum 64 for ANE pipeline alignment).
    let packed_size = (head_dim * n_kv_heads * bits / 16).max(64);
    mil.push_str(&format!(
        "output @ \"output\" (float16, {}) read write\n\n",
        packed_size,
    ));

    // Quantize: FP16 → 2-bit packed bits using polar quantization.
    mil.push_str(&format!(
        "layer quantize {{\n  type: quantize\n  input: \"input\"\n  output: \"output\"\n  mode: \"polar\"\n  bits: {}\n}}\n",
        bits,
    ));

    mil
}

/// Generate MIL program for L3 tier 2-bit decompression (2-bit packed → FP16).
///
/// The program reads 2-bit packed bytes from `packed_input`,
/// dequantises them to FP16 values via polar dequantization, applies
/// QJL residual correction, applies the inverse Hadamard transform,
/// and writes FP16 output to `decompressed_output`. Matches the L2
/// decompression pipeline but with 2-bit precision for cold pages
/// stored in DRAM.
///
/// `head_dim`: dimension per KV head.
/// `n_kv_heads`: number of KV heads.
pub fn generate_l3_decompress_mil(head_dim: u32, n_kv_heads: u32) -> String {
    let mut mil = String::new();
    let bits: u32 = 2;

    mil.push_str("# Generated by Tribunus ANE L3 2-bit Decompression\n");
    mil.push_str(&format!(
        "# head_dim: {} n_kv_heads: {} bits: {}\n\n",
        head_dim, n_kv_heads, bits,
    ));

    // Input: packed 2-bit bytes.
    let packed_size = (head_dim * n_kv_heads * bits / 16).max(64);
    mil.push_str(&format!(
        "input @ \"input\" (float16, {}) read write\n",
        packed_size,
    ));

    // Output: decompressed FP16.
    let output_size = head_dim * n_kv_heads;
    mil.push_str(&format!(
        "output @ \"output\" (float16, {}) read write\n\n",
        output_size,
    ));

    // Dequantize: unpack 2-bit values and apply scale (polar mode).
    mil.push_str(&format!(
        "layer dequant {{\n  type: dequantize\n  input: \"input\"\n  output: \"unpacked\"\n  mode: \"polar\"\n  bits: {}\n}}\n",
        bits,
    ));

    // Apply QJL correction (element-wise additive residual).
    mil.push_str(
        "layer qjl_correct {\n  type: add\n  input: \"unpacked\"\n  output: \"corrected\"\n}\n",
    );

    // Inverse Hadamard transform (Hadamard is self-inverse).
    mil.push_str(
        "layer inv_hadamard {\n  type: hadamard_transform\n  input: \"corrected\"\n  output: \"output\"\n}\n",
    );

    mil
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn kv_decompress_mil_includes_header() {
        let mil = generate_kv_decompress_mil(64, 8, 4);
        assert!(mil.contains("# Generated by Tribunus ANE KV Decompression"));
        assert!(mil.contains("head_dim: 64"));
        assert!(mil.contains("n_kv_heads: 8"));
        assert!(mil.contains("bits: 4"));
    }

    #[test]
    fn kv_decompress_mil_has_pipeline_layers() {
        let mil = generate_kv_decompress_mil(64, 8, 4);
        assert!(mil.contains("layer dequant"));
        assert!(mil.contains("layer qjl_correct"));
        assert!(mil.contains("layer inv_hadamard"));
    }

    #[test]
    fn kv_compress_mil_quantizes() {
        let mil = generate_kv_compress_mil(64, 8, 4);
        assert!(mil.contains("layer quantize"));
        assert!(mil.contains("bits: 4"));
    }

    #[test]
    fn attention_mil_has_four_layers() {
        let mil = generate_attention_mil(8, 2, 64, 256);
        assert!(mil.contains("layer qk_matmul"));
        assert!(mil.contains("layer window_mask"));
        assert!(mil.contains("layer softmax"));
        assert!(mil.contains("layer attn_matmul"));
    }

    #[test]
    fn l3_compress_uses_2_bits() {
        let mil = generate_l3_compress_mil(64, 8);
        assert!(mil.contains("bits: 2"));
        assert!(mil.contains("layer quantize"));
    }

    #[test]
    fn l3_decompress_matches_l2_pipeline() {
        let mil = generate_l3_decompress_mil(64, 8);
        assert!(mil.contains("layer dequant"));
        assert!(mil.contains("layer qjl_correct"));
        assert!(mil.contains("layer inv_hadamard"));
        assert!(mil.contains("bits: 2"));
    }
}
