//! `headers` — emit the Cloudflare Pages `_headers` file from the
//! §15.4 policy in `OBSERVATORY_V1_SPEC.md`.
//!
//! The headers are real HTTP response headers served at the
//! edge. The CSP, HSTS, Referrer-Policy, Permissions-Policy,
//! COOP, and CORP are the security posture. The cache directives
//! are real. See ADR-032 D5 and D6.

/// A single header rule. A path prefix applies to every path
/// that begins with `prefix`. A `_headers` file supports both
/// exact paths and prefixes; the renderer uses the prefix form
/// (`/*` matches all paths; `/assets/*` matches the assets
/// directory).
#[derive(Debug, Clone)]
pub struct HeaderRule {
    pub path: &'static str,
    pub headers: &'static [(&'static str, &'static str)],
}

/// The v1 security and cache policy. Mirrors `OBSERVATORY_V1_SPEC.md`
/// §15.4 and §15.5. Editing this is a spec-affecting change.
pub const HEADER_RULES: &[HeaderRule] = &[
    HeaderRule {
        path: "/*",
        headers: &[
            ("Strict-Transport-Security", "max-age=31536000; includeSubDomains; preload"),
            ("X-Content-Type-Options", "nosniff"),
            ("Referrer-Policy", "strict-origin-when-cross-origin"),
            (
                "Content-Security-Policy",
                "default-src 'self'; script-src 'self'; style-src 'self'; \
                 img-src 'self' data:; font-src 'self'; connect-src 'self'; \
                 frame-ancestors 'none'; base-uri 'self'; form-action 'self'",
            ),
            ("Permissions-Policy", "camera=(), microphone=(), geolocation=()"),
            ("Cross-Origin-Opener-Policy", "same-origin"),
            ("Cross-Origin-Resource-Policy", "same-origin"),
        ],
    },
    HeaderRule {
        path: "/*",
        headers: &[("Cache-Control", "public, max-age=0, must-revalidate")],
    },
    HeaderRule {
        path: "/assets/*",
        headers: &[("Cache-Control", "public, max-age=31536000, immutable")],
    },
    HeaderRule {
        path: "/pkg/*",
        headers: &[("Cache-Control", "public, max-age=31536000, immutable")],
    },
];

/// Render the header rules to a Cloudflare Pages `_headers`
/// file body. The format is:
///
/// ```text
/// <path>
///   <header-name>: <value>
///   <header-name>: <value>
/// ```
pub fn render_headers() -> String {
    let mut out = String::new();
    out.push_str("# _headers — generated by prism-docs-ssg.\n");
    out.push_str("# Source: OBSERVATORY_V1_SPEC.md §15.4 and §15.5.\n");
    out.push_str("# These are real HTTP response headers served at the edge.\n");
    out.push_str("# Do not edit by hand; update the spec and the SSG table.\n\n");

    for rule in HEADER_RULES {
        out.push_str(&format!("{}\n", rule.path));
        for (name, value) in rule.headers {
            // Indent header lines for readability; Cloudflare's
            // _headers format is whitespace-tolerant.
            out.push_str(&format!("  {}: {}\n", name, value));
        }
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn csp_is_strict() {
        let csp = HEADER_RULES
            .iter()
            .flat_map(|r| r.headers.iter())
            .find(|(n, _)| *n == "Content-Security-Policy")
            .expect("CSP must be present");
        assert!(csp.1.contains("frame-ancestors 'none'"), "CSP must include frame-ancestors 'none'");
        assert!(csp.1.contains("base-uri 'self'"), "CSP must include base-uri 'self'");
        assert!(csp.1.contains("form-action 'self'"), "CSP must include form-action 'self'");
        // Must not include unsafe-eval or unsafe-inline.
        assert!(!csp.1.contains("unsafe-eval"), "CSP must not include unsafe-eval");
        assert!(!csp.1.contains("unsafe-inline"), "CSP must not include unsafe-inline");
    }

    #[test]
    fn hsts_is_long_enough() {
        let hsts = HEADER_RULES
            .iter()
            .flat_map(|r| r.headers.iter())
            .find(|(n, _)| *n == "Strict-Transport-Security")
            .expect("HSTS must be present");
        assert!(hsts.1.contains("max-age=31536000"), "HSTS max-age must be at least one year");
    }

    #[test]
    fn assets_and_pkg_are_immutable() {
        let paths_with_immutable: Vec<&str> = HEADER_RULES
            .iter()
            .filter(|r| {
                r.headers.iter().any(|(n, v)| {
                    *n == "Cache-Control" && v.contains("immutable")
                })
            })
            .map(|r| r.path)
            .collect();
        assert!(paths_with_immutable.contains(&"/assets/*"), "/assets/* must be immutable");
        assert!(paths_with_immutable.contains(&"/pkg/*"), "/pkg/* must be immutable");
    }

    #[test]
    fn html_pages_revalidate() {
        let ctl = HEADER_RULES
            .iter()
            .flat_map(|r| r.headers.iter())
            .find(|(n, v)| *n == "Cache-Control" && v.contains("max-age=0"))
            .expect("HTML revalidation must be present");
        assert!(ctl.1.contains("must-revalidate"));
    }

    #[test]
    fn rendered_file_is_well_formed() {
        let body = render_headers();
        assert!(body.contains("# _headers"));
        // Every rule's path appears.
        for rule in HEADER_RULES {
            assert!(body.contains(rule.path), "missing path in render: {}", rule.path);
        }
    }
}
