//! Hydration JS — the only client-side code the site ships.
//!
//! This file is generated. It is a projection of the same world
//! the SSG renders. The typed components project to data
//! attributes; the hydration reads them and reconciles the DOM.
//!
//! The hydration is the only path that mutates the live DOM.
//! Every other renderer is a projection at SSG time.

/// The hydration source. Reads three sets of data attributes
/// and wires up the corresponding interactivity.
pub const HYDRATION_JS: &str = r#"
/* prism-docs hydration — generated by prism-docs-ssg.
 * This is the only client-side code on the site. It reads
 * data-* attributes (which are projections of typed
 * components) and reconciles the DOM. Do not edit by hand.
 */
(function () {
  'use strict';

  // ---------------------------------------------------------------------
  // Capability filter.
  // data-component="capability-filter" — the filter strip.
  // data-component="capability-grid" — the card grid.
  // Each .capability-filter button has data-filter="<domain>".
  // Each .capability-card has data-domain="<domain>".
  // ---------------------------------------------------------------------
  function wireCapabilityFilter() {
    var filterRoot = document.querySelector('[data-component="capability-filter"]');
    if (!filterRoot) return;
    var grid = document.querySelector('[data-component="capability-grid"]');
    if (!grid) return;
    var buttons = filterRoot.querySelectorAll('.capability-filter');
    var cards = grid.querySelectorAll('.capability-card');
    buttons.forEach(function (button) {
      button.addEventListener('click', function () {
        var filter = button.getAttribute('data-filter');
        var wasActive = button.getAttribute('aria-pressed') === 'true';
        buttons.forEach(function (b) { b.setAttribute('aria-pressed', 'false'); });
        if (wasActive) {
          button.setAttribute('aria-pressed', 'true');
        }
        cards.forEach(function (card) {
          if (filter === 'all' || wasActive && filter === 'all') {
            card.removeAttribute('data-hidden');
          } else if (card.getAttribute('data-domain') === filter) {
            card.removeAttribute('data-hidden');
          } else {
            card.setAttribute('data-hidden', 'true');
          }
        });
      });
    });
  }

  // ---------------------------------------------------------------------
  // Demo workflow stage control.
  // data-component="demo-workflow" — the four gates.
  // data-component="demo-controls" — the stage buttons.
  // data-stage="<n>" — which stage a button activates.
  // ---------------------------------------------------------------------
  function wireDemoWorkflow() {
    var workflow = document.querySelector('[data-component="demo-workflow"]');
    if (!workflow) return;
    var controls = document.querySelectorAll('.demo-control');
    var gates = workflow.querySelectorAll('.demo-gate');
    controls.forEach(function (button) {
      button.addEventListener('click', function () {
        var stage = parseInt(button.getAttribute('data-stage') || '0', 10);
        gates.forEach(function (gate, i) {
          if (i === stage) {
            gate.setAttribute('data-active', 'true');
          } else {
            gate.setAttribute('data-active', 'false');
          }
        });
      });
    });
  }

  // ---------------------------------------------------------------------
  // Projection rebuilder stage strip.
  // data-component="projection-stage" — the surface.
  // data-component="projection-stages" — the strip of stage buttons.
  // data-stage="<n>" — which stage a button activates.
  // The SVG canvas is the canonical subject; the stage strip
  // shows where the projection sits in the rebuild sequence.
  // ---------------------------------------------------------------------
  function wireProjectionStages() {
    var stageRoot = document.querySelector('[data-component="projection-stage"]');
    if (!stageRoot) return;
    var stageButtons = stageRoot.querySelectorAll('.projection-stage-step');
    stageButtons.forEach(function (button) {
      button.addEventListener('click', function () {
        var stage = parseInt(button.getAttribute('data-stage') || '0', 10);
        stageButtons.forEach(function (b, i) {
          if (i === stage) {
            b.setAttribute('aria-current', 'true');
          } else {
            b.setAttribute('aria-current', 'false');
          }
        });
      });
    });
  }

  // ---------------------------------------------------------------------
  // Wire all interactive components. The order is irrelevant;
  // each function is idempotent and reads from the typed
  // attributes the SSG already emitted.
  // ---------------------------------------------------------------------
  function wireAll() {
    wireCapabilityFilter();
    wireDemoWorkflow();
    wireProjectionStages();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', wireAll);
  } else {
    wireAll();
  }
})();
"#;
