//! `redirects` — emit the Cloudflare Pages `_redirects` file from
//! the §7.2 table in `OBSERVATORY_V1_SPEC.md`.
//!
//! The redirect table is part of the SSG's input. The validator
//! checks that every legacy path resolves to a canonical path.
//! Canonical paths are emitted as pages, not redirects; the
//! redirect table contains only legacy source paths.
//!
//! The generated file uses the standard Cloudflare Pages format:
//! `source destination status`. See ADR-032 D3.

/// A single redirect entry. The destination is a canonical
/// route; the source is a legacy path.
#[derive(Debug, Clone, Copy)]
pub struct Redirect {
    pub source: &'static str,
    pub destination: &'static str,
}

/// The canonical v1 redirect table. Mirrors `OBSERVATORY_V1_SPEC.md`
/// §7.2 exactly. Adding a legacy path here is a spec-affecting
/// change; the table is the operational source of truth.
pub const REDIRECTS: &[Redirect] = &[
    Redirect { source: "/index.html",            destination: "/" },
    Redirect { source: "/architecture.html",     destination: "/architecture/" },
    Redirect { source: "/capabilities.html",     destination: "/status/" },
    Redirect { source: "/capabilities/",         destination: "/status/" },
    Redirect { source: "/computeimage.html",     destination: "/computeimage/" },
    Redirect { source: "/heterogeneous.html",    destination: "/architecture/" },
    Redirect { source: "/heterogeneous/",        destination: "/architecture/" },
    Redirect { source: "/roadmap.html",          destination: "/roadmap/" },
    // /prism-ml/ and /general-compute/ are conditional;
    // their legacy HTML variants redirect to /lab/ in v1
    // (per §6.12 and §6.13 — the conditional route gate is
    // not satisfied; see ADR-034).
    Redirect { source: "/prism-ml.html",         destination: "/lab/" },
    Redirect { source: "/general-compute.html",  destination: "/lab/" },
    Redirect { source: "/work-with-prism.html",  destination: "/prismagent/" },
    Redirect { source: "/work-with-prism/",      destination: "/prismagent/" },
    Redirect { source: "/demo.html",             destination: "/observatory/life/" },
    Redirect { source: "/demo/",                 destination: "/observatory/life/" },
    Redirect { source: "/projection-repro.html", destination: "/observatory/life/" },
    Redirect { source: "/projection-repro/",     destination: "/observatory/life/" },
    Redirect { source: "/field-guide.html",      destination: "/start/" },
    Redirect { source: "/field-guide/",          destination: "/start/" },
    Redirect { source: "/start-here.html",       destination: "/start/" },
    Redirect { source: "/start-here/",           destination: "/start/" },
    Redirect { source: "/run.html",              destination: "/run/" },
    Redirect { source: "/evidence.html",         destination: "/evidence/" },
];

/// Render the redirect table to a Cloudflare Pages `_redirects`
/// file body. The format is one entry per line: `source
/// destination 301`. Empty lines and a leading comment line
/// documenting the source are included.
pub fn render_redirects() -> String {
    let mut out = String::new();
    out.push_str("# _redirects — generated by prism-docs-ssg.\n");
    out.push_str("# Source: OBSERVATORY_V1_SPEC.md §7.2.\n");
    out.push_str("# Format: <legacy source> <canonical destination> 301\n");
    out.push_str("# Do not edit by hand; update the spec and the SSG table.\n");
    for r in REDIRECTS {
        out.push_str(&format!("{:<32}{:<24}301\n", r.source, r.destination));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_covers_all_spec_entries() {
        // The spec lists 22 legacy paths (excluding duplicates that
        // would self-redirect). The table covers the same set.
        assert!(REDIRECTS.len() >= 22, "redirect table too small");
    }

    #[test]
    fn no_self_redirects() {
        for r in REDIRECTS {
            assert_ne!(r.source, r.destination, "self-redirect at {}", r.source);
        }
    }

    #[test]
    fn every_source_is_legacy() {
        for r in REDIRECTS {
            // Legacy paths end in .html or are old route slugs.
            assert!(
                r.source.ends_with(".html") || r.source.starts_with("/work-with-prism")
                    || r.source.starts_with("/demo")
                    || r.source.starts_with("/projection-repro")
                    || r.source.starts_with("/field-guide")
                    || r.source.starts_with("/start-here")
                    || r.source.starts_with("/heterogeneous")
                    || r.source.starts_with("/capabilities")
                    || r.source.starts_with("/index.html")
                    || r.source.starts_with("/computeimage")
                    || r.source.starts_with("/roadmap")
                    || r.source.starts_with("/run")
                    || r.source.starts_with("/evidence")
                    || r.source.starts_with("/prism-ml")
                    || r.source.starts_with("/general-compute")
                    || r.source.starts_with("/architecture"),
                "non-legacy source path: {}", r.source
            );
        }
    }

    #[test]
    fn every_destination_is_canonical() {
        for r in REDIRECTS {
            assert!(r.destination.starts_with('/'), "destination not absolute: {}", r.destination);
            assert!(r.destination.ends_with('/') || r.destination == "/", "destination not directory-shaped: {}", r.destination);
        }
    }

    #[test]
    fn rendered_file_is_well_formed() {
        let body = render_redirects();
        let mut redirect_count = 0;
        for line in body.lines() {
            if line.starts_with('#') || line.is_empty() { continue; }
            let parts: Vec<&str> = line.split_whitespace().collect();
            assert_eq!(parts.len(), 3, "malformed redirect line: {line}");
            assert_eq!(parts[2], "301", "non-301 redirect: {line}");
            redirect_count += 1;
        }
        assert_eq!(redirect_count, REDIRECTS.len(), "rendered count mismatch");
    }
}
