//! `selection_controller` — the client-side reducer that owns
//! the addressable selection state.
//!
//! Per `OBSERVATORY_V1_SPEC.md` §5.3 and §8, the SelectionController
//! is the sole owner of selection state. `Specimen`, `Journey`,
//! the Observatory instruments, and any other component that
//! displays selection state consume the controller's broadcast.
//! `Navigation` and `SiteShell` do not.
//!
//! The controller is a reducer: it parses selection from the
//! URL, validates against the schema, normalizes, writes back
//! to the URL, and broadcasts changes to subscribers. It does
//! not render DOM, does not perform network requests, and does
//! not persist selection beyond the URL.
//!
//! The controller is emitted as a JavaScript module loaded
//! alongside the page. Subscribers register via
//! `window.prismSelection.subscribe(callback)`. The current
//! selection is read via `window.prismSelection.current()`. The
//! URL is the source of truth.

/// The SelectionController JavaScript source. Loaded as a
/// `<script type="module">` after the page's static HTML; the
/// static HTML carries the default selection (per the no-JS
/// parity rule of §5.4), and the controller deepens the view by
/// listening for changes and broadcasting them.
pub const SELECTION_CONTROLLER_JS: &str = r#"
// Prism Observatory v1 — SelectionController.
// Generated by prism-docs-ssg. Do not edit by hand.
//
// The sole owner of the addressable selection state. Parses
// selection from the URL, validates, normalizes, writes back,
// and broadcasts to subscribers. The URL is the source of truth.

(function () {
  'use strict';

  // ---------- Schema (declarative) ----------

  // The known selection dimensions. Each is optional. The URL
  // carries them as query parameters. Unknown parameters are
  // ignored. The reducer normalizes the URL after a write.
  var SCHEMA = {
    stage:        { kind: 'integer', min: 1, max: 12 },
    density:      { kind: 'enum',    values: ['overview', 'technical', 'raw-artifact'] },
    tensor:       { kind: 'string',  pattern: /^[a-zA-Z0-9._-]+$/ },
    capability:   { kind: 'string',  pattern: /^capability\.[a-zA-Z0-9._-]+$/ },
    evidence:     { kind: 'string',  pattern: /^evidence\.[a-zA-Z0-9._-]+$/ },
    specimen:     { kind: 'string',  pattern: /^observatory\.specimen\.[a-zA-Z0-9._-]+$/ }
  };

  // ---------- Reducer ----------

  function readFromUrl() {
    var u;
    try { u = new URL(window.location.href); }
    catch (e) { return {}; }
    var out = {};
    var keys = Object.keys(SCHEMA);
    for (var i = 0; i < keys.length; i++) {
      var k = keys[i];
      var raw = u.searchParams.get(k);
      if (raw == null) continue;
      var parsed = parseValue(k, raw);
      if (parsed !== undefined) out[k] = parsed;
    }
    return out;
  }

  function parseValue(key, raw) {
    var def = SCHEMA[key];
    if (!def) return undefined;
    if (def.kind === 'integer') {
      var n = parseInt(raw, 10);
      if (isNaN(n)) return undefined;
      if (def.min != null && n < def.min) return undefined;
      if (def.max != null && n > def.max) return undefined;
      return n;
    }
    if (def.kind === 'enum') {
      if (def.values.indexOf(raw) === -1) return undefined;
      return raw;
    }
    if (def.kind === 'string') {
      if (def.pattern && !def.pattern.test(raw)) return undefined;
      return raw;
    }
    return undefined;
  }

  function writeToUrl(selection) {
    var u;
    try { u = new URL(window.location.href); }
    catch (e) { return; }
    var keys = Object.keys(SCHEMA);
    for (var i = 0; i < keys.length; i++) {
      var k = keys[i];
      if (selection[k] == null) {
        u.searchParams.delete(k);
      } else {
        u.searchParams.set(k, String(selection[k]));
      }
    }
    // Use replaceState so the browser history is not polluted.
    try {
      window.history.replaceState(null, '', u.toString());
    } catch (e) { /* no-op */ }
  }

  // ---------- Broadcast ----------

  var subscribers = [];
  var current = readFromUrl();

  function broadcast(prev) {
    for (var i = 0; i < subscribers.length; i++) {
      try { subscribers[i](current, prev); }
      catch (e) { /* a single subscriber failure must not break the others */ }
    }
  }

  // ---------- Public API ----------

  function subscribe(callback) {
    if (typeof callback !== 'function') return function () {};
    subscribers.push(callback);
    // Fire once on subscribe so the new subscriber sees the
    // current state without waiting for the next change.
    try { callback(current, current); } catch (e) { /* no-op */ }
    return function unsubscribe() {
      var idx = subscribers.indexOf(callback);
      if (idx !== -1) subscribers.splice(idx, 1);
    };
  }

  function set(partial) {
    if (partial == null || typeof partial !== 'object') return;
    var prev = {};
    for (var k in current) prev[k] = current[k];
    var next = {};
    for (var k in current) next[k] = current[k];
    var keys = Object.keys(partial);
    for (var i = 0; i < keys.length; i++) {
      var k = keys[i];
      if (!(k in SCHEMA)) continue;
      var v = partial[k];
      if (v == null) {
        delete next[k];
      } else {
        var parsed = parseValue(k, String(v));
        if (parsed !== undefined) next[k] = parsed;
      }
    }
    current = next;
    writeToUrl(current);
    broadcast(prev);
  }

  function get() {
    var out = {};
    for (var k in current) out[k] = current[k];
    return out;
  }

  // ---------- Wire up popstate ----------

  window.addEventListener('popstate', function () {
    var prev = current;
    current = readFromUrl();
    broadcast(prev);
  });

  // ---------- Expose ----------

  window.prismSelection = {
    subscribe: subscribe,
    set: set,
    get: get,
    schema: SCHEMA
  };
})();
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn selection_controller_is_non_empty() {
        assert!(!SELECTION_CONTROLLER_JS.is_empty());
        assert!(SELECTION_CONTROLLER_JS.contains("prismSelection"));
    }

    #[test]
    fn selection_controller_uses_replace_state() {
        // Per the spec: writes to the URL use replaceState so the
        // browser history is not polluted by selection changes.
        assert!(SELECTION_CONTROLLER_JS.contains("replaceState"));
    }

    #[test]
    fn selection_controller_handles_popstate() {
        // Back/forward navigation re-reads the URL and broadcasts.
        assert!(SELECTION_CONTROLLER_JS.contains("popstate"));
    }

    #[test]
    fn selection_controller_does_not_perform_network_requests() {
        // The controller is a reducer; it must not make network calls.
        let network_calls = ["fetch(", "XMLHttpRequest", "WebSocket", "EventSource"];
        for needle in &network_calls {
            assert!(
                !SELECTION_CONTROLLER_JS.contains(needle),
                "controller must not use {}",
                needle
            );
        }
    }
}
