// Prism Observatory v1 — ThemeProvider.
// Generated by prism-docs-ssg. Do not edit by hand.
//
// The sole owner of the dark/light theme attribute. Reads the
// visitor's preference (localStorage) on first visit, falls
// back to prefers-color-scheme, writes the data-theme
// attribute on <html>, persists subsequent changes.
//
// Per §A22, the visitor's preference persists. Per §9, the
// choice must be readable in the URL? No — theme is a
// presentation choice, not an addressable selection. The
// SelectionController does not see it.
//
// The no-flash guard runs synchronously in <head> before
// paint, so the visitor never sees the wrong theme. See the
// `pre-paint-theme` block emitted by the renderer.

(function () {
  'use strict';

  var STORAGE_KEY = 'prism-theme';
  var VALID = { dark: 'dark', light: 'light' };

  function readStored() {
    try {
      var v = window.localStorage.getItem(STORAGE_KEY);
      if (v === VALID.dark || v === VALID.light) return v;
    } catch (e) {
      // localStorage may be denied (private mode, file://).
      // Fall through to system preference.
    }
    return null;
  }

  function readSystem() {
    try {
      if (window.matchMedia &&
          window.matchMedia('(prefers-color-scheme: light)').matches) {
        return VALID.light;
      }
    } catch (e) {
      // matchMedia unavailable. Stay dark.
    }
    return VALID.dark;
  }

  function current() {
    var attr = document.documentElement.getAttribute('data-theme');
    if (attr === VALID.dark || attr === VALID.light) return attr;
    return VALID.dark;
  }

  function apply(theme) {
    if (theme !== VALID.dark && theme !== VALID.light) return;
    document.documentElement.setAttribute('data-theme', theme);
    // Mirror the system color-scheme for the UA (form
    // controls, scrollbars, default focus rings). The
    // [data-theme] selector in CSS sets this too; the
    // attribute write is the redundant belt-and-braces.
    try {
      document.documentElement.style.colorScheme = theme;
    } catch (e) { /* color-scheme unsupported */ }
    // Re-render the toggle's pressed state.
    var btn = document.querySelector('.theme-toggle');
    if (btn) btn.setAttribute('aria-pressed', String(theme === VALID.light));
  }

  function persist(theme) {
    try {
      window.localStorage.setItem(STORAGE_KEY, theme);
    } catch (e) {
      // localStorage denied. The choice is volatile but
      // the toggle still works for the session.
    }
  }

  function toggle() {
    apply(current() === VALID.dark ? VALID.light : VALID.dark);
    persist(current());
  }

  // ---------- Wire the toggle button ----------

  function wireToggle() {
    var btn = document.querySelector('.theme-toggle');
    if (!btn) return;
    btn.setAttribute('aria-pressed', String(current() === VALID.light));
    btn.addEventListener('click', function (ev) {
      ev.preventDefault();
      toggle();
    });
  }

  // ---------- Track system preference changes ----------
  //
  // If the visitor has not chosen, follow the system. Once
  // they choose, the system change does not override.

  function wireSystem() {
    if (!window.matchMedia) return;
    var mq = window.matchMedia('(prefers-color-scheme: light)');
    var listener = function (ev) {
      if (readStored() != null) return; // user choice wins
      apply(ev.matches ? VALID.light : VALID.dark);
    };
    if (mq.addEventListener) mq.addEventListener('change', listener);
    else if (mq.addListener) mq.addListener(listener);
  }

  // ---------- Bootstrap ----------
  //
  // The no-flash guard has already set the data-theme on
  // <html> before this script runs. We just verify and wire.

  function boot() {
    apply(current());
    wireToggle();
    wireSystem();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', boot);
  } else {
    boot();
  }

  // ---------- Expose ----------

  window.prismTheme = {
    current: current,
    set: function (t) { apply(t); persist(t); },
    toggle: toggle
  };
})();
