use crate::compute_image::manifest::{
    AliasEntry, CompilationAuthority, CompileReceipt, CompiledImage, ImageBuilder,
    Manifest, ManifestVerification, Segment, TensorEntry,
};
use crate::compute_image::phase_dag::EmittedPhaseGraph;
use crate::config::LayerPlan;
use crate::profiled_model::LayerWeights;
use serde::{Deserialize, Serialize};
use std::sync::Arc;

// ---------------------------------------------------------------------------
// Identifier types
// ---------------------------------------------------------------------------

/// A stable, content-addressed identifier for a ComputeImage.
#[derive(Debug, Clone, Hash, Eq, PartialEq, Serialize, Deserialize)]
pub struct ComputeImageId(pub String);

/// Identifier for a target hardware profile (e.g. "apple-m1-pro-16", "apple-m4-max-64").
#[derive(Debug, Clone, Hash, Eq, PartialEq, Serialize, Deserialize)]
pub struct TargetProfileId(pub String);

// ---------------------------------------------------------------------------
// Placeholder types — to be replaced by proper implementations once the
// corresponding modules (phase_program_version, fusion_abi) are populated.
// ---------------------------------------------------------------------------

/// Placeholder for the compiled phase program version identifier.
///
/// To be replaced by `crate::compute_image::phase_program_version::PhaseProgramVersion`
/// once that module is implemented.
#[derive(Debug, Clone, Hash, Eq, PartialEq, Serialize, Deserialize)]
pub struct PhaseProgramVersion(pub u32);

/// Pre-computed RoPE trigonometric tables for the model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RopeTables {
    /// Cosine table for rotary positions.
    pub cos: Vec<f32>,
    /// Sine table for rotary positions.
    pub sin: Vec<f32>,
    /// Full cosine table covering max sequence length.
    pub full_cos: Vec<f32>,
    /// Full sine table covering max sequence length.
    pub full_sin: Vec<f32>,
}

/// Registry of compiled fusion artifact bindings.
///
/// To be replaced by `crate::compute_image::fusion_abi::FusionBindingRegistry`
/// once the fusion ABI is extended with a registry type.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct FusionBindingRegistry {
    /// All sealed metal fusion artifacts available to this image.
    pub artifacts: Vec<crate::compute_image::fusion_abi::SealedMetalFusionArtifact>,
}

// ---------------------------------------------------------------------------
// ComputeImageState
// ---------------------------------------------------------------------------

/// Immutable state derived from a sealed ComputeImage.
///
/// This is the sole source of truth for model architecture, weights,
/// fusion artifacts, and compilation decisions. It is shareable across
/// concurrent sessions and never mutated after construction.
///
/// # Send + Sync
///
/// All heap-allocated fields use `Arc`, making the entire struct `Send + Sync`.
pub struct ComputeImageState {
    /// Content-addressed identifier for this image.
    pub image_id: ComputeImageId,
    /// The target hardware profile this image was compiled for.
    pub target_profile: TargetProfileId,
    /// Emitted phase DAG — the compiler's acyclic execution plan.
    pub phase_graph: Arc<EmittedPhaseGraph>,
    /// Version of the phase program schema used during compilation.
    pub phase_program_version: PhaseProgramVersion,
    /// Per-layer execution plan generated by the compiler.
    pub layer_plans: Arc<[LayerPlan]>,
    /// All layer weight projections loaded from the compiled image.
    pub layer_weights: Arc<[LayerWeights]>,
    /// Pre-computed RoPE trigonometric tables.
    pub rope_tables: Arc<RopeTables>,
    /// Fusion artifact binding metadata (Metal, Core ML, etc.).
    pub artifacts: Arc<FusionBindingRegistry>,
    /// Resolved fusion binding dispatch table.
    pub fusion_bindings: Arc<FusionBindingRegistry>,
    /// Core ML artifact bindings for ANE‑routed phases.
    pub coreml_artifacts: Arc<FusionBindingRegistry>,
    /// Verification bundle containing content-hash and integrity evidence.
    pub verification_bundle: Arc<ManifestVerification>,
}

impl ComputeImageState {
    /// Construct from an existing loaded model and its compiled phase graph.
    ///
    /// Only callable after manifest validation and target profile
    /// compatibility checks have passed.
    pub fn new(
        _model: &crate::profiled_model::LoadedProfiledModel,
        _graph: EmittedPhaseGraph,
    ) -> Self {
        // Construction logic requires types not yet fully imported in this
        // module — extension points: layer-plan extraction, artifact registry
        // assembly, verification-bundle ingestion, and profile-id derivation.
        todo!()
    }
}
