// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(prism_bridgeFFI)
    import prism_bridgeFFI
#endif

private extension RustBuffer {
    /// Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_prism_bridge_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    /// Frees the buffer in place.
    /// The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_prism_bridge_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

/// Reads an integer at the current offset, in big-endian order, and advances
/// the offset on success. Throws if reading the integer would move the
/// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

/// Reads an arbitrary number of bytes, to be used to read
/// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

/// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

/// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

/// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S: Sequence>(_ writer: inout [UInt8], _ byteArr: S) where S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

/// Writes an integer in big-endian order.
///
/// Warning: make sure what you are trying to write
/// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

/// Protocol for types that transfer other types across the FFI. This is
/// analogous go the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

/// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

/// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
/// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

/// An error type for FFI errors. These errors occur at the UniFFI level, not
/// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: nil)
}

private func rustCallWithError<T>(
    _ errorHandler: @escaping (RustBuffer) throws -> Error,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

private struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

private struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

private struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

private struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

private struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return try Data(readBytes(&buf, count: Int(len)))
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}

/**
 * A loaded .cimage model ready for inference.  Passes by reference
 * (Arc) across the FFI boundary — the multiplexer holds the Metal
 * buffers, ECS world, and ANE state.
 */
public protocol BridgeMultiplexerProtocol: AnyObject {}

/**
 * A loaded .cimage model ready for inference.  Passes by reference
 * (Arc) across the FFI boundary — the multiplexer holds the Metal
 * buffers, ECS world, and ANE state.
 */
open class BridgeMultiplexer:
    BridgeMultiplexerProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    /// This constructor can be used to instantiate a fake object.
    /// - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    ///
    /// - Warning:
    ///     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_prism_bridge_fn_clone_bridgemultiplexer(self.pointer, $0) }
    }

    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_prism_bridge_fn_free_bridgemultiplexer(pointer, $0) }
    }

    /**
     * Load a compiled .cimage and initialise the runtime multiplexer.
     */
    public static func load(cimagePath: String, modelDir: String) throws -> BridgeMultiplexer {
        return try FfiConverterTypeBridgeMultiplexer.lift(rustCallWithError(FfiConverterTypeBridgeError.lift) {
            uniffi_prism_bridge_fn_constructor_bridgemultiplexer_load(
                FfiConverterString.lower(cimagePath),
                FfiConverterString.lower(modelDir), $0
            )
        })
    }
}

public struct FfiConverterTypeBridgeMultiplexer: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = BridgeMultiplexer

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> BridgeMultiplexer {
        return BridgeMultiplexer(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: BridgeMultiplexer) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BridgeMultiplexer {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: BridgeMultiplexer, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

public func FfiConverterTypeBridgeMultiplexer_lift(_ pointer: UnsafeMutableRawPointer) throws -> BridgeMultiplexer {
    return try FfiConverterTypeBridgeMultiplexer.lift(pointer)
}

public func FfiConverterTypeBridgeMultiplexer_lower(_ value: BridgeMultiplexer) -> UnsafeMutableRawPointer {
    return FfiConverterTypeBridgeMultiplexer.lower(value)
}

/**
 * Serializable agent state.
 */
public struct BridgeAgentState {
    public var phase: BridgePhase
    public var historyJsonl: String
    public var currentPrompt: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(phase: BridgePhase, historyJsonl: String, currentPrompt: String) {
        self.phase = phase
        self.historyJsonl = historyJsonl
        self.currentPrompt = currentPrompt
    }
}

extension BridgeAgentState: Equatable, Hashable {
    public static func == (lhs: BridgeAgentState, rhs: BridgeAgentState) -> Bool {
        if lhs.phase != rhs.phase {
            return false
        }
        if lhs.historyJsonl != rhs.historyJsonl {
            return false
        }
        if lhs.currentPrompt != rhs.currentPrompt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(phase)
        hasher.combine(historyJsonl)
        hasher.combine(currentPrompt)
    }
}

public struct FfiConverterTypeBridgeAgentState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BridgeAgentState {
        return
            try BridgeAgentState(
                phase: FfiConverterTypeBridgePhase.read(from: &buf),
                historyJsonl: FfiConverterString.read(from: &buf),
                currentPrompt: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: BridgeAgentState, into buf: inout [UInt8]) {
        FfiConverterTypeBridgePhase.write(value.phase, into: &buf)
        FfiConverterString.write(value.historyJsonl, into: &buf)
        FfiConverterString.write(value.currentPrompt, into: &buf)
    }
}

public func FfiConverterTypeBridgeAgentState_lift(_ buf: RustBuffer) throws -> BridgeAgentState {
    return try FfiConverterTypeBridgeAgentState.lift(buf)
}

public func FfiConverterTypeBridgeAgentState_lower(_ value: BridgeAgentState) -> RustBuffer {
    return FfiConverterTypeBridgeAgentState.lower(value)
}

/**
 * Combined result payload returned to Swift.
 */
public struct BridgeStepResult {
    public var state: BridgeAgentState
    public var outcome: BridgeStepOutcome

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(state: BridgeAgentState, outcome: BridgeStepOutcome) {
        self.state = state
        self.outcome = outcome
    }
}

extension BridgeStepResult: Equatable, Hashable {
    public static func == (lhs: BridgeStepResult, rhs: BridgeStepResult) -> Bool {
        if lhs.state != rhs.state {
            return false
        }
        if lhs.outcome != rhs.outcome {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(state)
        hasher.combine(outcome)
    }
}

public struct FfiConverterTypeBridgeStepResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BridgeStepResult {
        return
            try BridgeStepResult(
                state: FfiConverterTypeBridgeAgentState.read(from: &buf),
                outcome: FfiConverterTypeBridgeStepOutcome.read(from: &buf)
            )
    }

    public static func write(_ value: BridgeStepResult, into buf: inout [UInt8]) {
        FfiConverterTypeBridgeAgentState.write(value.state, into: &buf)
        FfiConverterTypeBridgeStepOutcome.write(value.outcome, into: &buf)
    }
}

public func FfiConverterTypeBridgeStepResult_lift(_ buf: RustBuffer) throws -> BridgeStepResult {
    return try FfiConverterTypeBridgeStepResult.lift(buf)
}

public func FfiConverterTypeBridgeStepResult_lower(_ value: BridgeStepResult) -> RustBuffer {
    return FfiConverterTypeBridgeStepResult.lower(value)
}

/**
 * A spawned subagent.
 */
public struct BridgeSubagentHandle {
    public var id: UInt64
    public var goal: String
    public var sandboxSubpath: String
    public var maxRevisions: UInt8

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(id: UInt64, goal: String, sandboxSubpath: String, maxRevisions: UInt8) {
        self.id = id
        self.goal = goal
        self.sandboxSubpath = sandboxSubpath
        self.maxRevisions = maxRevisions
    }
}

extension BridgeSubagentHandle: Equatable, Hashable {
    public static func == (lhs: BridgeSubagentHandle, rhs: BridgeSubagentHandle) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.goal != rhs.goal {
            return false
        }
        if lhs.sandboxSubpath != rhs.sandboxSubpath {
            return false
        }
        if lhs.maxRevisions != rhs.maxRevisions {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(goal)
        hasher.combine(sandboxSubpath)
        hasher.combine(maxRevisions)
    }
}

public struct FfiConverterTypeBridgeSubagentHandle: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BridgeSubagentHandle {
        return
            try BridgeSubagentHandle(
                id: FfiConverterUInt64.read(from: &buf),
                goal: FfiConverterString.read(from: &buf),
                sandboxSubpath: FfiConverterString.read(from: &buf),
                maxRevisions: FfiConverterUInt8.read(from: &buf)
            )
    }

    public static func write(_ value: BridgeSubagentHandle, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.id, into: &buf)
        FfiConverterString.write(value.goal, into: &buf)
        FfiConverterString.write(value.sandboxSubpath, into: &buf)
        FfiConverterUInt8.write(value.maxRevisions, into: &buf)
    }
}

public func FfiConverterTypeBridgeSubagentHandle_lift(_ buf: RustBuffer) throws -> BridgeSubagentHandle {
    return try FfiConverterTypeBridgeSubagentHandle.lift(buf)
}

public func FfiConverterTypeBridgeSubagentHandle_lower(_ value: BridgeSubagentHandle) -> RustBuffer {
    return FfiConverterTypeBridgeSubagentHandle.lower(value)
}

/**
 * A tool call emitted by the model.
 */
public struct BridgeToolCall {
    public var id: String
    public var name: String
    public var argumentsJson: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(id: String, name: String, argumentsJson: String) {
        self.id = id
        self.name = name
        self.argumentsJson = argumentsJson
    }
}

extension BridgeToolCall: Equatable, Hashable {
    public static func == (lhs: BridgeToolCall, rhs: BridgeToolCall) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.argumentsJson != rhs.argumentsJson {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(argumentsJson)
    }
}

public struct FfiConverterTypeBridgeToolCall: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BridgeToolCall {
        return
            try BridgeToolCall(
                id: FfiConverterString.read(from: &buf),
                name: FfiConverterString.read(from: &buf),
                argumentsJson: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: BridgeToolCall, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.argumentsJson, into: &buf)
    }
}

public func FfiConverterTypeBridgeToolCall_lift(_ buf: RustBuffer) throws -> BridgeToolCall {
    return try FfiConverterTypeBridgeToolCall.lift(buf)
}

public func FfiConverterTypeBridgeToolCall_lower(_ value: BridgeToolCall) -> RustBuffer {
    return FfiConverterTypeBridgeToolCall.lower(value)
}

/**
 * A tool definition for the model.
 */
public struct BridgeToolDefinition {
    public var name: String
    public var description: String
    public var parametersJson: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(name: String, description: String, parametersJson: String) {
        self.name = name
        self.description = description
        self.parametersJson = parametersJson
    }
}

extension BridgeToolDefinition: Equatable, Hashable {
    public static func == (lhs: BridgeToolDefinition, rhs: BridgeToolDefinition) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        if lhs.parametersJson != rhs.parametersJson {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(description)
        hasher.combine(parametersJson)
    }
}

public struct FfiConverterTypeBridgeToolDefinition: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BridgeToolDefinition {
        return
            try BridgeToolDefinition(
                name: FfiConverterString.read(from: &buf),
                description: FfiConverterString.read(from: &buf),
                parametersJson: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: BridgeToolDefinition, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterString.write(value.parametersJson, into: &buf)
    }
}

public func FfiConverterTypeBridgeToolDefinition_lift(_ buf: RustBuffer) throws -> BridgeToolDefinition {
    return try FfiConverterTypeBridgeToolDefinition.lift(buf)
}

public func FfiConverterTypeBridgeToolDefinition_lower(_ value: BridgeToolDefinition) -> RustBuffer {
    return FfiConverterTypeBridgeToolDefinition.lower(value)
}

/**
 * Errors that can cross the UniFFI boundary.
 */
public enum BridgeError {
    case CimageLoadFailed(message: String)
}

public struct FfiConverterTypeBridgeError: FfiConverterRustBuffer {
    typealias SwiftType = BridgeError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BridgeError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .CimageLoadFailed(
                message: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BridgeError, into buf: inout [UInt8]) {
        switch value {
        case .CimageLoadFailed(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(1))
        }
    }
}

extension BridgeError: Equatable, Hashable {}

extension BridgeError: Error {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/* 
 * Current phase of the agent state machine.
 */

public enum BridgePhase {
    case idle
    case generating
    case awaitingTools
    case awaitingSubagents
    case done
}

public struct FfiConverterTypeBridgePhase: FfiConverterRustBuffer {
    typealias SwiftType = BridgePhase

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BridgePhase {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .idle

        case 2: return .generating

        case 3: return .awaitingTools

        case 4: return .awaitingSubagents

        case 5: return .done

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BridgePhase, into buf: inout [UInt8]) {
        switch value {
        case .idle:
            writeInt(&buf, Int32(1))

        case .generating:
            writeInt(&buf, Int32(2))

        case .awaitingTools:
            writeInt(&buf, Int32(3))

        case .awaitingSubagents:
            writeInt(&buf, Int32(4))

        case .done:
            writeInt(&buf, Int32(5))
        }
    }
}

public func FfiConverterTypeBridgePhase_lift(_ buf: RustBuffer) throws -> BridgePhase {
    return try FfiConverterTypeBridgePhase.lift(buf)
}

public func FfiConverterTypeBridgePhase_lower(_ value: BridgePhase) -> RustBuffer {
    return FfiConverterTypeBridgePhase.lower(value)
}

extension BridgePhase: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/* 
 * Outcome of one `prism_agent_step` call.
 */

public enum BridgeStepOutcome {
    case generating
    case awaitingTools(tools: [BridgeToolCall])
    case awaitingSubagents(subagents: [BridgeSubagentHandle])
    case finished(result: String)
}

public struct FfiConverterTypeBridgeStepOutcome: FfiConverterRustBuffer {
    typealias SwiftType = BridgeStepOutcome

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BridgeStepOutcome {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .generating

        case 2: return try .awaitingTools(tools: FfiConverterSequenceTypeBridgeToolCall.read(from: &buf))

        case 3: return try .awaitingSubagents(subagents: FfiConverterSequenceTypeBridgeSubagentHandle.read(from: &buf))

        case 4: return try .finished(result: FfiConverterString.read(from: &buf))

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BridgeStepOutcome, into buf: inout [UInt8]) {
        switch value {
        case .generating:
            writeInt(&buf, Int32(1))

        case let .awaitingTools(tools):
            writeInt(&buf, Int32(2))
            FfiConverterSequenceTypeBridgeToolCall.write(tools, into: &buf)

        case let .awaitingSubagents(subagents):
            writeInt(&buf, Int32(3))
            FfiConverterSequenceTypeBridgeSubagentHandle.write(subagents, into: &buf)

        case let .finished(result):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(result, into: &buf)
        }
    }
}

public func FfiConverterTypeBridgeStepOutcome_lift(_ buf: RustBuffer) throws -> BridgeStepOutcome {
    return try FfiConverterTypeBridgeStepOutcome.lift(buf)
}

public func FfiConverterTypeBridgeStepOutcome_lower(_ value: BridgeStepOutcome) -> RustBuffer {
    return FfiConverterTypeBridgeStepOutcome.lower(value)
}

extension BridgeStepOutcome: Equatable, Hashable {}

/**
 * Errors during GGUF→cimage compilation.
 */
public enum CompilerError {
    case InvalidFormat(message: String)

    case IoError(message: String)

    case QuantizationFailed(message: String)
}

public struct FfiConverterTypeCompilerError: FfiConverterRustBuffer {
    typealias SwiftType = CompilerError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CompilerError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .InvalidFormat(
                message: FfiConverterString.read(from: &buf)
            )

        case 2: return try .IoError(
                message: FfiConverterString.read(from: &buf)
            )

        case 3: return try .QuantizationFailed(
                message: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CompilerError, into buf: inout [UInt8]) {
        switch value {
        case .InvalidFormat(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(1))
        case .IoError(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(2))
        case .QuantizationFailed(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(3))
        }
    }
}

extension CompilerError: Equatable, Hashable {}

extension CompilerError: Error {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/* 
 * A single event in the streaming inference output stream.
 *
 * Text tokens arrive as `Text`.  Raw media (uncompressed pixels, PCM audio,
 * embeddings) arrives as the other variants — Vec<u8> maps to Swift's
 * Foundation.Data and Vec<f32> maps to [Float] with zero manual conversion.
 *
 * Each `VideoFrame` carries a monotonic `timestamp_ns` so the Swift export
 * pipeline (AVAssetWriter → ProRes .mov) can reconstruct a deterministic
 * timeline that NLEs like DaVinci Resolve or Final Cut Pro accept without
 * resampling or drift correction.
 */

public enum StreamEvent {
    case text(token: String)
    /**
     * Raw uncompressed BGRA 8-bit pixel array for direct CVPixelBuffer wrapping.
     */
    case imageFrame(pixelBytes: Data, width: UInt32, height: UInt32)
    /**
     * Raw uncompressed BGRA 8-bit pixel array with high-precision timestamp
     * for ProRes video track assembly.
     */
    case videoFrame(pixelBytes: Data, width: UInt32, height: UInt32, timestampNs: UInt64)
    /**
     * Raw Linear PCM audio bytes (32-bit float or 16-bit int) for Core Audio
     * CMSampleBuffer ingestion.  `sample_rate` in Hz, `channels` = 1 (mono)
     * or 2 (stereo).
     */
    case audioChunk(pcmBytes: Data, sampleRate: UInt32, channels: UInt32)
    /**
     * Dense vector embedding from the model.  Used for similarity search,
     * clustering, or conditioning downstream generators.
     */
    case embedding(values: [Float])
}

public struct FfiConverterTypeStreamEvent: FfiConverterRustBuffer {
    typealias SwiftType = StreamEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StreamEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .text(token: FfiConverterString.read(from: &buf))

        case 2: return try .imageFrame(pixelBytes: FfiConverterData.read(from: &buf), width: FfiConverterUInt32.read(from: &buf), height: FfiConverterUInt32.read(from: &buf))

        case 3: return try .videoFrame(pixelBytes: FfiConverterData.read(from: &buf), width: FfiConverterUInt32.read(from: &buf), height: FfiConverterUInt32.read(from: &buf), timestampNs: FfiConverterUInt64.read(from: &buf))

        case 4: return try .audioChunk(pcmBytes: FfiConverterData.read(from: &buf), sampleRate: FfiConverterUInt32.read(from: &buf), channels: FfiConverterUInt32.read(from: &buf))

        case 5: return try .embedding(values: FfiConverterSequenceFloat.read(from: &buf))

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: StreamEvent, into buf: inout [UInt8]) {
        switch value {
        case let .text(token):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(token, into: &buf)

        case let .imageFrame(pixelBytes, width, height):
            writeInt(&buf, Int32(2))
            FfiConverterData.write(pixelBytes, into: &buf)
            FfiConverterUInt32.write(width, into: &buf)
            FfiConverterUInt32.write(height, into: &buf)

        case let .videoFrame(pixelBytes, width, height, timestampNs):
            writeInt(&buf, Int32(3))
            FfiConverterData.write(pixelBytes, into: &buf)
            FfiConverterUInt32.write(width, into: &buf)
            FfiConverterUInt32.write(height, into: &buf)
            FfiConverterUInt64.write(timestampNs, into: &buf)

        case let .audioChunk(pcmBytes, sampleRate, channels):
            writeInt(&buf, Int32(4))
            FfiConverterData.write(pcmBytes, into: &buf)
            FfiConverterUInt32.write(sampleRate, into: &buf)
            FfiConverterUInt32.write(channels, into: &buf)

        case let .embedding(values):
            writeInt(&buf, Int32(5))
            FfiConverterSequenceFloat.write(values, into: &buf)
        }
    }
}

public func FfiConverterTypeStreamEvent_lift(_ buf: RustBuffer) throws -> StreamEvent {
    return try FfiConverterTypeStreamEvent.lift(buf)
}

public func FfiConverterTypeStreamEvent_lower(_ value: StreamEvent) -> RustBuffer {
    return FfiConverterTypeStreamEvent.lower(value)
}

extension StreamEvent: Equatable, Hashable {}

/**
 * Callback interface that lets the V8 sandbox drive the WKWebView.
 * Implemented in Swift — each method blocks the V8 thread until the
 * WebKit operation completes on the Main Actor.
 */
public protocol BrowserRuntimeDriver: AnyObject {
    /**
     * Navigate to a URL. Returns "ok" or an error message starting with "ERROR:".
     */
    func navigate(url: String) -> String

    /**
     * Return the semantic DOM snapshot as JSON, or an error starting with "ERROR:".
     */
    func snapshot() -> String

    /**
     * Interact with an element. Returns "ok" or an error starting with "ERROR:".
     */
    func interact(id: UInt32, action: String, value: String?) -> String

    /**
     * Evaluate JS in the page. Returns the result, or "ERROR: ...".
     */
    func evaluateJs(script: String) -> String

    /**
     * Download a URL using the browser's authenticated session.
     */
    func download(url: String, filename: String) -> String
}

/// Magic number for the Rust proxy to call using the same mechanism as every other method,
/// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

/// Put the implementation in a struct so we don't pollute the top-level namespace
private enum UniffiCallbackInterfaceBrowserRuntimeDriver {
    /// Create the VTable using a series of closures.
    /// Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceBrowserRuntimeDriver = .init(
        navigate: { (
            uniffiHandle: UInt64,
            url: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceBrowserRuntimeDriver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.navigate(
                    url: FfiConverterString.lift(url)
                )
            }

            let writeReturn = { uniffiOutReturn.pointee = FfiConverterString.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        snapshot: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceBrowserRuntimeDriver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.snapshot(
                )
            }

            let writeReturn = { uniffiOutReturn.pointee = FfiConverterString.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        interact: { (
            uniffiHandle: UInt64,
            id: UInt32,
            action: RustBuffer,
            value: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceBrowserRuntimeDriver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.interact(
                    id: FfiConverterUInt32.lift(id),
                    action: FfiConverterString.lift(action),
                    value: FfiConverterOptionString.lift(value)
                )
            }

            let writeReturn = { uniffiOutReturn.pointee = FfiConverterString.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        evaluateJs: { (
            uniffiHandle: UInt64,
            script: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceBrowserRuntimeDriver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.evaluateJs(
                    script: FfiConverterString.lift(script)
                )
            }

            let writeReturn = { uniffiOutReturn.pointee = FfiConverterString.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        download: { (
            uniffiHandle: UInt64,
            url: RustBuffer,
            filename: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceBrowserRuntimeDriver.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.download(
                    url: FfiConverterString.lift(url),
                    filename: FfiConverterString.lift(filename)
                )
            }

            let writeReturn = { uniffiOutReturn.pointee = FfiConverterString.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) in
            let result = try? FfiConverterCallbackInterfaceBrowserRuntimeDriver.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface BrowserRuntimeDriver: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitBrowserRuntimeDriver() {
    uniffi_prism_bridge_fn_init_callback_vtable_browserruntimedriver(&UniffiCallbackInterfaceBrowserRuntimeDriver.vtable)
}

/// FfiConverter protocol for callback interfaces
private enum FfiConverterCallbackInterfaceBrowserRuntimeDriver {
    fileprivate static var handleMap = UniffiHandleMap<BrowserRuntimeDriver>()
}

extension FfiConverterCallbackInterfaceBrowserRuntimeDriver: FfiConverter {
    typealias SwiftType = BrowserRuntimeDriver
    typealias FfiType = UInt64

    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

/**
 * Callback for deterministic compiler progress.
 */
public protocol CompilerProgressCallback: AnyObject {
    func onLog(message: String)

    func onProgress(percentage: Float)
}

/// Put the implementation in a struct so we don't pollute the top-level namespace
private enum UniffiCallbackInterfaceCompilerProgressCallback {
    /// Create the VTable using a series of closures.
    /// Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceCompilerProgressCallback = .init(
        onLog: { (
            uniffiHandle: UInt64,
            message: RustBuffer,
            _: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceCompilerProgressCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onLog(
                    message: FfiConverterString.lift(message)
                )
            }

            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onProgress: { (
            uniffiHandle: UInt64,
            percentage: Float,
            _: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceCompilerProgressCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onProgress(
                    percentage: FfiConverterFloat.lift(percentage)
                )
            }

            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) in
            let result = try? FfiConverterCallbackInterfaceCompilerProgressCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface CompilerProgressCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitCompilerProgressCallback() {
    uniffi_prism_bridge_fn_init_callback_vtable_compilerprogresscallback(&UniffiCallbackInterfaceCompilerProgressCallback.vtable)
}

/// FfiConverter protocol for callback interfaces
private enum FfiConverterCallbackInterfaceCompilerProgressCallback {
    fileprivate static var handleMap = UniffiHandleMap<CompilerProgressCallback>()
}

extension FfiConverterCallbackInterfaceCompilerProgressCallback: FfiConverter {
    typealias SwiftType = CompilerProgressCallback
    typealias FfiType = UInt64

    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

/**
 * Callback interface for multimodal streaming inference.
 */
public protocol MultimodalStreamCallback: AnyObject {
    /**
     * Called for each event in the output stream (text token, image, audio, etc.).
     */
    func onEvent(event: StreamEvent)

    /**
     * Generation completed successfully.
     */
    func onDone()

    /**
     * Generation failed.
     */
    func onError(error: String)
}

/// Put the implementation in a struct so we don't pollute the top-level namespace
private enum UniffiCallbackInterfaceMultimodalStreamCallback {
    /// Create the VTable using a series of closures.
    /// Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceMultimodalStreamCallback = .init(
        onEvent: { (
            uniffiHandle: UInt64,
            event: RustBuffer,
            _: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceMultimodalStreamCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onEvent(
                    event: FfiConverterTypeStreamEvent.lift(event)
                )
            }

            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onDone: { (
            uniffiHandle: UInt64,
            _: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceMultimodalStreamCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onDone(
                )
            }

            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onError: { (
            uniffiHandle: UInt64,
            error: RustBuffer,
            _: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceMultimodalStreamCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onError(
                    error: FfiConverterString.lift(error)
                )
            }

            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) in
            let result = try? FfiConverterCallbackInterfaceMultimodalStreamCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface MultimodalStreamCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitMultimodalStreamCallback() {
    uniffi_prism_bridge_fn_init_callback_vtable_multimodalstreamcallback(&UniffiCallbackInterfaceMultimodalStreamCallback.vtable)
}

/// FfiConverter protocol for callback interfaces
private enum FfiConverterCallbackInterfaceMultimodalStreamCallback {
    fileprivate static var handleMap = UniffiHandleMap<MultimodalStreamCallback>()
}

extension FfiConverterCallbackInterfaceMultimodalStreamCallback: FfiConverter {
    typealias SwiftType = MultimodalStreamCallback
    typealias FfiType = UInt64

    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

private struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private struct FfiConverterOptionCallbackInterfaceBrowserRuntimeDriver: FfiConverterRustBuffer {
    typealias SwiftType = BrowserRuntimeDriver?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterCallbackInterfaceBrowserRuntimeDriver.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterCallbackInterfaceBrowserRuntimeDriver.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private struct FfiConverterOptionCallbackInterfaceCompilerProgressCallback: FfiConverterRustBuffer {
    typealias SwiftType = CompilerProgressCallback?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterCallbackInterfaceCompilerProgressCallback.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterCallbackInterfaceCompilerProgressCallback.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private struct FfiConverterSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [Float]

    static func write(_ value: [Float], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterFloat.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Float] {
        let len: Int32 = try readInt(&buf)
        var seq = [Float]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterFloat.read(from: &buf))
        }
        return seq
    }
}

private struct FfiConverterSequenceTypeBridgeSubagentHandle: FfiConverterRustBuffer {
    typealias SwiftType = [BridgeSubagentHandle]

    static func write(_ value: [BridgeSubagentHandle], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeBridgeSubagentHandle.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [BridgeSubagentHandle] {
        let len: Int32 = try readInt(&buf)
        var seq = [BridgeSubagentHandle]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeBridgeSubagentHandle.read(from: &buf))
        }
        return seq
    }
}

private struct FfiConverterSequenceTypeBridgeToolCall: FfiConverterRustBuffer {
    typealias SwiftType = [BridgeToolCall]

    static func write(_ value: [BridgeToolCall], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeBridgeToolCall.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [BridgeToolCall] {
        let len: Int32 = try readInt(&buf)
        var seq = [BridgeToolCall]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeBridgeToolCall.read(from: &buf))
        }
        return seq
    }
}

private struct FfiConverterSequenceTypeBridgeToolDefinition: FfiConverterRustBuffer {
    typealias SwiftType = [BridgeToolDefinition]

    static func write(_ value: [BridgeToolDefinition], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeBridgeToolDefinition.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [BridgeToolDefinition] {
        let len: Int32 = try readInt(&buf)
        var seq = [BridgeToolDefinition]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeBridgeToolDefinition.read(from: &buf))
        }
        return seq
    }
}

/**
 * Drive one step of the agent state machine.
 *
 * Takes the current serialised state and the model's output text, runs the
 * pure state transition, and returns the new state + outcome.  The app is
 * responsible for calling inference externally and feeding the output here.
 */
public func prismAgentStep(stateJson: String, modelOutput: String) -> BridgeStepResult {
    return try! FfiConverterTypeBridgeStepResult.lift(try! rustCall {
        uniffi_prism_bridge_fn_func_prism_agent_step(
            FfiConverterString.lower(stateJson),
            FfiConverterString.lower(modelOutput), $0
        )
    })
}

/**
 * Compile a GGUF model file into a .cimage output directory.
 *
 * The output directory will contain the .cimage binary (loaded by
 * `BridgeMultiplexer.load`), manifest.json, segment files, and optional
 * ANE model archives.  Returns the path to the compiled output directory.
 */
public func prismCompileGguf(ggufPath: String, outputDir: String, callback: CompilerProgressCallback?) throws -> String {
    return try FfiConverterString.lift(rustCallWithError(FfiConverterTypeCompilerError.lift) {
        uniffi_prism_bridge_fn_func_prism_compile_gguf(
            FfiConverterString.lower(ggufPath),
            FfiConverterString.lower(outputDir),
            FfiConverterOptionCallbackInterfaceCompilerProgressCallback.lower(callback), $0
        )
    })
}

/**
 * Return the default set of sandbox file tools (read_file, write_file, etc.)
 * as JSON strings that the model can consume.
 */
public func prismDefaultTools() -> [BridgeToolDefinition] {
    return try! FfiConverterSequenceTypeBridgeToolDefinition.lift(try! rustCall {
        uniffi_prism_bridge_fn_func_prism_default_tools($0)
    })
}

/**
 * Run inference with streaming output, using the LUT engine path.
 *
 * `cimage_path` — compiled .cimage from `prism_compile_gguf`.
 * `model_dir` — directory containing tokenizer.json and config.json.
 */
public func prismInferMultimodalStream(cimagePath: String, modelDir: String, prompt: String, callback: MultimodalStreamCallback) {
    try! rustCall {
        uniffi_prism_bridge_fn_func_prism_infer_multimodal_stream(
            FfiConverterString.lower(cimagePath),
            FfiConverterString.lower(modelDir),
            FfiConverterString.lower(prompt),
            FfiConverterCallbackInterfaceMultimodalStreamCallback.lower(callback), $0
        )
    }
}

/**
 * Run JavaScript in the V8 sandbox with a browser driver for web ops.
 * The driver is called synchronously from V8 ops — it must block until
 * the WKWebView operation completes.
 */
public func prismRunJs(code: String, sandboxRoot: String, driver: BrowserRuntimeDriver?) -> String {
    return try! FfiConverterString.lift(try! rustCall {
        uniffi_prism_bridge_fn_func_prism_run_js(
            FfiConverterString.lower(code),
            FfiConverterString.lower(sandboxRoot),
            FfiConverterOptionCallbackInterfaceBrowserRuntimeDriver.lower(driver), $0
        )
    })
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

/// Use a global variables to perform the versioning checks. Swift ensures that
/// the code inside is only computed once.
private var initializationResult: InitializationResult {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_prism_bridge_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_prism_bridge_checksum_func_prism_agent_step() != 9963 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_prism_bridge_checksum_func_prism_compile_gguf() != 38930 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_prism_bridge_checksum_func_prism_default_tools() != 31886 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_prism_bridge_checksum_func_prism_infer_multimodal_stream() != 510 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_prism_bridge_checksum_func_prism_run_js() != 17689 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_prism_bridge_checksum_constructor_bridgemultiplexer_load() != 59071 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_prism_bridge_checksum_method_browserruntimedriver_navigate() != 25514 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_prism_bridge_checksum_method_browserruntimedriver_snapshot() != 41627 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_prism_bridge_checksum_method_browserruntimedriver_interact() != 57155 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_prism_bridge_checksum_method_browserruntimedriver_evaluate_js() != 31060 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_prism_bridge_checksum_method_browserruntimedriver_download() != 38235 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_prism_bridge_checksum_method_compilerprogresscallback_on_log() != 45151 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_prism_bridge_checksum_method_compilerprogresscallback_on_progress() != 57165 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_prism_bridge_checksum_method_multimodalstreamcallback_on_event() != 12608 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_prism_bridge_checksum_method_multimodalstreamcallback_on_done() != 54994 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_prism_bridge_checksum_method_multimodalstreamcallback_on_error() != 31629 {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitBrowserRuntimeDriver()
    uniffiCallbackInitCompilerProgressCallback()
    uniffiCallbackInitMultimodalStreamCallback()
    return InitializationResult.ok
}

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
